### PR TITLE
Fix race condition when interrupting applications

### LINKED ISSUE #9807: Unclean shutdown as a result of a race between shutdown hooks
For the purpose of this explanation I will refer to any shutdown sequence that completes without writing any errors to stdout/stderr as "clean shutdown" and any that writes such errors as "unclear shutdown". Clean deallocation of resources is not the focus of this bug report.

Let's have a look at this dead simple ZIO application:
```
import zio._

object CleanShutdown extends ZIOAppDefault {

  override def run: ZIO[Any, Throwable, Unit] =
    ZIO.never

}
```

It shuts down cleanly after receiving a SIGTERM/SIGINT. This is a welcome behaviour, but it's surprising given the `main` implementation https://github.com/zio/zio/blob/series/2.x/core/jvm-native/src/main/scala/zio/ZIOAppPlatformSpecific.scala

If we follow that code here's what I would expect to happen:
1. The `main` methods (which runs on the `main` thread) executes a `runtime.unsafe.run`
2. SIGTERM/SIGINT leads to execution of the shutdown hook, which interrupts the `fiber`
3. Interruption of `fiber` complets, the shutdown hook completes
4. the main thread joins the interrupted `fiber`, so the `runtime.unsafe.run` returns an `Exit` that is `Failed`/`Interrupted`
5. `getOrThrowFiberFailure` throws a `FiberFailure`
6. `java.lang.ThreadGroup#uncaughtException` prints `Exception in thread "main" ...` to stderr

But that's not what we see, because in this simple application the ZIO shutdown hook is the slowest (the only) shutdown hook, so right after it completes (3.), the `main` thread is stopped, and it happens fast enough that it doesn't print that uncaught Exception. 

But a real world application may have some other shutdown hooks, and those may run longer than the ZIO shutdown hook. We can simulate it with this application code:

```
import zio._

object UncleanShutdown extends ZIOAppDefault {

  java.lang.Runtime.getRuntime.addShutdownHook(new Thread {
    override def run(): Unit = {
      Thread.sleep(2000)
    }
  })

  override def run: ZIO[Any, Throwable, Unit] =
    ZIO.uninterruptible(ZIO.sleep(1000.milliseconds)).forever

}
```

On shutdown this application prints to stderr:

```
Exception in thread "main" Exception in thread "zio-fiber-163356120" java.lang.InterruptedException: Interrupted by thread "zio-fiber-404068148"
	Suppressed: java.lang.InterruptedException: Interrupted by thread "zio-fiber-404068148"
		Suppressed: java.lang.InterruptedException: Interrupted by thread "zio-fiber-404068148"
			Suppressed: java.lang.InterruptedException: Interrupted by thread "zio-fiber-404068148"
```

In a real world application the timing of these two hooks would be much more complex and depending on which one is faster we either get an error on shutdown or not.

That's a long explanation, so the state the nature of the bug clearly: I would expect the shutdown sequence to produce the same result regardless of relative timing of shutdown hooks, and I would expect no error printed to stderr.

I doubt that it matters but: I'm using ZIO `2.1.17` on `Temurin-17.0.4.1+1`

### PR DESCRIPTION
**Pull request by kyri-petrou**
/fixes #9807

The main issue here is that in cases where the shutdown hooks were taking some time to process, the `fiber.join` would win the race and the thrown Exception (in this case the interruption exception) would be thrown in the main thread. The fix is to make sure that all errors in `workflow` are caught (by using `exitWith` instead of `onExit`, and gracefully close the application with `exit(exitCode)` after we join the forked fiber.

I also made some cleanups in the logic so that it's easier to follow, since the code previously relied on unsafely running effects unnecessarily and was harder to follow terms of what was executed in what sequence

### CODE REVIEW

File: core/jvm-native/src/main/scala/zio/ZIOAppPlatformSpecific.scala [hunk 1]
```diff
@@ -24,20 +24,18 @@ private[zio] trait ZIOAppPlatformSpecific { self: ZIOApp =>
...
         for {
           fiberId <- ZIO.fiberId
-          p       <- Promise.make[Nothing, Set[FiberId.Runtime]]
-          fiber <- restore(workflow).onExit { exit0 =>
-                     val exitCode  = if (exit0.isSuccess) ExitCode.success else ExitCode.failure
-                     val interrupt = interruptRootFibers(p)
+          fiber <- workflow.interruptible.exitWith { exit0 =>
+                     val exitCode = if (exit0.isSuccess) ExitCode.success else ExitCode.failure
                      // If we're shutting down due to an external signal, the shutdown hook will fulfill the promise
                      // Otherwise it means we're shutting down due to normal completion and we need to fulfill the promise
```
Comment (hearnadam) [inline core/jvm-native/src/main/scala/zio/ZIOAppPlatformSpecific.scala]: leftover promise comments?

File: core/jvm-native/src/main/scala/zio/ZIOAppPlatformSpecific.scala [hunk 2]
```diff
@@ -49,27 +47,23 @@ private[zio] trait ZIOAppPlatformSpecific { self: ZIOApp =>
                   )
                 } else {
                   try {
```
Comment (hearnadam) [inline core/jvm-native/src/main/scala/zio/ZIOAppPlatformSpecific.scala:49]: Does this still need to be in a `try`?

**Review by hearnadam — DISMISSED** [review]
Would be nice if it was possible to test, but...

File: core/jvm-native/src/main/scala/zio/ZIOAppPlatformSpecific.scala (hunk 1 above)
Comment (kyri-petrou) [reply core/jvm-native/src/main/scala/zio/ZIOAppPlatformSpecific.scala]: Removed

File: core/jvm-native/src/main/scala/zio/ZIOAppPlatformSpecific.scala (hunk 2 above)
Comment (kyri-petrou) [reply core/jvm-native/src/main/scala/zio/ZIOAppPlatformSpecific.scala:49]: There is an extremely low chance (I can't reproduce, but theoretically it might be possible), that the submission of the task to the executor is rejected (due to shutdown) and throws a `RejectedExecutionException`.

As I said, I'm not even sure if that's possible but just wanted to be extra safe just in case

Comment (kyri-petrou) [reply core/jvm-native/src/main/scala/zio/ZIOAppPlatformSpecific.scala:49]: I added a comment to clarify
