### PR TITLE
Transfer child finalisers to parent in ZIO.raceAll and ZIO.raceFibersWith  #9203

### LINKED ISSUE #9203: [bug] ZIO.raceFirst sometimes prevents scope finalisers from running
I tried ZIO 2.0.0, 2.1.0, 2.1.9 (latest). All of them have the same issue.

Here's a test that reproduces the error
```scala
import zio._
import zio.test.TestAspect.timeout
import zio.test._

import java.util.concurrent.atomic.AtomicBoolean

object ZIORaceFirstBug extends ZIOSpecDefault {
  override def spec: Spec[Any, Any] =
    suite("ZIO.raceFirst")(
      test("should always call finalizers") {
        for {
          isRunning <- ZIO.succeed(new AtomicBoolean(true))

          backgroundBlockingStuff = ZIO.attemptBlocking(while (isRunning.get()) {})

          acquire = backgroundBlockingStuff.fork
          release = ZIO.succeed(isRunning.set(false))

          eff = ZIO.acquireRelease(acquire)(_ => release)

          // _ <- ZIO.scoped(eff) // this one works
          _ <- ZIO.scoped(ZIO.raceFirst(eff, Nil))

        } yield assertCompletes
      } @@ timeout(10.seconds)
    )
}

```

For some reason, when there's long-running blocking background operation wrapped into `ZIO.raceFirst`, finalisers are not called and test terminates due to timeout. If I replace `ZIO.scoped(ZIO.raceFirst(eff, Nil))` with `ZIO.scoped(eff)`, test immediately passes.
IMO racing an effect against an empty list should have no impact on how it behaves at all. My real case is way more complicated and I'm actually racing against a bunch of other stuff, so simple replacement as in this test is not an option. As a workaround I can do `(effect +: effects).reduce(_.raceFirst(_)` and it seems to work fine, but it's still surprising that `ZIO.raceFirst` doesn't work.

### PR DESCRIPTION
**Pull request by digy**
When forking child fibers in raceAll and raceFibersWith make sure that finalizers are moved to the parent fiber.

Solves #9203

### CODE REVIEW

File: core/shared/src/main/scala/zio/ZIO.scala [hunk 1]
```diff
@@ -1353,23 +1353,25 @@ sealed trait ZIO[-R, +E, +A]
...
-                    }
-
-               inheritAll = { (res: (A1, Fiber[E1, A1])) => res._2.inheritAll.as(res._1) }
-
-               c <- restore(done.await.flatMap(inheritAll))
-                      .onInterrupt(fs.foldLeft(ZIO.unit)((io, f) => io <* f.interrupt))
-             } yield c
-           }
-    } yield c)
+    ZIO.transplant { graft =>
```
Comment (kyri-petrou) [inline core/shared/src/main/scala/zio/ZIO.scala]: To improve performance, you can replace the `suspendSucceed` in L1336 with this

File: streams-tests/shared/src/test/scala/zio/stream/ZStreamSpec.scala [hunk 2]
```diff
@@ -2953,7 +2953,7 @@ object ZStreamSpec extends ZIOBaseSpec {
               _      <- queue2.offer(3)
               result <- fiber.join
             } yield assert(result)(equalTo(Chunk(1, 2)))
-          },
+          } @@ flaky,
```
Comment (kyri-petrou) [inline streams-tests/shared/src/test/scala/zio/stream/ZStreamSpec.scala]: Remove this for now, I'm working separately on fixing these (there are other flaky tests in this suite). I think it's caused by a race condition where the `TestClock.adjust` method might be called before the forked fiber has began execution

File: core/shared/src/main/scala/zio/ZIO.scala [hunk 3]
```diff
@@ -1423,48 +1425,50 @@ sealed trait ZIO[-R, +E, +A]
...
-        winner: Fiber.Runtime[E0, A],
-        loser: Fiber.Runtime[E1, B],
-        cont: (Fiber.Runtime[E0, A], Fiber.Runtime[E1, B]) => ZIO[R1, E2, C],
-        ab: AtomicBoolean,
-        cb: ZIO[R1, E2, C] => Any
-      ): Any =
-        if (ab.compareAndSet(true, false)) {
-          cb(cont(winner, loser))
-        }
+    ZIO.transplant { graft =>
```
Comment (kyri-petrou) [inline core/shared/src/main/scala/zio/ZIO.scala]: Maybe create the Grafter manually here to avoid calling `ZIO.withFiberRuntime` twice (see implementation of `ZIO.transplant`)

**Review by kyri-petrou — COMMENTED** [review]
LGTM, just some minor comments

File: core/shared/src/main/scala/zio/ZIO.scala (hunk 3 above)
Comment (kyri-petrou) [reply core/shared/src/main/scala/zio/ZIO.scala]: Note that you should probably add an apply method in `Grafter`s companion object that accepts a `Fiber.Runtime` method to avoid duplicating the logic

File: core/shared/src/main/scala/zio/ZIO.scala [hunk 4]
```diff
@@ -5511,6 +5507,18 @@ object ZIO extends ZIOCompanionPlatformSpecific with ZIOCompanionVersionSpecific
       }
   }
 
+  object Grafter {
+
+    def apply[E, A](fiberState: Fiber.Runtime[E, A])(implicit trace: Trace): Grafter = {
```
Comment (kyri-petrou) [inline core/shared/src/main/scala/zio/ZIO.scala]: Sorry for the nit 😅: AFAICT the type params are unnecessary, you can simply change the param to `Fiber.Runtime[?, ?]`

Comment (kyri-petrou) [reply core/shared/src/main/scala/zio/ZIO.scala]: Also let's make this method `private[ZIO]` for now

File: core-tests/shared/src/test/scala/zio/ZIOSpec.scala [hunk 5]
```diff
@@ -1959,7 +1960,17 @@ object ZIOSpec extends ZIOBaseSpec {
       } @@ flaky @@ zioTag(errors),
       test("returns success when it happens after failure") {
         assertZIO(ZIO.fail(42).raceAll(List(ZIO.succeed(24) <* Live.live(ZIO.sleep(100.millis)))))(equalTo(24))
-      } @@ zioTag(errors)
+      } @@ zioTag(errors),
+      test("always calls finalizers") {
+        for {
+          isRunning              <- ZIO.succeed(new AtomicBoolean(true))
+          backgroundBlockingStuff = ZIO.attemptBlocking(while (isRunning.get()) {})
```
Comment (kyri-petrou) [inline core-tests/shared/src/test/scala/zio/ZIOSpec.scala]: Sorry I only just noticed this. Can you change this to `ZIO.whileLoop(isRunning.get)(ZIO.yieldNow)(_ => ())` instead and below? Otherwise it might cause issues in low CPU environments due to the background thread being active all the time

**Review by kyri-petrou — APPROVED** [review]
