### PR TITLE
ZStream.aggregate, ZTransducer.collectAllWhile

### LINKED ISSUE #3290: New Stream encoding: very basic transducing doesn't work
I tried to write basic examples and failed so far:

```
testM("trans1"){
        val x = ZStream[Int](1,2,3).transduce[Any, Nothing, Int, Chunk[Int]](idSink.toTransducer).runCollect.map(l => l.flatMap(_.toSeq))
        assertM(x)(equalTo(List(1,2,3)))
      } @@ timeout(3.seconds),
testM("trans2"){
        val x = ZStream[Int](1,2,3).transduce[Any, Nothing, Int, Int](ZTransducer.chunkN(10)).runCollect
        assertM(x)(equalTo(List(1,2,3)))
} @@ timeout(3.seconds)

//returns incoming chunks untouched
def idSink[I]: ZSink[Any, Nothing, I, Chunk[I]] =
    ZSink(ZManaged.succeed({
      case Some(ch) => {
        //println("-- " + ch)
        Push.emit(ch)
      }
      case None => {
        //println("--None")
        Push.more
      }
    }))
```

Both tests fail due to timeout.
In the first one `idSink` continuously receives `None` input.

Pinging @regiskuckaertz and @iravid

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Closes #3290 

ZTransducer is missing map and flatMap before we can uncomment all the tests, I started working on it but prefer to do a PR for that only.

### CODE REVIEW

File: streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala [hunk 1]
```diff
@@ -82,6 +82,46 @@ abstract class ZStream[-R, +E, +O](
...
+   * Applies an aggregator to the stream, which converts one or more elements
+   * of type `A` into elements of type `B`.
+   */
+  def aggregate[R1 <: R, E1 >: E, O1 >: O, P](sink: ZTransducer[R1, E1, O1, P]): ZStream[R1, E1, P] =
+    aggregateManaged(ZManaged.succeedNow(sink))
+
+  /**
+   * Applies a managed transducer to the stream, converting elements of type `A` into elements of type `B`.
+   */
+  final def aggregateManaged[R1 <: R, E1 >: E, O1 >: O, P](
```
Comment (iravid) [inline streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:95]: I think we can just do the `aggregate` variant - a transducer already has a `ZManaged` built into it.

File: streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala [hunk 2]
```diff
@@ -87,40 +87,28 @@ abstract class ZStream[-R, +E, +O](
...
+        pull <- self.process
+        push <- sink.push
+        done <- ZRef.makeManaged(false)
+        run = {
+          def go: ZIO[R1, Option[E1], Chunk[P]] = done.get.flatMap {
+            if (_)
+              push(None)
+            else
+              pull
+                .foldM(
```
Comment (iravid) [inline streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:101]: Maybe just `foldCauseM(Cause.sequenceCauseOption(...), ...)` here instead of `foldM.catchAllCause`?

Comment (regiskuckaertz) [reply streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:101]: Hmm, I don't think you can remove the `catchAllCause` as it is necessary to handle the "next" signal from the transducer and pull again, right? I switched to `foldM` to avoid the redundancy in case of a defect.

File: streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala [hunk 3]
```diff
@@ -82,6 +82,34 @@ abstract class ZStream[-R, +E, +O](
...
+  def aggregate[R1 <: R, E1 >: E, O1 >: O, P](sink: ZTransducer[R1, E1, O1, P]): ZStream[R1, E1, P] =
+    ZStream {
+      for {
+        pull <- self.process
+        push <- sink.push
+        done <- ZRef.makeManaged(false)
+        run = {
+          def go: ZIO[R1, Option[E1], Chunk[P]] = done.get.flatMap {
+            if (_)
+              push(None)
```
Comment (regiskuckaertz) [inline streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:98]: I'm still not convinced this is correct because in the transducer failing with `None` means give me more, whereas failing with `None` in the stream means this is the end.

Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:98]: Oh wait I think I am confused. Transducer failing with `None` should mean `end`, not give me more. A transducer can just send an empty Chunk if it doesn't have anything to send.

File: streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala (hunk 2 above)
Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:101]: Right! Good point. It does look like you can replace `catchAllCause` with `catchAll` though, because you're just forwarding the cause with `Pull.halt` on the non-typed-failure case.

File: streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala (hunk 3 above)
Comment (regiskuckaertz) [reply streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:98]: Ha. Ok so that changes everything 😆 give me a sec.

File: streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala [hunk 4]
```diff
@@ -82,6 +82,37 @@ abstract class ZStream[-R, +E, +O](
...
+  def aggregate[R1 <: R, E1 >: E, O1 >: O, P](sink: ZTransducer[R1, E1, O1, P]): ZStream[R1, E1, P] =
+    ZStream {
+      for {
+        pull <- self.process
+        push <- sink.push
+        done <- ZRef.makeManaged(false)
+        run = {
+          def go: ZIO[R1, Option[E1], Chunk[P]] = done.get.flatMap {
+            if (_)
+              push(None).repeat(Schedule.doWhile(_.isEmpty))
```
Comment (regiskuckaertz) [inline streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:98]: What do you think of this @iravid ?

File: streams-tests/shared/src/test/scala/zio/stream/experimental/ZStreamSpec.scala [hunk 5]
```diff
@@ -44,6 +44,68 @@ object ZStreamSpec extends ZIOBaseSpec {
           } yield assert(res1)(fails(equalTo(s))) && assert(res2)(fails(equalTo(s)))
         })
       ),
+      suite("aggregate")(
+        testM("aggregate") {
+          val s      = ZStream('1', '2', ',', '3', '4')
+          val parser = ZTransducer.collectAllWhile[Char](_.isDigit).map(_.mkString.toInt)
```
Comment (regiskuckaertz) [inline streams-tests/shared/src/test/scala/zio/stream/experimental/ZStreamSpec.scala:50]: The current version of the transducer for this test is:
```
val parser = ZSink.collectAllWhile[Char](_.isDigit).map(_.mkString.toInt) <* ZSink
          .collectAllWhile[Char](_ == ',')
```
Nice simplification. (Also, ZTransducers may not form monads after all)

**Comment by simpadjo** [comment]
`Stream#aggregate` used to be implemented as a special case of `aggregateManaged`. 
Will `aggregateManaged` exist or managed transducers make no sense?

**Comment by regiskuckaertz** [comment]
@simpadjo transducers are manager resources so it would be redundant

File: streams/shared/src/main/scala/zio/stream/experimental/ZTransducer.scala [hunk 6]
```diff
@@ -62,22 +65,55 @@ object ZTransducer {
...
     }
 
+  def collectAllWhile[I](p: I => Boolean): ZTransducer[Any, Nothing, I, List[I]] =
+    ZTransducer {
+      for {
+        buffered <- ZRef.makeManaged[Chunk[I]](Chunk.empty)
+        push = { (in: Option[Chunk[I]]) =>
+          buffered.modify { buf0 =>
+            val buf = in.foldLeft(buf0)(_ ++ _)
+            if (buf.isEmpty)
```
Comment (iravid) [inline streams/shared/src/main/scala/zio/stream/experimental/ZTransducer.scala:94]: This doesn’t look right - shouldn’t we check if `in` was originally `None`?

File: streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala (hunk 4 above)
Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:98]: It’s fine. A direct loop would be more performant but this should probably be an uncommon code path.

**Review by iravid — COMMENTED** [review]
Looks good! One small comment about collectAllWhile.

@simpadjo could you check your transducer tests with the identity sink against the implementation here?

**Comment by simpadjo** [comment]
@iravid The second test from https://github.com/zio/zio/issues/3290 is passing now, cool.
The first is still red but I guess it's a separate issue with `toTransducer`.

**Comment by iravid** [comment]
Awesome!

File: streams/shared/src/main/scala/zio/stream/experimental/ZTransducer.scala (hunk 6 above)
Comment (regiskuckaertz) [reply streams/shared/src/main/scala/zio/stream/experimental/ZTransducer.scala:94]: if it is then `buf == buf0` and if it isn't empty then my guess is we still have to go through the remainder. Is that correct?

Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/experimental/ZTransducer.scala:94]: Yes, that sounds right. Except that if it is `None`, we want to flush the remainder anyway (even if we haven't seen an `I` that satisfies `p`).

File: streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala [hunk 7]
```diff
@@ -82,6 +82,37 @@ abstract class ZStream[-R, +E, +O](
...
+            else
+              pull
+                .foldM(
+                  _.fold(done.set(true) *> push(None))(Pull.fail(_)),
+                  os => push(Some(os))
+                )
+                .foldCauseM(
+                  Cause.sequenceCauseOption(_).fold(go)(Pull.halt(_)),
```
Comment (iravid) [inline streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:106]: The `fold(go)` here looks suspicious, because we can get here both from `push(Some(os))` and from `push(None)`.

- From `push(Some(os))` - this looks like a protocol violation, right? Do we allow transducers to end on their own accord? I'm not clear on this 🧐
- From `push(None)` - this will recurse again if the transducer ended in response to the stream ending. Ah, it'll end on the next iteration because of `done set true`. Ok, I'd prefer to `ZIO.fail(None)` directly here but not critical 👍 

So let's just clarify the first point. What do you think?

File: core/shared/src/main/scala/zio/Chunk.scala [hunk 8]
```diff
@@ -652,6 +652,35 @@ sealed trait Chunk[+A] { self =>
     )
   }
 
+  /**
+   * Effectfully maps the elements of this chunk.
+   */
+  final def mapManaged[R, E, B](f: A => ZManaged[R, E, B]): ZManaged[R, E, Chunk[B]] = {
```
Comment (iravid) [inline core/shared/src/main/scala/zio/Chunk.scala:658]: Do we need this one? It's not used in this PR.

Comment (iravid) [reply core/shared/src/main/scala/zio/Chunk.scala:658]: Oh sorry I see the forwarder added in `ZManaged`.

File: streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala (hunk 7 above)
Comment (regiskuckaertz) [reply streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:106]: I think this also happens with sinks, the way they signal end is by failing which, thanks to ZIO being well-typed, you have to account for everywhere. That's another instance of what we were trying to fix with `SignalFunction`. Not sure there is a solution other than writing laws and throwing all the transducers at them.

Comment (regiskuckaertz) [reply streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:106]: I could refactor so that we die in case of a protocol error, but somehow that feels imperative. Note that having two different paths for the `None` and `Some` cases won't change the fact that the transducer may fail.

Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:106]: So I was thinking about this for a bit and perhaps it’s useful to allow transducers to signal end? E.g. that allows to create transducers that can short-circuit a stream when a predicate is violated.

Comment (regiskuckaertz) [reply streams/shared/src/main/scala/zio/stream/experimental/ZStream.scala:106]: Can you give an example? With `collectAllWhile`, I took the position that the transducer would just drop all elements violating the predicate, but still keep on accepting the rest of the stream. Is there another class of transducers where that wouldn't be possible?

**Review by iravid — APPROVED** [review]
Let’s get this in and refine the ZTransducer contract more later. Great work!
