### PR TITLE
zio-test: Don't overwrite inner node labels

### LINKED ISSUE #9227: ZIO Test Should Report a Failed Test With the Most Accurate Label
If I have a test like this: 

```scala
object LabelingAssertions extends ZIOSpecDefault {
  def spec =
    test("when an inner assertion fails") {
      assert(Some(0)) {
        isSome(
          equalTo(42).label("equality check")
        ).label("structural check")
      }.label("assertion label")
    }
}
```
It reports like this:
image

In the above test, when the "equalTo" assertion fails, I expect its corresponding label, the "equality check" will appear on the test report, not the outer label "assertion label"

### PR DESCRIPTION
**Pull request by joroKr21**
Fix #9227
/claim #9227

### CODE REVIEW

File: test-tests/shared/src/test/scala/zio/test/ReportingTestUtils.scala [hunk 1]
```diff
@@ -143,18 +143,30 @@ object ReportingTestUtils {
...
+      assert(b)(isSome(equalTo(1).label("eqB")).label("someB")).label("lblB") &&
+      assert(c)(isSome(equalTo(1).label("eqC")).label("someC")).label("lblC") &&
+      assert(d)(isSome(equalTo(1))).label("lblD")
   }
   def test7Expected(implicit sourceLocation: SourceLocation): Vector[String] = Vector(
     expectedFailureStreaming("labeled failures"),
-    s"0 was not equal to 1",
-    s"""${blue("c")} did not satisfy isSome(equalTo(1)).label("third")""",
+    """  ✗ Option was None
+      |  someB
```
Comment (kyri-petrou) [inline test-tests/shared/src/test/scala/zio/test/ReportingTestUtils.scala:157]: Shouldn't this be `eqB` instead?

Comment (joroKr21) [reply test-tests/shared/src/test/scala/zio/test/ReportingTestUtils.scala:157]: `eqB` wasn't executed, because `someB` already failed (the outer one)

Comment (kyri-petrou) [reply test-tests/shared/src/test/scala/zio/test/ReportingTestUtils.scala:157]: Aghh got it

**Review by kyri-petrou — APPROVED** [review]
