### PR TITLE
Fix `Queue#take` dropping items on interruption

### LINKED ISSUE #9973: Race condition when interrupting `Queue#take` can cause items to disappear
> A possibly more reliable repro:
> 
> ```scala
> final object ReproZio extends zio.ZIOAppDefault {
> 
>   import java.util.concurrent.atomic.AtomicReference
>   import zio._
> 
>   override def run = ZIO.unit.flatMap { _ =>
>     val t = for {
>       q <- Queue.unbounded[String]
>       ref <- ZIO.attempt { new AtomicReference[String] }
>       fib <- ZIO.uninterruptibleMask { restore =>
>         restore(q.take).flatMap { item =>
>           ZIO.attempt { ref.set(item) }
>         }
>       }.forkDaemon
>       _ <- ZIO.sleep(Duration.fromMillis(10L))
>       _ <- fib.interrupt zipPar q.offer("foo")
>       _ <- fib.await
>       s <- ZIO.attempt(ref.get())
>       _ <- if (s eq null) {
>         // take was cancelled, item should be in q
>         q.take.flatMap { item =>
>           if (item != "foo") ZIO.die(new AssertionError("incorrect item: " + item))
>           else ZIO.unit
>         }
>       } else {
>         // take was completed, q should be empty
>         q.isEmpty.flatMap { empty =>
>           if (!empty) ZIO.die(new AssertionError("nonempty q after completed take"))
>           else ZIO.unit
>         }
>       }
>       _ <- ZIO.attempt(println("ok"))
>     } yield ()
>     t.repeatN(99)
>   }
> }
> ```
> 
> This hangs for me with 2.1.19. So yes, it still seems to happen. 

 _Originally posted by @durban in [#4269](https://github.com/zio/zio/issues/4269#issuecomment-2972613161)_

### LINKED ISSUE #9974: Interruption "gap" at the end of `uninterruptibleMask`/`restore` and/or `asyncMaybe`/`asyncInterrupt`
### Short summary

There seems to be a "gap" (i.e., an opportunity for interruption) at the end of `restore` inside `uninterruptibleMask`. That is, a fiber can be interrupted at the place marked `HERE` in this code:

```scala
ZIO.uninterruptibleMask { restore =>
  restore(something /* HERE */).flatMap { i =>
    whatever
  }
}
```

even if `something` iself is uninterruptibe, i.e., something like this:

```scala
val something = ZIO.uninterruptibleMask { _ =>
  ...
}
```

This "gap" has real-world consequences for generic code (i.e., something which uses `F[_] : cats.effect.kernel.Async`), _but_ I think also for code which uses ZIO directly (and that's why I'm opening this issue here, and not in the [interop-cats](https://github.com/zio/interop-cats) repo).

### In Cats Effect

Cats Effect is explicitly documented to _not_ allow (the equivalent of) this. There is even a "law" called `onCancelAssociatesOverUncancelableBoundary`, which is (more or less) about this. There is already a discussion about it in zio/interop-cats/issues/617 and the related PR zio/interop-cats/pull/616. (Although that discussion is more about finalizers, I'm not sure why.) There, it is decided, that this is probably not that important. I think it is.

For reference, the Cats Effect issue about this: typelevel/cats-effect/issues/1744; and the PR: typelevel/cats-effect/pull/1800. These probably have everything I'm saying here (and more), but I'm trying to "summarize" here. (Also, I'm trying to talk about ZIO-only code too, here.)

### Consequences for generic code

The reason Cats Effect disallows cancellation at that specific place (i.e., `uncancelable { poll => ... poll(... /*HERE*/) ... }`) is to enable some very specific patterns to avoid "leaks". The pattern I'm most familiar with is that of `cats.effect.kernel.Async#asyncCheckAttempt`, so that's the one I'll talk about here. For reference, the default implementation of `asyncCheckAttempt` is [here](https://github.com/typelevel/cats-effect/blob/v3.6.1/kernel/shared/src/main/scala/cats/effect/kernel/Async.scala#L89-L104). The point of `asyncCheckAttempt` to do the following _without_ problems with cancellation:

- Check if some condition is true.
- If yes, complete without async suspension.
- If not, suspend until some notification (that the condition became true). Typically suspending in this way would need to have a finalizer.

As you can see, that default implementation uses `uncancelable` in a way, which makes the whole `asyncCheckAttempt` uncancelable in the case when the condition is true (the `case Right(a) => G.pure(a)`).

_But:_ that in itself is _not_ enough, without forbidding cancellation at the above mentioned place. Because a specific pattern of using it is like this:

```scala
uncancelable { poll =>
  poll(somethingWhichIsImplementedWithAsyncCheckAttempt /* HERE */).flatMap { i =>
    ...
  }
}
```

If that code can be cancelled at the place marked `HERE`, then we have a problem. To see why, let's take a look at creating an asynchronous queue from a synchronous one (i.e., we want to suspend the fiber in `take` if the queue is empty). We might do something like this:

```scala
def take: F[A] = {
  F.asyncCheckAttempt { cb =>
    F.delay {
      val a = syncQueue.poll()
      if (a ne null) { // ok, we're done
        Right(a)
      } else { // empty queue, need to suspend
        ... // register callback
        Left(Some(someFinalizer))
      }
    }
  }
}
```

And the code using the queue would call `take` like this:

```scala
uncancelable { poll =>
  poll(q.take /* HERE */).flatMap { item =>
    ... // do something with the item
  }
}
```

If it gets cancelled at `HERE`, then we have a problem, because (1) the item was removed form the queue, and (2) the code receiving the item was cancelled before it could handle it (even though it used `uncancelable` exactly because it wanted to avoid this). (Note, that it needs to call `poll`, because `take` might suspend, in which case it wants to be cancellable.)

If `uncancelable` works like it is documented, then the default implementation of `asyncCheckAttempt` is correct, and a queue implemented like this won't lose items. If it's not (like in zio/interop-cats), then such a generic queue can lose items.

To see this is not theoretical, `cats.effect.std.Queue` is a generic asynchronous queue implementation, which works for any `F[_] : cats.effect.kernel.Async`. And if the `Async` instance works like it should (i.e., it doesn't allow interruption `HERE`), then it can't lose items (to the best of my knowledge). But, based on all of the above, instantiating `F` with `zio.Task` (using the `Async` instance in zio/interop-cats), would have a problem with cancellation. And indeed: it can lose items. (Please note, that #9973 is an unrelated issue, that's about the queue in ZIO.)

### Consequences for code using ZIO directly

(I'm reasonably confident about what I've wrote so far. Now comes the ZIO-only part, which I'm much less familiar with, so it's entirely possible that I'm missing something.)

Based on the lot of text above, one might think fixing `asyncCheckAttempt` in zio/interop-cats would be enough. In fact, ZIO seems to have someting built-in, which is similar to `asyncCheckAttempt`: `ZIO.asyncMaybe` and `ZIO.asyncInterrupt`. These can also return an "immediate" result (i.e., one without async suspension).

But `asyncMaybe` and `asyncInterrupt` seems to have the _same_ problem: even when returning an immediate result, there is no guarantee that code using them receives it (e.g., receives an item from a queue). The pattern is basically this:

```scala
ZIO.uninterruptibleMask { restore =>
  restore(somethingImplementedWithAsyncMaybe /*HERE*/).flatMap { item =>
    ... // do something with `item`
  }
}
```

This is a full, but (almost) minimal reproduction:

```scala
object FooooInlinedImmediateZio extends zio.ZIOAppDefault {

  import java.util.concurrent.atomic.{ AtomicReference, AtomicBoolean }
  import zio.{ Task, ZIO }

  override def run = {
    task.repeatN(9999)
  }

  def task: Task[Unit] = {
    for {
      ref <- ZIO.attempt(new AtomicReference[Int](42))
      bodyWasCalledRef <- ZIO.attempt(new AtomicBoolean(false))
      holder <- ZIO.attempt(new AtomicReference[Int](0))
      getAndSave = ZIO.uninterruptibleMask { restore =>
        restore(innerTask(ref, bodyWasCalledRef) /*HERE*/).flatMap { i =>
          ZIO.attempt(holder.set(i))
        }
      }
      fib <- getAndSave.forkDaemon
      _ <- fib.interrupt
      _ <- fib.await
      bodyWasCalled <- ZIO.attempt(bodyWasCalledRef.get())
      holderContents <- ZIO.attempt(holder.get())
      _ <- if (bodyWasCalled) {
        ZIO.attempt {
          assert(holderContents == 42, s"unexpected contents: ${holderContents}") // this fails sometimes
        }
      } else {
        ZIO.unit
      }
      _ <- ZIO.attempt(java.lang.System.err.println("ok"))
    } yield ()
  }

  def innerTask(ref: AtomicReference[Int], bodyWasCalled: AtomicBoolean): Task[Int] = {
    ZIO.asyncMaybe { _ =>
      bodyWasCalled.set(true)
      val v = ref.get()
      val result = if (v != 0) v else 9999
      Some(ZIO.succeed(result))
    }
  }
}
```

### PR DESCRIPTION
**Pull request by kyri-petrou**
/fixes #9973
/fixes #9974
/claim #9973

This PR fixes two issues, which both contribute to `Queue#take` dropping items:
1. There is an interruption gap between uninterruptible regions (see changes under `FiberRuntime`)
2. `Queue#take` did not take into account that it had to return items to the queue in case that the promise was already fulfilled (with interruption)

Note that:
- Changes in the `FiberRuntime` file fix https://github.com/zio/zio/issues/9974
- Changes in the `Queue` file fix https://github.com/zio/zio/issues/9973

Leaving as draft cause I want to go over the queue code once more with a fresh mind, and to see if CI agrees with my changes 

Full disclaimer: While the solution seems rather simple, this was one of the hardest issues I ever worked on. Figuring out the changes needed to be done in FiberRuntime in a way that didn't break existing functionality took an enormous amount of time

### CODE REVIEW

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala [hunk 1]
```diff
@@ -1425,7 +1425,57 @@ final class FiberRuntime[E, A](fiberId: FiberId.Runtime, fiberRefs0: FiberRefs,
...
+          }
+        case _ => ()
+      }
+    }
+    result
+  }
+
+  @deprecated("This method will be removed in a future release.", "2.1.21")
+  private[zio] def shouldInterrupt(): Boolean =
+    isInterruptible() && isInterrupted()
```
Comment (hearnadam) [inline core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: Can this just be `def shouldInterrupt() = shouldInterrupt(true)` for simplicity?

File: core/shared/src/main/scala/zio/Queue.scala [hunk 2]
```diff
@@ -161,40 +161,36 @@ object Queue extends QueuePlatformSpecific {
     strategy: Strategy[A]
   ) extends Queue[A] {
 
-    private def removeTaker(taker: Promise[Nothing, A])(implicit trace: Trace): UIO[Unit] =
-      ZIO.succeed(takers.remove(taker))
+    private val interruptAsNone = ZIO.interruptAs(FiberId.None)(Trace.empty)
```
Comment (hearnadam) [inline core/shared/src/main/scala/zio/Queue.scala]: Does this belong in the object instead of the class itself?

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala [hunk 3]
```diff
@@ -27,6 +27,24 @@ import java.util.concurrent.atomic.AtomicBoolean
 import java.util.{Set => JavaSet}
 import scala.annotation.tailrec
 
+object Foo extends ZIOAppDefault {
```
Comment (hearnadam) [inline core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: might want to remove 🙂

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala [hunk 4]
```diff
@@ -1020,6 +1038,44 @@ final class FiberRuntime[E, A](fiberId: FiberId.Runtime, fiberRefs0: FiberRefs,
...
+   * '''IMPORTANT''': This check can only be used where we unwind the stack
+   *
+   * @see
+   *   https://github.com/zio/zio/issues/9974
+   * @see
+   *   https://github.com/zio/zio/issues/9973
+   */
+  private[this] def ignoreFlagsUpdate(update: RuntimeFlags.Patch, stackIndex: Int) = {
+    def isInterruptionDisabledInNextFrame(stackIndex: Int) =
+      _stack(stackIndex - 1) match {
```
Comment (hearnadam) [inline core/shared/src/main/scala/zio/internal/FiberRuntime.scala:1050]: I don't think we need a bounds check, but would abuse bite us later? Maybe an assertion we elide at runtime?

File: core/shared/src/main/scala/zio/Queue.scala [hunk 5]
```diff
@@ -248,26 +244,35 @@ object Queue extends QueuePlatformSpecific {
...
-              Exit.succeed(item)
+                restore(p.await).catchAllCause { c =>
+                  val removed = p.unsafe.completeWith(interruptAsNone)(Unsafe)
+                  takers.remove(p)
+                  if (removed) Exit.failCause(c)
+                  else {
+                    // The promise was already completed, so if we interrupt here we'll drop the item
+                    // This is not ideal but instead of interrupting we recover temporarily.
+                    // Interruption will resume at the next point where it's enabled
+                    p.await
```
Comment (hearnadam) [inline core/shared/src/main/scala/zio/Queue.scala:269]: very clever

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala (hunk 1 above)
Comment (hearnadam) [reply core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: You can ignore this, left before the recent set of changes.

File: core/shared/src/main/scala/zio/Queue.scala (hunk 2 above)
Comment (kyri-petrou) [reply core/shared/src/main/scala/zio/Queue.scala]: Oops, yes missed this 👍

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala (hunk 3 above)
Comment (kyri-petrou) [reply core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: Knew I forgot to delete some debugging code 😆

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala (hunk 4 above)
Comment (kyri-petrou) [reply core/shared/src/main/scala/zio/internal/FiberRuntime.scala:1050]: There is already a lower bound check (`size > 0`) as the stack might be empty. But having an upper bound check isn't really useful as we'll get an exception anyways.

Having said that, I'll add an elided assertion that the `stackIndex` argument is the same as heap `_stackSize` variable just to make sure we're passing the right value (since we utilize a local variable instead of the heap one for performance)

**Review by hearnadam — APPROVED** [review]

File: core/shared/src/main/scala/zio/Queue.scala [hunk 6]
```diff
@@ -248,26 +244,35 @@ object Queue extends QueuePlatformSpecific {
...
-              // add the promise to takers, then:
-              // - try take again in case a value was added since
-              // - wait for the promise to be completed
-              // - clean up resources in case of interruption
-              val p = Promise.unsafe.make[Nothing, A](fiberId)(Unsafe.unsafe)
-
-              ZIO.suspendSucceed {
+      ZIO.uninterruptibleMask { restore =>
+        ZIO.fiberIdWith { fiberId =>
+          if (shutdownFlag.get) ZIO.interrupt
```
Comment (guizmaii) [inline core/shared/src/main/scala/zio/Queue.scala:249]: What does `ZIO.interrupt` do when wrapped in a `ZIO.uninterruptibleMask`? 🤔 
Do we need to `restore` it?

Comment (kyri-petrou) [reply core/shared/src/main/scala/zio/Queue.scala:249]: `ZIO.interrupt` is simply a specialized `Die`. Self interruption pretty much works as an error that works the same way as defects. You can think of it as (more or less) the equivalent of doing this: 

```scala
ZIO.die(new InterruptedException())
```

You can test it using this code:

```scala
import zio.*

object Foo extends ZIOAppDefault {
  def run = ZIO.uninterruptible(ZIO.interrupt)
}
```
