### PR TITLE
Require At Least One Assertion

### LINKED ISSUE #8190: Replace all unsafe usage of `reduce`
I can't get to creating a PR right now but this is an easy one that anyone can pick up quickly if they have time. Basically `reduce` on an empty `Seq` will result in a `java.lang.UnsupportedOperationException: empty.reduceLeft`. There's a few usages of this in the zio codebase. Most of them are in specs so replacing those probably aren't crucial but there's examples of it in actual non-test code too. For example we ran into this one which caused an exception:
https://github.com/zio/zio/blob/521b6fd548073f5343f9c71aa92568b056a55d5a/test/shared/src/main/scala/zio/test/TestArrow.scala#L46-L48

The fix is to use `fold`, `reduceOption`, or use a non-empty list where appropriate.

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #8190.

### CODE REVIEW

File: test/shared/src/main/scala/zio/test/TestArrow.scala [hunk 1]
```diff
@@ -43,9 +43,9 @@ case class TestResult(arrow: TestArrow[Any, Boolean]) { self =>
 }
 
 object TestResult {
-  def all(asserts: TestResult*): TestResult = asserts.reduce(_ && _)
+  def all(assert: TestResult, asserts: TestResult*): TestResult = asserts.foldLeft(assert)(_ && _)
 
-  def any(asserts: TestResult*): TestResult = asserts.reduce(_ || _)
+  def any(assert: TestResult, asserts: TestResult*): TestResult = asserts.foldLeft(assert)(_ || _)
```
Comment (jdegoes) [inline test/shared/src/main/scala/zio/test/TestArrow.scala:48]: This would break binary backward compatibility, right? (Although I agree it's the correct API.)

Comment (jdegoes) [reply test/shared/src/main/scala/zio/test/TestArrow.scala:48]: Maybe you could make the original one `private`, and just add the new one.

Comment (adamgfraser) [reply test/shared/src/main/scala/zio/test/TestArrow.scala:48]: Done now!

**Review by vigoo — APPROVED** [review]
