### PR TITLE
Fix awaiting application finalizers to run on external interruption

### LINKED ISSUE #9901: ZIO 2.1.18 does not wait on termination of registered finalizers
The following code highlights the problem.

Create `ZioShutdownApp.scala`  and execute with `scala run ZioShutdownApp.scala`

```scala
//> using dep dev.zio::zio:2.1.17
//> using scala 3.7.0

import zio.*

object ZioShutdownApp extends zio.ZIOAppDefault:

  private class Service:
    val close: UIO[Unit] =
      ZIO.debug("Service is closing") *>
        ZIO.sleep(3.seconds) *>
        ZIO.debug("Service is closed")

  override def run: ZIO[ZIOAppArgs & Scope, Any, Any] =
    for
      _ <- ZIO.attempt(new Service).withFinalizer(_.close)
      _ <- ZIO.debug("Service is running. Hit Ctrl-C to shutdown")
      _ <- ZIO.never
    yield ()
```
Terminate the process by hitting `Ctrl+C`, and the following output is produced

> Service is running. Hit Ctrl-C to shutdown
> Service is closing
> Service is closed

After updating to `2.1.18` and running the same code, the finalization output is missing

> Service is running. Hit Ctrl-C to shutdown

The problem seems to be related to method `zio.Runtime.Scoped#shutdown0` to return immediately in `2.1.18` while it is "blocking" in `2.1.17`.

### PR DESCRIPTION
**Pull request by kyri-petrou**
/fixes #9901

It seems that https://github.com/zio/zio/pull/9827 introduced a bug where finalizers might not run in applications that are exited externally. I'll create a release straight after this PR is merged because this can be a relatively severe bug. This should revert the behaviour to what was in 2.1.17 but without the bug that was fixed (https://github.com/zio/zio/issues/9807)

One other thing is that this PR adds the `gracefulShutdownTimeout` method on `ZIOApp`. This way users can configure how much time the runtime will wait before exiting after an external interruption signal is received. This is partially to mitigate issues where the app might hang on termination (e.g., https://github.com/zio/zio/issues/5185) or because of uninterruptible finalizers that never complete. I set the default value to `Duration.Infinity` in order to avoid breaking applications and to match the behaviour pre-2.1.17.

I'll followup with:
1. Creating an issue to add tests for ensuring correct behaviour of `ZIOApp`
2. Documenting `gracefulShutdownTimeout`

### CODE REVIEW

File: core/jvm-native/src/main/scala/zio/ZIOAppPlatformSpecific.scala [hunk 1]
```diff
@@ -23,42 +23,62 @@ private[zio] trait ZIOAppPlatformSpecific { self: ZIOApp =>
...
               }
-            })
-          result <- fiber.join
-          _      <- exit(result)
-        } yield ()
+            } catch {
+              case _: OneShot.TimeoutException =>
+                println(
+                  "**** WARNING ****\n" +
+                    s"Timed out waiting for ZIO application to shut down after $gracefulShutdownTimeout. " +
```
Comment (hearnadam) [inline core/jvm-native/src/main/scala/zio/ZIOAppPlatformSpecific.scala]: minor: I would use a multi-line string + `.render` to make the output human readable.
```suggestion
                    s"Timed out waiting for ZIO application to shut down after ${gracefulShutdownTimeout.render}. " +
```

**Review by hearnadam — DISMISSED** [review]

File: core/jvm-native/src/main/scala/zio/internal/OneShot.scala [hunk 2]
```diff
@@ -106,4 +106,6 @@ private[zio] object OneShot {
    * Makes a new (unset) variable.
    */
   def make[A]: OneShot[A] = new OneShot()
+
+  final class TimeoutException extends Error("Timed out waiting for variable to be set")
```
Comment (hearnadam) [inline core/jvm-native/src/main/scala/zio/internal/OneShot.scala:110]: Just noting that the JS version does not have this same exception now.

**Review by hearnadam — APPROVED** [review]

File: core/jvm-native/src/main/scala/zio/internal/OneShot.scala (hunk 2 above)
Comment (kyri-petrou) [reply core/jvm-native/src/main/scala/zio/internal/OneShot.scala:110]: The JS version doesn't have a timeout so I guess that's fine?
