### PR TITLE
Fix #2261 race interruption inside `daemon`

### LINKED ISSUE #2261: `race` interruption doesn't work inside `daemon` region
https://github.com/zio/interop-cats/pull/112#issuecomment-554846476

Since interruption of child fibers on interruption of this fiber in `race` now depends on supervision, in regions where it's off `race` stops working correctly

### PR DESCRIPTION
**Pull request by Twizty**
Implemented #2261.

### CODE REVIEW

**Comment by Twizty** [comment]
@neko-kai @ghostdogpr please review. Some tests are flaky, I'll fix it, but I guess the core functionality is implemented.

**Comment by neko-kai** [comment]
@Twizty Looks fine. I guess you should use Promises instead of sleeps here

**Comment by Twizty** [comment]
@neko-kai sure, I'll fix it.

**Comment by Twizty** [comment]
@neko-kai done.

**Comment by ghostdogpr** [comment]
@Twizty your first test doesn’t enable the daemon mode so it’s not actually testing that it works. Also as @neko-kai said, you can get rid of all the sleeps and `flaky` by using latches. I posted the test that shows the problem here: https://github.com/zio/zio/issues/2261#issuecomment-557383549 , maybe you re-use it?

**Comment by Twizty** [comment]
@ghostdogpr @neko-kai done.

File: core-tests/shared/src/test/scala/zio/ZIOSpec.scala [hunk 1]
```diff
@@ -1451,6 +1451,144 @@ object ZIOSpec extends ZIOBaseSpec {
           fibs <- ZIO.children
         } yield assert(fibs, isEmpty)
       },
+      testM("daemon fiber race interruption") {
+        def plus1(ref: Ref[Int], latch: Promise[Nothing, Unit]) =
+          latch.succeed(()) *> clock.sleep(200.milliseconds) *> ref.update(_ + 1)
```
Comment (ghostdogpr) [inline core-tests/shared/src/test/scala/zio/ZIOSpec.scala]: The sleep could cause flakiness here. Actually you don't really need this `ref`, you could simply do `latch.succeed(()) *> ZIO.never` so that it wouldn't finish.

**Comment by Twizty** [comment]
Thank you!
