### PR TITLE
Make Lock Heritable

### LINKED ISSUE #2859: effectBlockingInterrupt does not shift into the blocking pool
While `blocking.blocking` properly shifts the effect into the Blocking pool, `effectBlockingInterrupt` does not.

Wrapping the effect returned by `effectBlockingInterrupt` into `blocking` does not resolve the issue.

I can also reproduce on RC17 with `effectBlocking` (which AFAICT was only renamed in master).

I’ve pushed a branch to reproduce it [here](https://github.com/fsvehla/zio/tree/fsvehla/effect-blocking-investigation)

Here is the minimal failing ZIO test:

```scala
testM("effectBlockingInterrupt shifts into a blocking pool") {
  val threadName = effectBlockingInterrupt(Thread.currentThread.getName())

  assertM(threadName)(containsString("blocking"))
}
```

### PR DESCRIPTION
**Pull request by adamgfraser**
Fixes a bug in `FiberContext` where when a fiber was forked it was forked on the platform's default executor instead of the current active executor. We had a test for this but the test was based on the  fiber's descriptor which said it was running on a certain executor even though it wasn't actually running there.

Resolves #2859.

### CODE REVIEW

File: core-tests/shared/src/test/scala/zio/ZIOSpec.scala [hunk 1]
```diff
@@ -2639,17 +2639,20 @@ object ZIOSpec extends ZIOBaseSpec {
...
-          } yield v.contains(exec)
-
-        assertM(io)(isTrue)
+        val threadName = ZIO.effectTotal(Thread.currentThread.getName)
+        val executor = internal.Executor.fromExecutionContext(100) {
+          scala.concurrent.ExecutionContext.Implicits.global
+        }
+        val poolName =
+          if (TestPlatform.isJS) "main"
+          else if (TestVersion.is211) "ForkJoinPool"
```
Comment (jdegoes) [inline core-tests/shared/src/test/scala/zio/ZIOSpec.scala]: Did you try using `Thread.currentThread.getThreadGroup`? May be less brittle than substring testing of the thread name.

Comment (adamgfraser) [reply core-tests/shared/src/test/scala/zio/ZIOSpec.scala]: Good idea. Used now.

**Comment by jdegoes** [comment]
💪

File: core-tests/shared/src/test/scala/zio/ZIOSpec.scala (hunk 1 above)
Comment (adamgfraser) [reply core-tests/shared/src/test/scala/zio/ZIOSpec.scala]: Actually `getThreadGroup` doesn't exist on ScalaJS so we need to revert to using the thread names.

**Comment by jdegoes** [comment]
How about adding `getCurrentThreadGroup` to `Platform` companion object? In Javascript, it can just return `""` or whatever? I'm just concerned even a small change in Scala std lib or Java could affect the stability of the test case.

**Comment by adamgfraser** [comment]
Okay.

**Comment by jdegoes** [comment]
@adamgfraser Thank you, looks great and very robust!
