### PR TITLE
Fix OOM issue in `ZPipeline#encodeStringWith`

### LINKED ISSUE #9935: `ZPipeline.encodeCharsWith` method from `zio-streams` causes memory leaks
Given a large file (10+ mb) as input, and streaming it over in various chunk sizes via a pipeline that includes `ZPipeline.encodeCharsWith` seems to cause memory leaks.

After exploring the code behind it and the way `CharsetEncoder` works, it seems to me like this might be the culprit here (although I still don't quite understand why):
https://github.com/zio/zio/blob/1241ddc16f21300b0a73e15e53307b484b8123a5/streams/shared/src/main/scala/zio/stream/ZPipeline.scala#L1228

I realize recursion is trampolined via flatmaps but the analysis I've done seems to indicate the recursive call is repeated until eventually an OOM exception is hit and then the thread hangs. 

memory profile

----

(If `CoderResult` is `OVERFLOW`, wouldn't the buffer need to be flushed first before attempting to call `encode` again? At least the documentation for `CharsetEncoder` seems to [say so](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/charset/CharsetEncoder.html).)

----

Yet, this only happens when the buffer size is small enough (ie. for ex. the default of 4096 bytes). Increasing buffer size seems to prevent this from happening. I am still not sure what is the causal relation there but perhaps a larger buffer prevents an overflow from ever happening in the encoder? Just a guess.

### PR DESCRIPTION
**Pull request by kyri-petrou**
/fixes #9935
/claim #9935

Main issue is that `charBuffer.flip()` was being called just once (see comment below), so in case that we couldn't drain the `charBuffer` in a single iteration, we were not flipping it in the next iteration causing an infinite loop (and eventually an OOM error).

I also took the opportunity to re-write this method using tail recursion instead of ZIO recursion which should be far more performant

### CODE REVIEW

File: streams/shared/src/main/scala/zio/stream/ZPipeline.scala [hunk 1]
```diff
@@ -1184,77 +1185,100 @@ object ZPipeline extends ZPipelinePlatformSpecificConstructors {
...
-      def flushRemaining: IO[CharacterCodingException, Chunk[Byte]] =
-        for {
-          result         <- ZIO.succeed(encoder.flush(byteBuffer))
-          encodedBytes   <- handleCoderResult(result)
-          remainderBytes <- if (result.isOverflow) flushRemaining else Exit.emptyChunk
-        } yield encodedBytes ++ remainderBytes
+      def endOfInput(): Chunk[Byte] = {
+        @tailrec
+        def loop(acc: Chunk[Byte] = Chunk.empty): Chunk[Byte] = {
+          charBuffer.flip()
```
Comment (kyri-petrou) [inline streams/shared/src/main/scala/zio/stream/ZPipeline.scala:1232]: This is the main fix. Everything else is optimizations

**Review by guizmaii — APPROVED** [review]
