### PR TITLE
Fix #9642 Compare operations of ops classes in assertTrue

### LINKED ISSUE #9642: assertTrue macro fails on a simple duration expression
**Scala**: 3.5.2
**JVM**:  openjdk 23 2024-09-17 (OpenJDK Runtime Environment Temurin-23+37 (build 23+37))

```scala
import zio.test.*
import zio.*
import java.time.temporal.ChronoUnit.*

object MarcoFailureTest extends ZIOSpecDefault {
  val spec = suite("Asset true macro")(
    test("should not fail on a simple duration expression") {
      val duration = Duration(500, MILLIS)
      
      assertTrue(duration < Duration(1, SECONDS))
    }
  )
} 
```

Fails to compile with:

```
Exception occurred while executing macro expansion.
java.lang.Error: NO
	at zio.test.SmartAssertMacros$.transform(Macros.scala:261)
	at zio.test.SmartAssertMacros$.smartAssertSingle_impl(Macros.scala:393)
	at zio.test.SmartAssertMacros$.smartAssert_impl(Macros.scala:405)
	at zio.test.SmartAssertMacros$.smartAssert(Macros.scala:32)

      assertTrue(duration < Duration(1, SECONDS))

```

### PR DESCRIPTION
**Pull request by artembakhanov**
Fix #9642

This PR fixes an issue in `assertTrue` macro that did not allow using compare operation (>, >=, <, <=) inside of it when they were extension methods.

The problem was that when the macro matched a tree with such an operation it always "tried" to summon an instance of `Ordering[l]` where `l` is the type of lhs. However, sometimes when having an ops class and implicit conversions to its instance does not mean that there is an `Ordering` instance for the type (actually I believe it's always the case). In other words, it is just an extension method that's why the macro would never work in Scala 3.

I have only changed the logic when `implicitConversionDirection` value is `Some(false)` (direction from the type on the rigth to the one on left) since all the comparison operators are left associative.

### CODE REVIEW

File: test/shared/src/main/scala-3/zio/test/Macros.scala [hunk 1]
```diff
@@ -263,6 +263,9 @@ object SmartAssertMacros {
                             .span($span)
                         }.asExprOf[TestArrow[Any, A]]
                     }
+                  case (None, _) =>
+                    val span = getSpan(tree)
+                    '{ TestArrow.succeed($expr).span($span) }
                   case _ => throw new Error("NO")
```
Comment (hearnadam) [inline test/shared/src/main/scala-3/zio/test/Macros.scala]:
```suggestion
                  case _ => throw new IllegalArgumentException("Unsupported operation in 'assertTrue'\nPlease open an issue: https://github.com/zio/zio/issues/new")
```

**Review by hearnadam — DISMISSED** [review]
Thank you so much 🙏

File: test/shared/src/main/scala-3/zio/test/Macros.scala (hunk 1 above)
Comment (artembakhanov) [reply test/shared/src/main/scala-3/zio/test/Macros.scala]: I just thought maybe it should not be the problem of the end user if they include some strange compare expressions? We can't really predict what kind of expressions are possible here, however, they might appear in the future, maybe we should simply allow all of them. And moreover it should not be the problem of this codebase to handle exception cases, such as what I wrote: `case (None, _) => ...` only for the specific conversion direction and only when a bug has been submitted.

What I mean is that instead of throwing this strange exception, which appears only in expressions with compare operations, simply do the `'{ TestArrow.succeed($expr).span($span) }` like it is already done when the tree does not match any other patterns (lines 383-385 in the original code)?

Comment (hearnadam) [reply test/shared/src/main/scala-3/zio/test/Macros.scala]: I am not sure I 100% understand, but I think you're saying the case you added should be a 'catchall'? Even if that's the case, I think it's better to leave a way to report bugs/issues and we can choose to fix/not fix them. `ERROR("NO")` is not descriptive.

Comment (kyri-petrou) [reply test/shared/src/main/scala-3/zio/test/Macros.scala]: Since this is used in a macro, why not throw a proper compiler error with the error message suggested by @hearnadam?

```suggestion
                  case _ => scala.compiletime.error("Unsupported operation in 'assertTrue'\nPlease open an issue: https://github.com/zio/zio/issues/new")
```

Or is that not possible?

Comment (artembakhanov) [reply test/shared/src/main/scala-3/zio/test/Macros.scala]: @kyri-petrou, yes it's possible, I have changed the error message to the one suggested by @hearnadam and used the compiler error like you suggested. The only thing I changed is moved this error expression to a separate `def`, since it is reused three times in places where "NO" exception was before.

**Review by hearnadam — APPROVED** [review]
