### PR TITLE
Make Diff contravariant on Scala 3 and use a union type for equality

### LINKED ISSUE #8754: zio-test: Comparing Chunk to Seq causes ClassCastException
Scala 3 (2.13 does not compile with `found Seq, require Chunk` error)
Both 2.0 and 2.1-RC

https://scastie.scala-lang.org/7CX9Y9D3QYq0v4TNcsIDmw

```scala
object Suite extends ZIOSpecDefault {
  override def spec = suite("suite") {
    test("test") {
     assertTrue(Chunk(1, 2, 3) == Seq(1, 2, 3, 4));
    }
  }
}
```

```
  - suite[2m / test
    ✗ ERROR: java.lang.ClassCastException: class scala.collection.immutable.$colon$colon cannot be cast to class zio.Chunk (scala.collection.immutable.$colon$colon is in unnamed module of loader sbt.internal.ScalaLibraryClassLoader @5ad07354; zio.Chunk is in unnamed module of loader sbt.internal.ReverseLookupClassLoader @3094bb)
      zio.test.diff.DiffInstances.mkSeqDiff$$anonfun$1(Diff.scala:113)
      zio.test.internal.SmartAssertions$.equalTo$$anonfun$1(SmartAssertions.scala:291)
    Chunk(1, 2, 3) == Seq(1, 2, 3, 4)
    [2m(1, 2, 3) = Chunk(1, 2, 3)
    [2mChunk = zio.Chunk$@3f018ce
    at /tmp/scastie5353637521019907974/src/main/scala/main.scala:10 
```

### PR DESCRIPTION
**Pull request by joroKr21**
fix #8754
/claim #8754

### CODE REVIEW

File: test/shared/src/main/scala-2/zio/test/SmartAssertMacros.scala [hunk 1]
```diff
@@ -257,13 +257,12 @@ $TestResult($ast.withCode($codeString).meta(location = $location))
...
 
   object UnwrapImplicit {
-    @nowarn("msg=never used")
-    def unapply(tree: c.Tree): Option[c.Tree] =
-      tree match {
-        case q"$wrapper($lhs)" if wrapper.symbol.isImplicit =>
-          Some(lhs)
-        case _ => Some(tree)
-      }
+    def unapply(tree: c.Tree): Option[c.Tree] = tree match {
```
Comment (hearnadam) [inline test/shared/src/main/scala-2/zio/test/SmartAssertMacros.scala]: I think it's best to avoid this in the same PR to enable simpler rollbacks/tracking.

File: test/shared/src/main/scala/zio/test/diff/Diff.scala [hunk 2]
```diff
@@ -8,7 +8,7 @@ import zio.{Chunk, NonEmptyChunk}
 import scala.collection.mutable.{ArrayBuffer, ListBuffer}
 import scala.util.Try
 
-trait Diff[A] { self =>
+trait Diff[-A] { self =>
```
Comment (hearnadam) [inline test/shared/src/main/scala/zio/test/diff/Diff.scala]: Can you think of any reason this is risky for consumers who might have a custom implementation?

Comment (joroKr21) [reply test/shared/src/main/scala/zio/test/diff/Diff.scala]: On Scala 3 it should be fine - maybe we should make it version specific? WDYT?

File: test/shared/src/main/scala-2/zio/test/SmartAssertMacros.scala (hunk 1 above)
Comment (joroKr21) [reply test/shared/src/main/scala-2/zio/test/SmartAssertMacros.scala]: What are you referring to?

Comment (hearnadam) [reply test/shared/src/main/scala-2/zio/test/SmartAssertMacros.scala]: Can you split the fix for implicit ordering to a separate PR?

Comment (joroKr21) [reply test/shared/src/main/scala-2/zio/test/SmartAssertMacros.scala]: Ah yeah sure

**Review by kyri-petrou — APPROVED** [review]
