### PR TITLE
Do Not Log Pure Interruptions

### LINKED ISSUE #2352: DefaultRuntime: Do not log pure interruptions
We should add a method on `Cause` to check to see if the cause is a "pure interruption". A pure interruption is a `Cause` formed solely through nodes that are neither `Die` nor `Fail` (although it may have any combination of `Both`, `Then`, `Trace`, `Meta`, and `Interrupt`).

A cause that is a pure interruption (even a complex one) should not, by default, be logged to standard error, in the `DefaultRuntime`.

Currently, while simple interruptions are not logged, more complex interruptions are logged.

`Cause` is defined in `Cause.scala` in `core`, and `DefaultRuntime` is defined in `DefaultRuntime.scala` in `core`.

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #2352.

### CODE REVIEW

File: core/shared/src/main/scala/zio/Cause.scala [hunk 1]
```diff
@@ -130,6 +130,16 @@ sealed trait Cause[+E] extends Product with Serializable { self =>
       case (_, Interrupt(_))    => false
     }
 
+  /**
+   * Determines if the `Cause` is a pure interruption, a `Cause` that does not
+   * contain any `Die` or `Fail` causes.
+   */
+  final def isPureInterruption: Boolean =
```
Comment (jdegoes) [inline core/shared/src/main/scala/zio/Cause.scala]: I might call this one, `justInterrupted` or even `interruptedOnly` for greater symmetry with `interrupted: Boolean`.

Otherwise, looks fantastic!

Comment (adamgfraser) [reply core/shared/src/main/scala/zio/Cause.scala]: Good idea. Updated now.

**Comment by jdegoes** [comment]
Superb. Thank you for this!
