### PR TITLE
fix deadlock on maxYieldOps less than 3

### LINKED ISSUE #1372: Runtime deadlocks on maxYieldOps less than 3
When `maxYieldOps` is less than 3, `FiberContext` dead locks. The reason is that when `maxopcount` is reached, `curZio` is set to a `FlatMap(Yield, _)`. Processing this structure already takes two cycles and so never completes. Moreover, resuming from a `Yield` requires processing a `Success(Unit)` before the actual next ZIO. If `maxYieldOps` is less than 2, this triggers the next `Yield`. 

Steps to reproduce:

```scala

val rts = new DefaultRuntime {
  override val Platform = PlatformLive.Default.withExecutor(PlatformLive.ExecutorUtil.makeDefault(1))
}

rts.unsafeRun(
  for {
   _ <- UIO.unit
   _ <- UIO.unit
  } yield true
)
```

### PR DESCRIPTION
**Pull request by runtologist**
Fixes #1372

This PR removes the indirection via `FlatMap` when `maxopcount` is reached. For resuming, a new tag is introduced, which is handled before entering the evaluation loop and does not contribute to `maxopcount`.

### CODE REVIEW

File: core/shared/src/main/scala/zio/internal/FiberContext.scala [hunk 1]
```diff
@@ -243,6 +243,7 @@ private[zio] final class FiberContext[E, A](
         var opcount: Int = 0
 
         while (curZio ne null) {
+          while (curZio.tag == ZIO.Tags.Resume) { curZio = nextInstr(()) }
```
Comment (dreverri) [inline core/shared/src/main/scala/zio/internal/FiberContext.scala]: It looks like `nextInstr` can return `null` which could cause `curZio.tag` to throw a `NullPointerException`?

File: core/shared/src/main/scala/zio/internal/FiberContext.scala [hunk 2]
```diff
@@ -252,10 +253,9 @@ private[zio] final class FiberContext[E, A](
               // Cannot capture `curZio` since it will be boxed into `ObjectRef`,
               // which destroys performance. So put `curZio` into a temp val:
               val tmpIo = curZio
-
-              curZio = ZIO.yieldNow *> tmpIo
-
-              opcount = 0
+              pushContinuation(_ => tmpIo)
+              evaluateLater(ZIO.Resume)
```
Comment (dreverri) [inline core/shared/src/main/scala/zio/internal/FiberContext.scala]: Could `tmpIo` be evaluated later instead of introducing a new tag?

File: core/shared/src/main/scala/zio/internal/FiberContext.scala (hunk 1 above)
Comment (runtologist) [reply core/shared/src/main/scala/zio/internal/FiberContext.scala]: I've added a guard condition.

File: core/shared/src/main/scala/zio/internal/FiberContext.scala (hunk 2 above)
Comment (runtologist) [reply core/shared/src/main/scala/zio/internal/FiberContext.scala]: The point is that we need to handle the parameter to `evaluateLater` before the while loop. I'd be happy about a solution without a special tag, but I couldn't think of one.

Comment (dreverri) [reply core/shared/src/main/scala/zio/internal/FiberContext.scala]: why does the parameter to `evaluateLater` need to be handled before the while loop?

Comment (runtologist) [reply core/shared/src/main/scala/zio/internal/FiberContext.scala]: Because we must not increase `maxopcount`. Otherwise we need to immediately yield again.

Comment (dreverri) [reply core/shared/src/main/scala/zio/internal/FiberContext.scala]: I was thinking of something like:

```
if (opcount == maxopcount) {
    // Cannot capture `curZio` since it will be boxed into `ObjectRef`,
    // which destroys performance. So put `curZio` into a temp val:
    val tmpIo = curZio
    evaluateLater(tmpIo)
    curZio = null
} else {
```

With `curZio` set to `null` the while loop stops so we don't need to worry about opcount.

Comment (dreverri) [reply core/shared/src/main/scala/zio/internal/FiberContext.scala]: Another idea is to add a `resume` to `Yield` and create a new `Yield` if `opcount == maxopcount` before matching on the tag. This also allows the addition of `yieldNow` to the trait so users can opt-in to yielding without creating an intermediate FlatMap.

https://github.com/zio/zio/compare/master...dreverri:djr/yield-resume?w=1

Comment (runtologist) [reply core/shared/src/main/scala/zio/internal/FiberContext.scala]: I see. I like both ideas. I tend to prefer the first, because it is simpler. What do you think?

Comment (runtologist) [reply core/shared/src/main/scala/zio/internal/FiberContext.scala]: Incorporated the first one. Thanks for the good suggestion. 🙏

File: core/shared/src/main/scala/zio/internal/FiberContext.scala [hunk 3]
```diff
@@ -252,10 +252,8 @@ private[zio] final class FiberContext[E, A](
               // Cannot capture `curZio` since it will be boxed into `ObjectRef`,
               // which destroys performance. So put `curZio` into a temp val:
               val tmpIo = curZio
-
-              curZio = ZIO.yieldNow *> tmpIo
-
-              opcount = 0
+              evaluateLater(tmpIo)
```
Comment (jdegoes) [inline core/shared/src/main/scala/zio/internal/FiberContext.scala]: This solution does not require `tmpIo`, so you can simplify to:

```scala
evaluateLater(tmpIo)
curZio = null
```

**Comment by kaishh** [comment]
Wow! Thank you! :pray:

File: core/shared/src/main/scala/zio/internal/FiberContext.scala (hunk 3 above)
Comment (runtologist) [reply core/shared/src/main/scala/zio/internal/FiberContext.scala]: done, thank you.

**Comment by jdegoes** [comment]
@runtologist Thank you for fixing this! 🙏
