### PR TITLE
Fix ZIO#timeoutTo inheriting wrong value from FiberRef#locally (#9693)

### LINKED ISSUE #9693: FiberRef#locally doesn't restore value when interrupted with timeout
zio 2.1.16
scala 2.13.16

```scala
      test("`locally` restores parent's value after timeout") {
        for {
          fiberRef <- FiberRef.make("initial")
          child    <- fiberRef.locally("update")(ZIO.sleep(10.seconds)).timeout(1.second).fork
          _        <- TestClock.adjust(1.second)
          _        <- child.join
          value    <- fiberRef.get
        } yield assert(value)(equalTo("initial"))
      }
```

This test fails with  `"update" was not equal to "initial"` message.  Looks like problem could be related to zio.FiberRef.unsafe.PatchFiber#locally / locallyWithin implementation which doesn't work with `timeout` logic

### PR DESCRIPTION
**Pull request by vladimirkl**
Fixes #9693. The cause of this issue is that current `timeoutTo`  implementation inherits `FiberRef` values from winner / loser before interruption - not catching  reset  to original value in `FiberRef#locally`. This PR moves `inheritAll` after `interruptAs`

### CODE REVIEW

File: core-tests/shared/src/test/scala/zio/FiberRefSpec.scala [hunk 1]
```diff
@@ -101,6 +101,15 @@ object FiberRefSpec extends ZIOBaseSpec {
           value      <- fiberRef.get
         } yield assert(localValue)(equalTo(update)) && assert(value)(equalTo(initial))
       },
+      test("`locally` restores parent's value after timeout") {
+        for {
+          fiberRef <- FiberRef.make(initial)
+          child    <- fiberRef.locally(update)(ZIO.sleep(10.seconds)).timeout(1.second).fork
```
Comment (hearnadam) [inline core-tests/shared/src/test/scala/zio/FiberRefSpec.scala]:
```suggestion
          child    <- fiberRef.locally(update)(ZIO.never).timeout(1.second).fork
```

**Review by kyri-petrou — APPROVED** [review]
Thanks!
