### PR TITLE
Fix race condition in `CyclicBarrier`

### LINKED ISSUE #10351: CyclicBarrier with streams fails after some cycles
Hi,

I am trying to make two infinite streams `await` on the same `CyclicBarrier` before outputing positive/negative random integers. I use `repeat(Schedule.forever)`, `runDrain` and `ZIO.collectAllParDiscard`; the "positive" stream is like this:

```Scala
ZStream.fromZIO(cb.await).tap(_ => ZIO.debug(gen.nextInt.abs)).repeat(Schedule.forever).runDrain
```

So, I launch the REPL:

```bash
scala-cli repl -S 3.8.0-RC4 --dep dev.zio::zio-concurrent:2.1.24 --dep dev.zio::zio-streams:2.1.24
```

Then I enter the following lines:

```scala
scala> import zio.*, zio.stream.*, zio.concurrent.*

scala> val gen = scala.util.Random
val gen: scala.util.Random.type = scala.util.Random$@6c9b2d0e

scala> val runtime = Runtime.default
val runtime: zio.Runtime[Any] = Runtime(environment = ZEnvironment(), fiberRefs = FiberRefLocals(), runtimeFlags = RuntimeFlags(Interruption, CooperativeYielding, FiberRoots))

scala> def job(cb: CyclicBarrier) = ZIO.collectAllParDiscard(List(ZStream.fromZIO(cb.await).tap(_ => ZIO.debug(gen.nextInt.abs)).repeat(Schedule.forever).runDrain, ZStream.fromZIO(cb.await).tap(_ => ZIO.debug(-gen.nextInt.abs)).repeat(Schedule.forever).runDrain))
def job(cb: zio.concurrent.CyclicBarrier): zio.ZIO[Any, Unit, Unit]

scala> CyclicBarrier.make(2).flatMap(job)
val res0: zio.ZIO[Any, Unit, Unit] = FlatMap(
  trace = "<empty>.rs$line$6.res0(rs$line$6:1)",
  first = FlatMap(
    trace = "zio.concurrent.CyclicBarrier.make(CyclicBarrier.scala:73)",
    first = Sync(
      trace = "zio.concurrent.CyclicBarrier.make(CyclicBarrier.scala:70)",
      eval = zio.Ref$$$Lambda/0x00007fbcac6e38f0@76a4394a
    ),
    successK = zio.concurrent.CyclicBarrier$$$Lambda/0x00007fbcac6e3bb0@581d1c66
  ),
  successK = rs$line$6$$$Lambda/0x00007fbcac6e5048@18b94906
)
```

But, when I run `res0`, the output halts:

```scala
scala> Unsafe.unsafe { implicit unsafe =>
         runtime.unsafe.run(res0)
       }
1418110016
-460596314
219137142
-905623904
1899590201
-1357003859
-1683614146
702573269
434598603
-478669152
-33512804
753216622
1154963113
-1029809319
1945147598
-665824362
-1030584444
522272978
1645690094
-1694636633
81114390
1449145849
760626709
-1943166876
val res1: zio.Exit[Unit, Unit] = Failure(
  Both(
    left = Empty,
    right = Both(
      left = Fail(value = (), trace = StackTrace(fiberId = None, stackTrace = IndexedSeq())),
      right = Interrupt(
        fiberId = Runtime(
          id = 1926225872,
          startTimeMillis = 1767025443717L,
          location = "<empty>.rs$line$5.job(rs$line$5:1)"
        ),
        trace = StackTrace(
          fiberId = Runtime(
            id = 519548941,
            startTimeMillis = 1767025443295L,
            location = "<empty>.rs$line$5.job(rs$line$5:1)"
          ),
          stackTrace = IndexedSeq("<empty>.rs$line$5.job(rs$line$5:1)")
        )
      )
    )
  )
)
```

Without `await`ing on the barrier, the two streams are infinite in output indeed. I am coding at a simplistic level, being knew to ZIO, but I was not quite expecting a `Fail` here...

### PR DESCRIPTION
**Pull request by kyri-petrou**
/fixes #10351

There seems to be a race condition in `CyclicBarrier` under high contention, where it was possible for a fiber to re-enter the `await` block before the "winning" fiber run the `reset` effect and cause an invalid state.

I rewrote the implementation of `CyclicBarrier` using volatile variables and a `Semaphore` to ensure exclusive access to certain parts of the codepath that might lead to invalid states if concurrent access is allowed

### CODE REVIEW

File: concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala [hunk 1]
```diff
@@ -16,59 +17,98 @@ import zio._
...
+              }
+            val out = nParties - n
+            f.as(out)
+          }
+        }
+      }.flatten
     }
 
+  /** Queries if this barrier is in a broken state. */
+  val isBroken: UIO[Boolean] =
```
Comment (hearnadam) [inline concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala]: Do we need a val for this?

File: concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala [hunk 2]
```diff
@@ -16,59 +17,98 @@ import zio._
...
 
   def make(parties: Int, action: UIO[Any]): UIO[CyclicBarrier] =
-    for {
-      waiting <- Ref.make(0)
-      broken  <- Ref.make(false)
-      lock    <- Promise.make[Unit, Unit].flatMap(Ref.make(_))
-    } yield new CyclicBarrier(parties, waiting, lock, action, broken)
+    ZIO.succeed(new CyclicBarrier(parties, action))
+
+  private def newPromise: Promise[Unit, Unit] =
```
Comment (hearnadam) [inline concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala]: minor, but since this is not suspended, I feel like it should have parens
```suggestion
  private def newPromise(): Promise[Unit, Unit] =
```

File: concurrent/src/test/scala/zio/concurrent/CyclicBarrierSpec.scala [hunk 3]
```diff
@@ -17,7 +20,7 @@ object CyclicBarrierSpec extends ZIOSpecDefault {
         } yield assert(barrier.parties)(equalTo(parties)) &&
           assert(isBroken)(equalTo(false)) &&
           assert(waiting)(equalTo(0))
-      },
+      } @@ nonFlaky(10000),
```
Comment (hearnadam) [inline concurrent/src/test/scala/zio/concurrent/CyclicBarrierSpec.scala]: Do we want to make these non-flaky on JS?

File: concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala [hunk 4]
```diff
@@ -16,59 +17,98 @@ import zio._
...
+      _broken = true
+      _lock.unsafe.done(Exit.failUnit)(Unsafe)
+      ()
+    })
 
-  /** The number of parties currently waiting at the barrier. */
-  val waiting: UIO[Int] = _waiting.get
+  private val succeedAndReset =
+    semaphore.withPermit(ZIO.succeed {
+      _lock.unsafe.done(Exit.unit)(Unsafe)
```
Comment (hearnadam) [inline concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala:41]: Is the issue succeedUnit that it requires an evidence parameter making explicit Unsafe hard?
```suggestion
      _lock.unsafe.succeedUnit
```

File: concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala [hunk 5]
```diff
@@ -16,59 +17,98 @@ import zio._
...
+              n0
+            }
+            val f =
+              if (n == nParties) restore(_action) *> succeedAndReset
+              else {
+                val lock = _lock
+                restore(lock.await).onInterrupt(break)
+              }
+            val out = nParties - n
+            f.as(out)
```
Comment (hearnadam) [inline concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala]: Some renames for clarity:
```suggestion
            val waiting = {
              val waiting0 = _waiting + 1
              if (waiting0 == nParties) _waiting = 0
              else _waiting = n0
              waiting0
            }
            val f =
              if (waiting == nParties) restore(_action) *> succeedAndReset
              else {
                val lock = _lock
                restore(lock.await).onInterrupt(break)
              }
            val remaining = nParties - waiting
            f.as(remaining)
```

Comment (hearnadam) [reply concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala]: This line is very sneaky: `restore(_action) *> succeedAndReset`

At first, it looks like it will double acquire the permit, but it really executes after the `flatten`. 

Regardless, does it need to be `.ensuring` instead of flatMap?

File: concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala (hunk 4 above)
Comment (kyri-petrou) [reply concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala:41]: Yes, I'd have to write this, which is really ugly :/

```scala
_lock.unsafe.succeedUnit(implicitly, implicitly, Unsafe)
```

Also, something that we missed during the review of this is that the method requires an implicit `Trace` when it's not needed at all.

File: concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala (hunk 5 above)
Comment (kyri-petrou) [reply concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala]: > Regardless, does it need to be .ensuring instead of flatMap?

AFAICT there's no `ensuring`. Are you referring to `onInterrupt`?

> This line is very sneaky: restore(_action) *> succeedAndReset

Yeah it is but it's kind of necessary. We should only be holding the lock while we modify the state of the `CyclicBarrier`. Which is also why the `val lock = _lock` is necessary, otherwise the `restore(...)` function call (which takes the argument by-name) might use the wrong state of `_lock`

File: concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala (hunk 2 above)
Comment (kyri-petrou) [reply concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala]: Good point, thanks!

File: concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala (hunk 1 above)
Comment (kyri-petrou) [reply concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala]: I kept them as vals because they were originally like this. But tbh that's really not needed so I changed it

File: concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala [hunk 6]
```diff
@@ -16,59 +17,98 @@ import zio._
...
-      _broken.set(false)).uninterruptible
+  def reset: UIO[Unit] =
+    semaphore.withPermit(ZIO.succeed(resetUnsafe()))
 
-  /** Queries if this barrier is in a broken state. */
-  val isBroken: UIO[Boolean] = _broken.get
 }
 
 object CyclicBarrier {
+  private implicit def trace: Trace = Trace.empty
```
Comment (hearnadam) [inline concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala:104]: What's this used for?

**Review by hearnadam — APPROVED** [review]

File: concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala (hunk 6 above)
Comment (kyri-petrou) [reply concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala:104]: It's used by a lot of the effects. But because we can't add the `implicit trace: Trace` argument due to bincompat reasons, it's better if we just use an empty trace rather than pollute traces with internal ones

Comment (kyri-petrou) [reply concurrent/src/main/scala/zio/concurrent/CyclicBarrier.scala:104]: It's used by a lot of the effects. But because we can't add the `implicit trace: Trace` argument due to bincompat reasons, it's better if we just use an empty trace rather than pollute traces with internal ones
