### PR TITLE
Split waiting for errors and waiting for completion in foreachPar_. 

### LINKED ISSUE #2642: Flaky foreachPar_ Test
@horned-sphere Can you take a look?

```
[info] ZIO Test
[info] - ZIOSpec
[info]   - foreachPar_
[info]     - accumulates errors
[info]       Set(1, 2) did not satisfy equalTo(Set(1, 2, 3))
```

https://circleci.com/gh/zio/zio/50708?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

### PR DESCRIPTION
**Pull request by horned-sphere**
Fixes problem where errors are not guaranteed to be accumulated. Fixes #2642

### CODE REVIEW

File: core/shared/src/main/scala/zio/ZIO.scala [hunk 1]
```diff
@@ -2300,24 +2300,34 @@ object ZIO {
...
+        causes         <- Ref.make[Cause[E]](Cause.empty)
+        result         <- Promise.make[Nothing, Boolean]
+        failureTrigger <- Promise.make[Unit, Unit]
+        count          <- Ref.make(0)
         fibers <- ZIO.traverse(as) {
                    f(_)
-                     .foldCauseM(c => causes.update(_ && c) *> result.fail(()), _ => {
-                       (succeed.update(_ + 1) >>= { succeed =>
-                         ZIO.when(succeed == size)(result.succeed(()))
+                     .foldCauseM(c => causes.update(_ && c) *> failureTrigger.fail(()), _ => ZIO.unit)
```
Comment (adamgfraser) [inline core/shared/src/main/scala/zio/ZIO.scala]: We don't need to add as part of this PR but you could see a `tapCause` combinator being useful here.

File: core/shared/src/main/scala/zio/ZIO.scala [hunk 2]
```diff
@@ -2300,24 +2300,34 @@ object ZIO {
...
+                     .ensuring {
+                       (count.update(_ + 1) >>= { done =>
+                         ZIO.when(done == size) {
+                           result.complete(failureTrigger.succeed(()))
+                         }
                        }).uninterruptible
```
Comment (adamgfraser) [inline core/shared/src/main/scala/zio/ZIO.scala]: Don't think we need `uninterruptible` here because finalizer in `ensuring` is already uninterruptible.

File: core/shared/src/main/scala/zio/ZIO.scala [hunk 3]
```diff
@@ -2300,24 +2300,34 @@ object ZIO {
...
-                     })
+                     }
                      .fork
                  }
-        interrupter = result.await
+        interrupter = failureTrigger.await
           .catchAll(_ => ZIO.foreach(fibers)(_.interruptAs(parentId).fork) >>= Fiber.joinAll)
           .toManaged_
```
Comment (adamgfraser) [inline core/shared/src/main/scala/zio/ZIO.scala]: You can use the new `forkManaged` here.

File: core-tests/shared/src/test/scala/zio/ZIOSpec.scala [hunk 4]
```diff
@@ -539,11 +539,21 @@ object ZIOSpec extends ZIOBaseSpec {
     ),
     suite("foreachPar_")(
       testM("accumulates errors") {
-        val failures = ZIO
-          .foreachPar_(1 to 3)(IO.fail(_).uninterruptible)
-          .foldCause(_.failures.toSet, _ => Set.empty)
-        assertM(failures)(equalTo(Set(1, 2, 3)))
-      } @@ flaky,
+        def task(started: Ref[Int], trigger: Promise[Nothing, Unit])(i: Int): IO[Int, Unit] =
```
Comment (adamgfraser) [inline core-tests/shared/src/test/scala/zio/ZIOSpec.scala]: Why do we need to change the test here?

Comment (adamgfraser) [reply core-tests/shared/src/test/scala/zio/ZIOSpec.scala]: Ah, I see, you are making sure that the effects aren't pre-interrupted. Makes sense.

File: core/shared/src/main/scala/zio/ZIO.scala (hunk 1 above)
Comment (horned-sphere) [reply core/shared/src/main/scala/zio/ZIO.scala]: In my defence, tapCause didn't exist when I made the PR ;).

I've changed it over as it's fairly trivial and is better.

File: core/shared/src/main/scala/zio/ZIO.scala (hunk 2 above)
Comment (horned-sphere) [reply core/shared/src/main/scala/zio/ZIO.scala]: Good catch. I copy/pasted it into the ensuring without engaging my brain.

File: core/shared/src/main/scala/zio/ZIO.scala (hunk 3 above)
Comment (horned-sphere) [reply core/shared/src/main/scala/zio/ZIO.scala]: Yeah, that does look a bit less mysterious.

File: core-tests/shared/src/test/scala/zio/ZIOSpec.scala (hunk 4 above)
Comment (horned-sphere) [reply core-tests/shared/src/test/scala/zio/ZIOSpec.scala]: Yes, sadly the simple version of the test is still flaky as the fibers can be interrupted before they enter the uninterruptible region.

**Comment by adamgfraser** [comment]
Looks great! Will merge when it goes green!
