### PR TITLE
Attempt to obtain new locks without retrying transaction in ZSTM

### LINKED ISSUE #9215: STM transaction retry loop (regression in 2.1.8)
### Steps to reproduce:

```
git clone https://github.com/nokia/stm-benchmark.git
cd stm-benchmark
```

#### With version 2.1.7:

```
git checkout b25cc70  # uses 2.1.7
sbt zstm/test
```

Finishes in about 2-3 seconds, and after some debugging output, it prints:

```
...
com.nokia.stmbenchmark.zstm.ZstmSolverSpec:
  + minimal.txt 0.756s
  + testBoard.txt 0.962s
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 3 s, completed Sep 23, 2024, 4:24:49 PM
```

#### With version 2.1.8:

```
git checkout 97d9bed  # uses 2.1.8
sbt zstm/test
```

It doesn't complete, and after some successful transactions, it continually seems to retry the same 2 transactions:

```
...
Trying to commit Route(Point(28,26),Point(64,29))
Trying to commit Route(Point(38,66),Point(47,36))
Trying to commit Route(Point(28,26),Point(64,29))
Trying to commit Route(Point(38,66),Point(47,36))
...
```

### Additional information:

I also tried it with version 2.1.9, it has the same problem.

Based on some debugging, it seems to me, that 2 threads are taking turns continuously retrying the same 2 transactions, which never seem to be able to commit. (I've let it run for more than a few minutes without the debug `println`s, and it spins the CPU, but doesn't seem to finish.)

### PR DESCRIPTION
**Pull request by kyri-petrou**
/fixes #9215

The issue is that in cases where a transaction creates ZSTMs internally, if there is contention and we reach the `MaxRetries` section, the ZSTM loop will keep retrying because the locks will be changing on each iteration.

With this PR we attempt to obtain the diff in locks while we still hold the "outer" locks. This fixes the issue but is also more performant as we're not retrying the entire transaction in cases where we can acquire the additional locks

### CODE REVIEW

File: core-tests/shared/src/test/scala/zio/stm/ZSTMSpec.scala [hunk 1]
```diff
@@ -1239,7 +1239,27 @@ object ZSTMSpec extends ZIOBaseSpec {
         _     <- transaction(ref).commit
         value <- ref.get
       } yield assertTrue(value == 9)
-    } @@ exceptJS(nonFlaky(10000))
+    } @@ exceptJS(nonFlaky(10000)),
+    test("doesn't deadlock under concurrency when transactions create new ZSTMs - i9215") {
+      def transaction(arr: TArray[String]) =
+        ZSTM.suspend {
+          Thread.sleep(1) // Force ZSTM lock contention
```
Comment (ghostdogpr) [inline core-tests/shared/src/test/scala/zio/stm/ZSTMSpec.scala]: Looks like it fails with Scala.js despite the except aspect

Comment (kyri-petrou) [reply core-tests/shared/src/test/scala/zio/stm/ZSTMSpec.scala]: Aghh the except part is for `nonFlaky`. Seems that ScalaJS doesn't like the `Thread.sleep` part, I'll move the test to be run for JVM/Native only

**Comment by ghostdogpr** [comment]
Native doesn't like it either? Or it's just flaky?

**Comment by kyri-petrou** [comment]
> Native doesn't like it either? Or it's just flaky?

Seems like an issue with GC. I changed the test to run on JVM only for the time being

**Review by ghostdogpr — APPROVED** [review]
