### PR TITLE
Remove Subscriber After Unsubscribing

### LINKED ISSUE #8178: Hub probably incorrectly releases subscriptions
`zio 2.0.15`

In some cases Hub incorrectly releases subscriptions, which causes resource leak and constantly growing internal subscribers list
```scala
    Hub.bounded[String](1024).flatMap { hub =>
      ZIO
        .scoped(
          hub.subscribe
            .flatMap { q =>
              for {
                f <- q.take.fork
                _ <- hub.publish("abcd").timed.map(_._1).debug
                _ <- f.join
              } yield ()
            }
        )
        .repeatN(1000_000)
    }
```
in this example  you can see the publishing time increases with the size of the subscriber list (which can be verified with debugger)

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #8178.

### CODE REVIEW

File: core/shared/src/main/scala/zio/Hub.scala [hunk 1]
```diff
@@ -352,6 +353,7 @@ object Hub {
       hub: internal.Hub[A],
       subscribers: Set[(internal.Hub.Subscription[A], MutableConcurrentQueue[Promise[Nothing, A]])]
     ): Unit = {
+      println(subscribers.size)
```
Comment (narma) [inline core/shared/src/main/scala/zio/Hub.scala]: debug print?

**Review by narma — APPROVED** [review]

File: core/shared/src/main/scala/zio/Hub.scala [hunk 2]
```diff
@@ -229,6 +229,7 @@ object Hub {
           ZIO
             .whenZIO(shutdownHook.succeed(())) {
               ZIO.foreachPar(unsafePollAll(pollers))(_.interruptAs(fiberId)) *>
+                ZIO.succeed(subscribers.remove(subscription -> pollers)) *>
                 ZIO.succeed(subscription.unsubscribe()) *>
                 ZIO.succeed(strategy.unsafeOnHubEmptySpace(hub, subscribers))
```
Comment (guizmaii) [inline core/shared/src/main/scala/zio/Hub.scala]: What do you think about:
```suggestion
                ZIO.succeed {
                  subscribers.remove(subscription -> pollers))
                  subscription.unsubscribe()
                  strategy.unsafeOnHubEmptySpace(hub, subscribers)
                }
```
?

Comment (adamgfraser) [reply core/shared/src/main/scala/zio/Hub.scala]: I find the way it is currently written more readable and feels like a premature optimization gives that this code is only run when the subscription is finalized but you can do that too!

File: core/shared/src/main/scala/zio/Hub.scala [hunk 3]
```diff
@@ -229,6 +229,7 @@ object Hub {
           ZIO
             .whenZIO(shutdownHook.succeed(())) {
               ZIO.foreachPar(unsafePollAll(pollers))(_.interruptAs(fiberId)) *>
+                ZIO.succeed(subscribers.remove(subscription -> pollers)) *>
```
Comment (jdegoes) [inline core/shared/src/main/scala/zio/Hub.scala]: It will make me very happy if this is written as:

```scala
*> ZIO.succeed {
  subscribers.remove(subscription -> pollers)
  subscription.unsubscribe()
  strategy.unsafeOnHubEmptySpace(hub, subscribers)
}
```

**Review by jdegoes — DISMISSED** [review]

File: core/shared/src/main/scala/zio/Hub.scala (hunk 3 above)
Comment (adamgfraser) [reply core/shared/src/main/scala/zio/Hub.scala]: Sure!

File: core/shared/src/main/scala/zio/Hub.scala [hunk 4]
```diff
@@ -171,13 +171,15 @@ object Hub {
...
-        ZIO.acquireRelease {
-          makeSubscription(hub, subscribers, strategy).tap { dequeue =>
-            scope.addFinalizer(dequeue.shutdown)
-          }
-        } { dequeue =>
-          dequeue.shutdown
-        }
+        ZIO.acquireReleaseExit {
+          for {
+            child   <- scope.fork
```
Comment (szlepermarcin) [inline core/shared/src/main/scala/zio/Hub.scala:176]: I'm not sure if this will help with the growing release map - `scope.fork` under the hood seems to also add a finalizer to release map

Comment (adamgfraser) [reply core/shared/src/main/scala/zio/Hub.scala:176]: It removes the finalizer when the scope is closed.

Comment (szlepermarcin) [reply core/shared/src/main/scala/zio/Hub.scala:176]: ok, now i noticed how it works, it should be ok - sorry for bothering you

Comment (adamgfraser) [reply core/shared/src/main/scala/zio/Hub.scala:176]: No worries! Thanks for raising!

**Review by vigoo — APPROVED** [review]
