### PR TITLE
clock.currentDateTime reflects exceptions in type signature (#3052)

### LINKED ISSUE #3052: ZIO Clock: Failure to reflect exception in type
Generated by `clock.currentDateTime`, which can apparently throw:

```
java.time.zone.ZoneRulesException: Unknown time-zone ID: America/New_York
```

The fix is to reflect the possibility of failure in the return type. I am not sure if `ZoneRulesException` is the only exception, or if there are others that can be thrown, but they should be reflected in the type and captured via `Task(...).refineOrDie { ... }`.

### PR DESCRIPTION
**Pull request by jorge-vasquez-2301**
Closes #3052. I've modified `clock.currentDateTime` to reflect the fact that an exception can be thrown, for that I've audited all Java methods we call in `clock/package.scala` to see if they throw exceptions or not, so we can properly reflect those in types:

- `System.currentTimeMillis`: https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#currentTimeMillis-- This doesn't throw exceptions.
- `System.nanoTime`: https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#nanoTime-- This doesn't throw exceptions.
- `ZoneId.systemDefault`: https://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html#systemDefault-- It can throw a `DateTimeException` if the converted zone ID has an invalid format, or a `ZoneRulesException` if the converted zone region ID cannot be found. And, it turns out `ZoneRulesException` is a subtype of `DateTimeException`.
- `Instant.ofEpochMilli`: https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#ofEpochMilli-long- It can throw a `DateTimeException` if the instant exceeds the maximum or minimum instant
- `OffsetDateTime.ofInstant`: https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html#ofInstant-java.time.Instant-java.time.ZoneId- It can throw a `DateTimeException` if the result exceeds the supported range

As you can see, all of this methods throw a `DateTimeException`, so now the type signature of `clock.currentDateTime` is `IO[DateTimeException, OffsetDateTime]`.

### CODE REVIEW

**Comment by jorge-vasquez-2301** [comment]
Thank you @adamgfraser!

**Comment by adamgfraser** [comment]
@jorge-vasquez-2301 Looks like the documentation needs to be updated to reflect the change.

**Comment by jorge-vasquez-2301** [comment]
Yeah, I've just realized that @adamgfraser, thanks! I'll make the adjustments

File: core/shared/src/main/scala/zio/clock/package.scala [hunk 1]
```diff
@@ -22,12 +22,14 @@ import java.util.concurrent.TimeUnit
 import zio.duration.Duration
 
 package object clock {
+
+  import java.time.DateTimeException
```
Comment (adamgfraser) [inline core/shared/src/main/scala/zio/clock/package.scala]: Very minor but can we move this to the imports at the top of the file with the other imports from `java.time`?

Comment (jorge-vasquez-2301) [reply core/shared/src/main/scala/zio/clock/package.scala]: Ohhh yeah, sorry, didn't realize that

File: core/shared/src/main/scala/zio/clock/package.scala [hunk 2]
```diff
@@ -45,11 +47,13 @@ package object clock {
             Left(UIO.effectTotal(canceler()))
           }
 
-        def currentDateTime: ZIO[Any, Nothing, OffsetDateTime] =
-          for {
-            millis <- currentTime(TimeUnit.MILLISECONDS)
-            zone   <- ZIO.effectTotal(ZoneId.systemDefault)
-          } yield OffsetDateTime.ofInstant(Instant.ofEpochMilli(millis), zone)
+        def currentDateTime: IO[DateTimeException, OffsetDateTime] =
+          (for {
```
Comment (adamgfraser) [inline core/shared/src/main/scala/zio/clock/package.scala]: Could define an intermediate value here if you wanted to avoid the awkward parentheses around the for comprehension.

Comment (jorge-vasquez-2301) [reply core/shared/src/main/scala/zio/clock/package.scala]: Yeah, makes sense, I'll do that

**Comment by adamgfraser** [comment]
Congratulations on your first contribution to ZIO!

**Comment by jorge-vasquez-2301** [comment]
Thanks very much @adamgfraser!
