### PR TITLE
Fix ZPool hangs during parallel item acquisition after invalidation (…

### LINKED ISSUE #8820: ZPool hangs during parallel item acquisition after invalidation
The following program hangs. Which, I guess, is not supposed to happen.

```scala

package test

import zio.{Scope, ZIO, ZIOAppArgs, ZIOAppDefault, ZPool}

import java.time.Duration

object TestPool extends ZIOAppDefault {

  private val program: ZIO[Any, Throwable, Unit] = ZIO.scoped {
    for {
      pool <- ZPool.make(
        ZIO.succeed("item").tap(r => ZIO.logInfo(s"Made $r")),
        0 to 1,
        Duration.ofSeconds(10)
      )
      getZIO = ZIO.scoped {
        for {
          _ <- ZIO.logInfo(s"Acquiring...")
          v <- pool.get
          _ <- ZIO.logInfo(s"Got: $v")
          _ <- pool.invalidate(v)
          _ <- ZIO.logInfo(s"Invalidated")
        } yield v
      }

      res <- ZIO.foreachPar(Seq.fill(2)(0)) { _ => getZIO.tap(r => ZIO.logInfo(s"Received: $r")) }
    } yield ()
  }

  override def run: ZIO[ZIOAppArgs & Scope, Any, Any] = program
}
```

The log is the following:

```log
thread=#zio-fiber-8 message="Acquiring..." location=test.TestPool.program.getZIO file=TestPool.scala line=18
thread=#zio-fiber-7 message="Acquiring..." location=test.TestPool.program.getZIO file=TestPool.scala line=18
thread=#zio-fiber-9 message="Made item" location=test.TestPool.program file=TestPool.scala line=12
thread=#zio-fiber-7 message="Got: item" location=test.TestPool.program.getZIO file=TestPool.scala line=20
thread=#zio-fiber-7 message="Invalidated" location=test.TestPool.program.getZIO file=TestPool.scala line=22
thread=#zio-fiber-7 message="Received: item" location=test.TestPool.program file=TestPool.scala line=26

(program hangs here)
```

If I change `ZIO.foreachPar` to just `ZIO.foreach`, everything works as expected:

```log
thread=#zio-fiber-4 message="Acquiring..." location=test.TestPool.program.getZIO file=TestPool.scala line=18
thread=#zio-fiber-7 message="Made item" location=test.TestPool.program file=TestPool.scala line=12
thread=#zio-fiber-4 message="Got: item" location=test.TestPool.program.getZIO file=TestPool.scala line=20
thread=#zio-fiber-4 message="Invalidated" location=test.TestPool.program.getZIO file=TestPool.scala line=22
thread=#zio-fiber-4 message="Received: item" location=test.TestPool.program file=TestPool.scala line=26
thread=#zio-fiber-4 message="Acquiring..." location=test.TestPool.program.getZIO file=TestPool.scala line=18
thread=#zio-fiber-8 message="Made item" location=test.TestPool.program file=TestPool.scala line=12
thread=#zio-fiber-4 message="Got: item" location=test.TestPool.program.getZIO file=TestPool.scala line=20
thread=#zio-fiber-4 message="Invalidated" location=test.TestPool.program.getZIO file=TestPool.scala line=22
thread=#zio-fiber-4 message="Received: item" location=test.TestPool.program file=TestPool.scala line=26

Process finished with exit code 0
```

I use scala 3.4.1 and sbt 1.9.7.
I tried ZIO 2.0.22 and ZIO 2.1.0-RC5, with the same outcome.

### PR DESCRIPTION
**Pull request by daemas**
Fix #8820

/claim #8820

### CODE REVIEW

File: core/shared/src/main/scala/zio/ZPool.scala [hunk 1]
```diff
@@ -215,7 +215,7 @@ object ZPool {
           attempted.forEach(a => invalidated.update(_ - a)) *>
             attempted.finalizer *>
             state.modify { case State(size, free) =>
-              if (size <= range.start)
+              if (size <= range.start || free < 0)
```
Comment (jdegoes) [inline core/shared/src/main/scala/zio/ZPool.scala:218]: How can `free` be less than zero? Isn't that a bug that should be fixed directly?

Comment (daemas) [reply core/shared/src/main/scala/zio/ZPool.scala:218]: I believe negative values represent the number of requests awaiting in queue before an item becomes available.

**Review by jdegoes — APPROVED** [review]
