### PR TITLE
Fix #9505 Constructors in assertTrue (Scala 3)

### LINKED ISSUE #9505: zio.assertTrue macros works incorrect
Hi! I have problem with `zio.assertTrue` macros in `scala 3`.  Scala version = 3.3.3

i get some weird error, when i execute test in Scala 3. But i don't have this problem in scala 2

```scala
import zio.Scope
import zio.test.{Spec, TestEnvironment, ZIOSpecDefault, assertTrue}

import java.nio.charset.StandardCharsets

object TestSpec extends ZIOSpecDefault {

  private val bytes: Array[Byte] = ???

  override def spec: Spec[TestEnvironment & Scope, Any] =
    suite("Test suite")(
      test("Test")(
        assertTrue(
          new String(bytes, StandardCharsets.UTF_8) == "str"
        )
      )
    )
}
```

<details>

<summary>error look like this</summary>

Image

</details>

if I move the string creation out of `assertTrue`, everything works fine

this works good:
```scala
object TestSpec extends ZIOSpecDefault {

  private val bytes: Array[Byte] = ???

  private val str = new String(bytes, StandardCharsets.UTF_8)

  override def spec: Spec[TestEnvironment & Scope, Any] =
    suite("Test suite")(
      test("Test")(
        assertTrue(
          str == "str"
        )
      )
    )
}
```

### PR DESCRIPTION
**Pull request by artembakhanov**
Fix #9505

This PR fixes a bug in assertTrue macro that did not allow using class constructors (in lhs) inside of it.

The problem was that this macro seemed to be originally written in Scala 2 and the `MethodCall` extractor object does not extact constructors. However, in Scala 3 it does. I have added a guard using `isClassConstructor` on Select symbol which does not allow future "decomposing" of the tree. 

Sorry, if what I have described is not understandable, I do not have much experience in contributing to such big projects, so do not hesitate to ask questions. I will try my best to answer them.

### CODE REVIEW

**Review by guizmaii — APPROVED** [review]
LGTM

Thanks for your detailed description in the PR. Was helpful :)

File: test-tests/shared/src/test/scala/zio/test/SmartAssertionSpec.scala [hunk 1]
```diff
@@ -87,6 +87,19 @@ object SmartAssertionSpec extends ZIOBaseSpec {
         assertTrue(zio.Duration.fromNanos(1000) == zio.Duration.Zero)
       }
     ) @@ failing,
+    suite("class constructors")(
```
Comment (hearnadam) [inline test-tests/shared/src/test/scala/zio/test/SmartAssertionSpec.scala:90]: Can you add an 'ops' class based test?

**Review by hearnadam — APPROVED** [review]

File: test-tests/shared/src/test/scala/zio/test/SmartAssertionSpec.scala (hunk 1 above)
Comment (artembakhanov) [reply test-tests/shared/src/test/scala/zio/test/SmartAssertionSpec.scala:90]: If I understood you correctly, the 'ops' classes are not supported now, at least that's what I see from #9642.
I you want an explicit 'ops' instance creation, I can do that

Comment (hearnadam) [reply test-tests/shared/src/test/scala/zio/test/SmartAssertionSpec.scala:90]: Aren't Ops classes failing due to the issue you fixed? I was just hoping to include the `Duration` example.

Comment (artembakhanov) [reply test-tests/shared/src/test/scala/zio/test/SmartAssertionSpec.scala:90]: Unfortunately, it is a completely different issue. The one I fixed is only about explicit constructor call, #9642 is about impossibility of implicit cast to some type A having a compare operation method.

Comment (artembakhanov) [reply test-tests/shared/src/test/scala/zio/test/SmartAssertionSpec.scala:90]: I want to take a deeper look into #9642 but outside of this PR
