### PR TITLE
Fixes and inference improvements to ZSink combinators

### LINKED ISSUE #1509: Does Sink really need a distinct leftover type parameter?
*To be discussed on one of the hackathons. Or here, if anyone wants to chime in.*

Data points:
- All sinks I've used either had `A0 = A`, or `A0 = Nothing`
- We have just two constructors (`Sink.fold`, `Sink.foldM`) that create sinks with `A0 != A`

It looks like we could just do with always returning a `Chunk[A]` as the leftover?

### LINKED ISSUE #1676: Refactor ZSink#collectAllWhileWith to not use stepChunk
And use stepChunkSlice instead, which doesn't discard elements.

### LINKED ISSUE #1682: ZSink#takeWhile continuation function is wrong
Should be
`def cont(state: State) = state._2.isEmpty && self.cont(state._1)`.

The sink is done whenever a stream element does not pass the predicate and is returned as remainder.

### PR DESCRIPTION
**Pull request by iravid**
Resolves #1682 
Resolves #1676

@vasilmkd - could you have a look? Thanks!

### CODE REVIEW

File: streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala [hunk 1]
```diff
@@ -439,15 +423,45 @@ class SinkSpec(implicit ee: org.specs2.concurrent.ExecutionEnv) extends TestRunt
     unsafeRun(sinkIteration(sink, 1).either.map(_ must_=== Left("Ouch")))
   }
 
+  private def collectAllSucceed = {
```
Comment (vasilmkd) [inline streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala]: Thanks for this test.

File: streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala [hunk 2]
```diff
@@ -439,15 +423,45 @@ class SinkSpec(implicit ee: org.specs2.concurrent.ExecutionEnv) extends TestRunt
...
+            .step(init, 1)
+            .flatMap(sink.step(_, 2))
+            .flatMap(sink.step(_, 3))
+      result <- sink.extract(s)
+    } yield result must_=== (List(5, 5, 5, 5) -> Chunk(1, 2, 3))
+
+    unsafeRun(test)
+  }
+
+  private def collectAllIgnoreWhile = {
```
Comment (vasilmkd) [inline streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala]: And this one.

File: streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala [hunk 3]
```diff
@@ -489,9 +503,8 @@ class SinkSpec(implicit ee: org.specs2.concurrent.ExecutionEnv) extends TestRunt
   }
 
   private def collectAllWhileFalsePredicate = {
```
Comment (vasilmkd) [inline streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala]: Fixed!

File: streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala [hunk 4]
```diff
@@ -509,88 +522,28 @@ class SinkSpec(implicit ee: org.specs2.concurrent.ExecutionEnv) extends TestRunt
...
-    val sink = stepErrorSink.dimap[String, String](_.toInt)(_.toString.reverse)
-    unsafeRun(sinkIteration(sink, "123").either.map(_ must_=== Left("Ouch")))
-  }
-
-  private def dimapExtractError = {
-    val sink = extractErrorSink.dimap[String, String](_.toInt)(_.toString.reverse)
-    unsafeRun(sinkIteration(sink, "123").either.map(_ must_=== Left("Ouch")))
-  }
-
   private def dropWhileHappyPath = {
```
Comment (vasilmkd) [inline streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala]: Inference win, great to see.

File: streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala [hunk 5]
```diff
@@ -1027,8 +967,9 @@ class SinkSpec(implicit ee: org.specs2.concurrent.ExecutionEnv) extends TestRunt
       step3  <- sink.step(step2, 3)
       step4  <- sink.step(step3, 4)
       step5  <- sink.step(step4, 5)
+      cont   = sink.cont(step5)
       result <- sink.extract(step5)
-    } yield result must_=== ((List(1, 2, 3, 4), Chunk.single(5)))
+    } yield (cont must_=== false) and (result must_=== ((List(1, 2, 3, 4), Chunk.single(5))))
```
Comment (vasilmkd) [inline streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala]: Nice.

File: streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala [hunk 6]
```diff
@@ -1053,15 +994,17 @@ class SinkSpec(implicit ee: org.specs2.concurrent.ExecutionEnv) extends TestRunt
...
-      result <- sink.extract(step4)
-    } yield result must_=== ((Some(List(1, 2, 3, 4)), Chunk.empty))
+      under <- sink.initial
+                .flatMap(sink.stepChunk(_, Chunk(1, 2)).map(_._1))
+                .flatMap(sink.extract)
+      over <- sink.initial
+               .flatMap(sink.stepChunk(_, Chunk(1, 2)).map(_._1))
+               .flatMap(sink.stepChunk(_, Chunk(2, 2)).map(_._1))
+               .flatMap(sink.extract)
+    } yield (under must_=== (None -> Chunk.empty)) and (over must_=== (Some(List(1, 2, 2)) -> Chunk(2)))
```
Comment (vasilmkd) [inline streams-tests/jvm/src/test/scala/zio/stream/SinkSpec.scala]: Awesome test.

File: streams/shared/src/main/scala/zio/stream/Sink.scala [hunk 7]
```diff
@@ -176,120 +176,116 @@ object Sink {
...
     f: (S, A) => S
-  ): Sink[Nothing, A, A, S] =
+  ): Sink[Nothing, A, S] =
     ZSink.foldWeightedDecompose(z)(costFn, max, decompose)(f)
 
   /**
    * see [[ZSink.fromEffect]]
    */
-  final def fromEffect[E, B](b: => IO[E, B]): Sink[E, Nothing, Any, B] =
+  final def fromEffect[E, B](b: => IO[E, B]): Sink[E, Any, B] =
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/Sink.scala]: I'm confused. `succeed` gets a type parameter `A`, but this doesn't? How does this compose?

File: docs/datatypes/sink.md [hunk 8]
```diff
@@ -76,7 +79,7 @@ A fold with control over continuation and the remainder produced by the sink.
 `foldLeft` is implemented as a fold that always continues and produces no remainder.
 
 ```scala mdoc:silent
-Sink.fold[Nothing, Int, Int](0)(_ => true)((acc, n) => (acc + n, Chunk.empty))
+Sink.fold(0)(_ => true)((acc, n: Int) => (acc + n, Chunk[Int]()))
```
Comment (jdegoes) [inline docs/datatypes/sink.md]: If this is going to be the new pattern, maybe `Chunk.empty` should take a type parameter like `List.empty`?

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 9]
```diff
@@ -56,40 +56,42 @@ trait ZSink[-R, +E, +A0, -A, +B] { self =>
...
+  final def <|[R1 <: R, E1, B1 >: B](
+    that: ZSink[R1, E1, A, B1]
+  ): ZSink[R1, E1, A, B1] =
     (self orElse that).map(_.merge)
 
-  private[ZSink] final def ?[A00 >: A0, A1 <: A](implicit ev: A1 =:= A00): ZSink[R, Nothing, A00, A1, Option[B]] =
-    new ZSink[R, Nothing, A00, A1, Option[B]] {
+  final def optional = ?
+
+  final def ? : ZSink[R, Nothing, A, Option[B]] =
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: It seems that we have lost the scaladoc when deleting the syntax classes.

File: docs/datatypes/sink.md (hunk 8 above)
Comment (vasilmkd) [reply docs/datatypes/sink.md]: Agreed.

On the other hand, would something like `ZSink[-R, +E, -A, +B]` with `def extract[A1 <: A](state: State): ZIO[R, E, (B, Chunk[A1])]` work?

@jdegoes

File: streams/shared/src/main/scala/zio/stream/Sink.scala (hunk 7 above)
Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/Sink.scala]: Ah good catch. Every sink that has  `A = Any` should be audited. Most of them would need to be polymorphic in `A`. Will fix that.

File: docs/datatypes/sink.md (hunk 8 above)
Comment (iravid) [reply docs/datatypes/sink.md]: Yes, good point.

File: streams/shared/src/main/scala/zio/stream/ZSink.scala (hunk 9 above)
Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/ZSink.scala]: 👍🏻

File: streams-tests/jvm/src/test/scala/zio/stream/StreamSpec.scala [hunk 10]
```diff
@@ -1405,7 +1403,7 @@ class StreamSpec(implicit ee: org.specs2.concurrent.ExecutionEnv) extends TestRu
     val s2 = Stream(1, 2)
 
     s1.mergeWith(s2)(_.toString, _.toString)
-      .run(Sink.succeed("done"))
+      .run(Sink.succeed[String, String]("done"))
```
Comment (jdegoes) [inline streams-tests/jvm/src/test/scala/zio/stream/StreamSpec.scala]: Arg. This is one of the places where it's a loss.

File: docs/datatypes/sink.md (hunk 8 above)
Comment (iravid) [reply docs/datatypes/sink.md]: @vasilmkd It has to be `[A1 >: A]`, actually. 

I'll give that a try in a follow-up. I tried that for a bit but some of the  combinators that extract an underlying sink get confused so I scrapped that direction for now.

File: streams-tests/jvm/src/test/scala/zio/stream/StreamSpec.scala (hunk 10 above)
Comment (iravid) [reply streams-tests/jvm/src/test/scala/zio/stream/StreamSpec.scala]: @jdegoes Oh it's good to have the grandmaster of variance and inference here.

There's a really annoying issue that the Stream's  element type parameter  isn't used to infer the Sink's input type parameter - in `run`, `transduce` and others. Any thoughts on that?

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 11]
```diff
@@ -142,148 +144,129 @@ trait ZSink[-R, +E, +A0, -A, +B] { self =>
...
-  )(f: (S, B) => S)(implicit ev: A00 =:= A1, ev2: A1 =:= A00): ZSink[R, E, A00, A1, S] =
-    collectAllWhileWith[S, A00, A1](_ => true)(z)(f)
-
-  private[ZSink] final def collectAllWhile[A00 >: A0, A1 <: A](
-    p: A1 => Boolean
-  )(implicit ev: A00 =:= A1, ev2: A1 =:= A00): ZSink[R, E, A00, A1, List[B]] =
-    collectAllWhileWith[List[B], A00, A1](p)(List.empty[B])((bs, b) => b :: bs)
-      .map(_.reverse)
+  final def collectAll: ZSink[R, E, A, List[B]] =
+    collectAllWith[List[B]](List.empty[B])((bs, b) => b :: bs).map(_.reverse)
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: Can be simplified. Either `List.empty[B]` with no type parameter or `Nil`.

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 12]
```diff
@@ -142,148 +144,129 @@ trait ZSink[-R, +E, +A0, -A, +B] { self =>
...
 
-  private[ZSink] final def collectAllWhileWith[S, A00 >: A0, A1 <: A](
-    p: A1 => Boolean
-  )(z: S)(f: (S, B) => S)(implicit ev: A00 =:= A1, ev2: A1 =:= A00): ZSink[R, E, A00, A1, S] =
-    new ZSink[R, E, A00, A1, S] {
-      type State = (S, self.State, Boolean, Chunk[A00])
+  final def collectAllN(i: Int): ZSink[R, E, A, List[B]] =
+    new ZSink[R, E, A, List[B]] {
+      case class State(s: self.State, bs: List[B], n: Int, leftover: Chunk[A], dirty: Boolean)
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: This is totally new to me. One could implement abstract types as classes. Seems so simple and logical but wow. :boom:

File: streams-tests/jvm/src/test/scala/zio/stream/StreamSpec.scala (hunk 10 above)
Comment (jdegoes) [reply streams-tests/jvm/src/test/scala/zio/stream/StreamSpec.scala]: Can you paste signatures and I'll make it work (if it's possible 😆 )? Thank you! 🙏

File: streams/shared/src/main/scala/zio/stream/Sink.scala (hunk 7 above)
Comment (jdegoes) [reply streams/shared/src/main/scala/zio/stream/Sink.scala]: Good catch! 👍

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 13]
```diff
@@ -142,148 +144,129 @@ trait ZSink[-R, +E, +A0, -A, +B] { self =>
...
-      .map(_.reverse)
+  final def collectAll: ZSink[R, E, A, List[B]] =
+    collectAllWith[List[B]](List.empty[B])((bs, b) => b :: bs).map(_.reverse)
 
-  private[ZSink] final def collectAllWhileWith[S, A00 >: A0, A1 <: A](
-    p: A1 => Boolean
-  )(z: S)(f: (S, B) => S)(implicit ev: A00 =:= A1, ev2: A1 =:= A00): ZSink[R, E, A00, A1, S] =
-    new ZSink[R, E, A00, A1, S] {
-      type State = (S, self.State, Boolean, Chunk[A00])
+  final def collectAllN(i: Int): ZSink[R, E, A, List[B]] =
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: I like this a lot.

File: streams-tests/jvm/src/test/scala/zio/stream/StreamSpec.scala (hunk 10 above)
Comment (iravid) [reply streams-tests/jvm/src/test/scala/zio/stream/StreamSpec.scala]:
```scala
trait ZSink[-R, +E, A, +B]
object ZSink {
  final def succeed[A, B](b: B): ZSink[Any, Nothing, A, B] = new ZSink[Any, Nothing, A, B] {}
}

trait ZStream[-R, +E, +A] {
  def run[R1 <: R, E1 >: E, A1 >: A, B](sink: ZSink[R1, E1, A1, B]): Unit = ()
}

val stream = new ZStream[Any, Nothing, String] {}
stream.run(ZSink.succeed("OK"))

// cmd0.sc:11: type mismatch;
// found   : ammonite.$sess.cmd0.ZSink[Any,Nothing,Nothing,String]
// required: ammonite.$sess.cmd0.ZSink[Any,Nothing,String,String]
```

Comment (iravid) [reply streams-tests/jvm/src/test/scala/zio/stream/StreamSpec.scala]: @jdegoes ^

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 14]
```diff
@@ -463,36 +446,48 @@ trait ZSink[-R, +E, +A0, -A, +B] { self =>
...
       def extract(state: State)    = self.extract(state).mapError(f)
       def cont(state: State)       = self.cont(state)
     }
 
-  /**
-   * Effectfully maps the value produced by this sink.
-   */
-  final def mapM[R1 <: R, E1 >: E, C](f: B => ZIO[R1, E1, C]): ZSink[R1, E1, A0, A, C] =
-    new ZSink[R1, E1, A0, A, C] {
+  final def mapInput[C](f: C => A)(g: A => C): ZSink[R, E, C, B] =
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: Could use a scaladoc. Same with `mapInputM`.

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 15]
```diff
@@ -508,29 +503,29 @@ trait ZSink[-R, +E, +A0, -A, +B] { self =>
    * Right: ===== SUCCEEDS!
    *             xxxxxxxxx <- Should NOT be consumed
    */
-  final def orElse[R1 <: R, E1, A00 >: A0, A1 <: A, C](
-    that: ZSink[R1, E1, A00, A1, C]
-  )(implicit ev: A1 =:= A00): ZSink[R1, E1, A00, A1, Either[B, C]] =
-    new ZSink[R1, E1, A00, A1, Either[B, C]] {
+  final def orElse[R1 <: R, E1, C](
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: Feels good to see the complex combinators migrated without too much hassle. It looks like we got them right last time. :smile:

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 16]
```diff
@@ -1111,119 +973,119 @@ object ZSink extends ZSinkPlatformSpecific {
...
+    foldM[R, E, A, (List[A], Boolean)]((Nil, true))(_._2) {
       case ((as, _), a) =>
         p(a).map(if (_) ((a :: as, true), Chunk.empty) else ((as, false), Chunk.single(a)))
     }.map(_._1.reverse)
 
   /**
    * Creates a sink halting with the specified `Throwable`.
    */
-  final def die(e: Throwable): ZSink[Any, Nothing, Nothing, Any, Nothing] =
+  final def die(e: Throwable): ZSink[Any, Nothing, Any, Nothing] =
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: Just to mark them for having `Any`, `die`, `dieMessage` and `drain`.

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 17]
```diff
@@ -1446,15 +1308,15 @@ object ZSink extends ZSinkPlatformSpecific {
    * Creates a sink by starts consuming value as soon as one fails
    * the predicate `p`.
    */
-  final def ignoreWhile[A](p: A => Boolean): ZSink[Any, Nothing, A, A, Unit] =
+  final def ignoreWhile[A](p: A => Boolean): ZSink[Any, Nothing, A, Unit] =
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: I'd like this to be a `SinkPure` and not delegate through `ignoreWhileM`. Ignore if you think it's not worth it.

**Comment by vasilmkd** [comment]
Another day another `ZSink` refactor. :laughing:

Initial review done. I will be around for follow up changes.

File: streams/shared/src/main/scala/zio/stream/ZSink.scala (hunk 17 above)
Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/ZSink.scala]: Yeah we'll do that in a follow-up. There are several combinators that can be overriden in `SinkPure`.

**Comment by iravid** [comment]
Hmm. So, I went over the changes again and I admit I am not sold on whether the inference changes are a win or not. So I'm going to backpedal on this and keep `A0` separate.

**Comment by vasilmkd** [comment]
I stand by your decision.

**Comment by iravid** [comment]
@vasilmkd I moved the definitions of combinators that use `A0 = A` and have problematic inference into `InputRemainderOps`. Figured keeping the private methods on the trait was redundant.

**Comment by vasilmkd** [comment]
@iravid I saw that and like it a lot. Big :+1:. It will take some more consideration when implementing future combinators but the removal of implicit compiler evidence is worth it in my opinion.

Can I bother you to go through the tests again and try to remove as much of the type parameters as possible? Just as a testament to the improved inference.

File: streams/shared/src/main/scala/zio/stream/Sink.scala [hunk 18]
```diff
@@ -242,13 +242,9 @@ object Sink {
   /**
    * see [[ZSink.succeed]]
    */
-  final def succeed[B](b: B): Sink[Nothing, Nothing, Any, B] =
+  final def succeed[A, B](b: B): Sink[Nothing, A, A, B] =
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/Sink.scala]: `A` should be reverted now. 😄

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 19]
```diff
@@ -947,127 +665,428 @@ trait ZSink[-R, +E, +A0, -A, +B] { self =>
     that: ZSink[R1, E1, A00, A1, C]
   )(f: (B, C) => D)(implicit ev: A00 =:= A1, ev2: A1 =:= A00): ZSink[R1, E1, A00, A1, D] =
     zip(that).map(f.tupled)
-
 }
 
 object ZSink extends ZSinkPlatformSpecific {
 
-  implicit class InputRemainderOps[R, E, A, B](val sink: ZSink[R, E, A, A, B]) extends AnyVal {
+  implicit class InputRemainderOps[R, E, A, B](private val sink: ZSink[R, E, A, A, B]) {
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: `extends AnyVal`

File: streams/shared/src/main/scala/zio/stream/Sink.scala (hunk 18 above)
Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/Sink.scala]: It's actually required because of the leftovers.

File: streams/shared/src/main/scala/zio/stream/ZSink.scala (hunk 19 above)
Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/ZSink.scala]: Can't work because of the inner classes that are defined. Not a big loss.

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 20]
```diff
@@ -947,127 +665,428 @@ trait ZSink[-R, +E, +A0, -A, +B] { self =>
...
+        def extract(state: State) = self.extract(state._1)
+
+        def cont(state: State) = self.cont(state._1)
+      }
+
+    /**
+     * Filters the inputs fed to this sink.
+     */
+    def filter(f: A => Boolean): ZSink[R, E, A0, A, B] =
+      self match {
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: Nitpicking. Not sure how I feel about having `SinkPure` implementations in this file from a discoverability and maintainability standpoint.

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 21]
```diff
@@ -947,127 +665,428 @@ trait ZSink[-R, +E, +A0, -A, +B] { self =>
...
+              val results   = list.map { case (k, (b, _)) => (k, b) }.toMap
+              val leftovers = Chunk.fromIterable(list.map { case (k, (_, chunk)) => (k, chunk) }).filter(_._2.notEmpty)
+              (results, leftovers)
+            }
+
+        def cont(state: State) = state.values.forall(self.cont)
+      }
   }
 
   private[ZSink] object internal {
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: Can the `Optional` ADT be migrated to `?` as well? OTOH Not sure if `Side` is used in multiple combinators.

File: streams/shared/src/main/scala/zio/stream/Sink.scala (hunk 18 above)
Comment (vasilmkd) [reply streams/shared/src/main/scala/zio/stream/Sink.scala]: Sorry yes, I skimmed over the implementation.

File: streams/shared/src/main/scala/zio/stream/ZSink.scala (hunk 19 above)
Comment (vasilmkd) [reply streams/shared/src/main/scala/zio/stream/ZSink.scala]: Sorry, can you point me to the defined classes? I can't find anything.

Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/ZSink.scala]: `case class State` in `collectAllN`

File: streams/shared/src/main/scala/zio/stream/ZSink.scala (hunk 20 above)
Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/ZSink.scala]: Well, since `filter` was moved out to an implicit class to improve inference, it can no longer be overriden in `SinkPure.

File: streams/shared/src/main/scala/zio/stream/ZSink.scala (hunk 21 above)
Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/ZSink.scala]: Yup! Moved it

File: streams/shared/src/main/scala/zio/stream/ZSink.scala (hunk 19 above)
Comment (vasilmkd) [reply streams/shared/src/main/scala/zio/stream/ZSink.scala]: Yes, thanks.

File: streams/shared/src/main/scala/zio/stream/ZSink.scala (hunk 20 above)
Comment (vasilmkd) [reply streams/shared/src/main/scala/zio/stream/ZSink.scala]: I'm well aware... we'll live with it. :-)

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 22]
```diff
@@ -1606,19 +1664,15 @@ object ZSink extends ZSinkPlatformSpecific {
...
    * Creates a single-value sink from a value.
    */
-  final def succeed[B](b: B): ZSink[Any, Nothing, Nothing, Any, B] =
-    new SinkPure[Nothing, Nothing, Any, B] {
-      type State = Unit
-      val initialPure                    = ()
-      def stepPure(state: State, a: Any) = ()
-      def extractPure(state: State)      = Right((b, Chunk.empty))
-      def cont(state: State)             = false
+  final def succeed[A, B](b: B): ZSink[Any, Nothing, A, A, B] =
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: I'm guessing this cannot be inferred from the sink before this one? :/

Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/ZSink.scala]: No, unfortunately not. Same problem as with `ZStream#run`

File: streams-tests/jvm/src/test/scala/zio/stream/StreamSpec.scala (hunk 10 above)
Comment (iravid) [reply streams-tests/jvm/src/test/scala/zio/stream/StreamSpec.scala]: Fixed in Dotty, at least

Comment (jdegoes) [reply streams-tests/jvm/src/test/scala/zio/stream/StreamSpec.scala]: I think this case is beyond help. The covariance on `A` in `ZStream` is interacting with the invariance on `ZSink` to cause the problem, and we certainly don't want to eliminate covariance on `ZStream`
