### PR TITLE
Fix `ZStream.async` dropping elements on Scala Native

### LINKED ISSUE #9701: ZStream.async issue on scala-native
Hi. I noticed there might be some issues with `ZStream.async` on `scala-native`. 

```scala
//> using scala 3.3.5
//> using platform native
//> using nativeVersion 0.5.7
//> using dep "dev.zio::zio::2.1.16"
//> using dep "dev.zio::zio-streams::2.1.16"
//> using dep "io.github.cquiroz::scala-java-time::2.6.0"

import zio.*
import zio.stream.*

object Main extends ZIOAppDefault {

  val stream = ZStream.async { cb =>
    for (i <- 1 to 10) { cb(ZIO.succeed(Chunk.single(i))) }
    cb.end
  }

  def run = stream.runCount
    .tap(x => Console.printLine(x))
    .repeatN(10)
}

```

On jvm, this code always prints "10":
```
10
10
10
10
10
10
10
10
10
10
10
```
On scala-native, sometimes I'm getting values <10, for example:
```
8
9
10
9
10
9
10
9
8
10
10
```

### PR DESCRIPTION
**Pull request by Saturn225**
/claim #9701

This patch fixes a race in `ZStream.async` on Scala Native where the end marker could overtake pending chunk offers which causing some elements to be dropped. Rather than spawning a fiber for each chunk, we now enqueue each chunk synchronously `(.run(...))` before returning so that all 10 items are guaranteed to be in the queue before `cb.end`

 A new test is added that runs the same 10‐element stream 100 times to confirm no elements are ever lost

### CODE REVIEW

**Review by kyri-petrou — COMMENTED** [review]
LGTM, although given that we don't have to worry about binary incompatibility with Scala Native, I recommend changing the method signatures to replace Future[Boolean] with Unit so that we can keep the code consistent with the JVM variant

**Comment by Saturn225** [comment]
@kyri-petrou I have addressed the review comments. Could you please have another look when you get a chance?

File: managed/native/src/main/scala/zio/managed/ZManagedCompatPlatformSpecific.scala [hunk 1]
```diff
@@ -36,6 +36,13 @@ private[managed] trait ZManagedCompatPlatformSpecific {
       register: (ZIO[R, Option[E], Chunk[A]] => Future[Boolean]) => ZManaged[R, E, Any],
       outputBuffer: => Int = 16
     )(implicit trace: Trace): ZStream[R, E, A] =
-      ZStream.asyncScoped[R, E, A](register(_).scoped, outputBuffer)
+      ZStream.asyncScoped[R, E, A](
+        (callbackUnit: ZIO[R, Option[E], Chunk[A]] => Unit) =>
+          register { zioPull =>
+            callbackUnit(zioPull)
+            Future.successful(true)
```
Comment (kyri-petrou) [inline managed/native/src/main/scala/zio/managed/ZManagedCompatPlatformSpecific.scala]: I think we can change this to Unit as well no?

Comment (Saturn225) [reply managed/native/src/main/scala/zio/managed/ZManagedCompatPlatformSpecific.scala]: Yes we can change it

File: streams/native/src/main/scala/zio/stream/platform.scala [hunk 2]
```diff
@@ -60,7 +58,7 @@ private[stream] trait ZStreamPlatformSpecificConstructors {
    * be used to signal the end of the stream, by setting it to `None`.
    */
   def asyncInterrupt[R, E, A](
```
Comment (hearnadam) [inline streams/native/src/main/scala/zio/stream/platform.scala:60]: Is the code different in any meaningful way from the JVM version? if not, we should just aim to merge the traits.

I suspect most of the 'java specific' stream methods can now exist in Native due to increased coverage of Java library.

Comment (Saturn225) [reply streams/native/src/main/scala/zio/stream/platform.scala:60]: @hearnadam While many stream constructors now overlap, Native still lacks true NIO support maybe look some of them async sockets, piped streams, MessageDigest, classloader resources etc...  but the platform‐specific I/O methods must remain separate.

Comment (Saturn225) [reply streams/native/src/main/scala/zio/stream/platform.scala:60]: Ahh, given the platform differences, I think keeping them separate makes sense for now

**Comment by Saturn225** [comment]
@kyri-petrou Can this be merged now?

File: streams-tests/jvm-native/src/test/scala/zio/stream/ZStreamPlatformSpecific2Spec.scala [hunk 3]
```diff
@@ -111,6 +111,29 @@ object ZStreamPlatformSpecific2Spec extends ZIOBaseSpec {
...
+                i += 1
+              }
+              cb.end
+              ()
+            }
+
+          def countElements: UIO[Int] =
+            asyncTenStream.runCount.map(_.toInt)
+
+          val runs: UIO[IndexedSeq[Int]] = ZIO.foreach(1 to 100)(_ => countElements)
```
Comment (kyri-petrou) [inline streams-tests/jvm-native/src/test/scala/zio/stream/ZStreamPlatformSpecific2Spec.scala]: Just use `@ nonFlaky` instead of manually running it 100 times

**Comment by Saturn225** [comment]
@kyri-petrou Done!

**Review by kyri-petrou — APPROVED** [review]
Thanks!
