### PR TITLE
Eliminate all notions of scope errors from ZStream

### LINKED ISSUE #2234: ZStream scope error handling
Currently, `ZStream` is defined in terms of the `val process: ZManaged[R, E, Pull[R, E, A]]` method, which defines most streams as scoped effectful iterators.

There are some constructors that accept scoped resources, immediately try to enter the scope and build a stream inside it (`ZStream.unwrapManaged`, `ZStream.fromIteratorManaged`). Passing a `ZManaged.fail` to these constructors fails with an unhandled checked error.

There are also other constructors that don't assume anything and guard against failures that occur when entering the scope (`ZStream.fromEffect`, `ZStream.managed`). These constructors are safer, but currently produce a stream that will throw the scope entering failure when pulled. Honestly, I feel that this behavior is wrong, because the stream should not output the error, but rather, the stream should not even be constructed, because this error conceptually occurs before the stream even exists.

In that sense, the constructors that I mentioned first in this description are more correct, they don't allow the stream to be constructed.

Therefore, I would like to suggest the following. We should force the user to handle the scope errors before constructing the Stream, by requiring that any managed effect passed to a stream constructor has all checked errors handled (error type Nothing).

Further, this should be visible in the type signature of `val process: ZManaged[R, Nothing, Pull[R, E, A]]` and should be visible in the `managed`, `fromEffect`, `unwrapManaged` and other constructors as needed.

One caveat. This would probably change the signature of `bracket` to accept a non-failing `acquire` effect.

On the other hand, if this is not the direction that we wish to continue in, we should use this opportunity to define exactly how to unify these constructors and other stream combinators that accept a scoped pull somewhere in their implementation. This is very important for #1765.

@iravid

### PR DESCRIPTION
**Pull request by iravid**
Resolves #2234.

This changes the representation of `ZStream` from `ZManaged[R, E, Pull[R, E, A]]` to `ZManaged[R, Nothing, Pull[R, E, A]]`. It turns out that we don't actually need to represent failures on the scope level; the only thing we're using scopes for is finalizer management.

Incidentally, this also makes a bunch of operations lazier as they don't eagerly allocate ZManaged values but rather wait for them to be pulled.

With this out of the way, we can properly eliminate errors from a stream by handling element-level errors.

### CODE REVIEW

**Comment by iravid** [comment]
Big thanks to @vasilmkd for pushing us to think this through :-)

**Comment by iravid** [comment]
Also - @adamgfraser - the CanFail was super useful when refactoring this!

File: streams/shared/src/main/scala/zio/stream/StreamEffect.scala [hunk 1]
```diff
@@ -365,12 +365,10 @@ private[stream] object StreamEffect extends Serializable {
       }
     }
 
-  final def fromIterator[R, E, A](iterator: ZManaged[R, E, Iterator[A]]): StreamEffect[R, E, A] =
+  final def fromIterator[R, E, A](iterator: Iterator[A]): StreamEffect[R, E, A] =
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/StreamEffect.scala]: How can we make this to work for #2334?

Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/StreamEffect.scala]: I think we can't do this on StreamEffect right now, as it requires `unsafeRun`.

**Comment by vasilmkd** [comment]
Love to see team effort and orthogonal solutions coming together.

File: streams/shared/src/main/scala/zio/stream/StreamEffect.scala (hunk 1 above)
Comment (vasilmkd) [reply streams/shared/src/main/scala/zio/stream/StreamEffect.scala]: Ok, then let's simplify the function signature. `R = Any, E = Nothing`?

Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/StreamEffect.scala]: Oh yeah. Good catch.

**Comment by vasilmkd** [comment]
Also, it's nice to see my essays (like #2234) actually realized in code. :laughing:

File: streams/shared/src/main/scala/zio/stream/StreamEffect.scala [hunk 2]
```diff
@@ -365,12 +365,10 @@ private[stream] object StreamEffect extends Serializable {
       }
     }
 
-  final def fromIterator[R, E, A](iterator: ZManaged[R, E, Iterator[A]]): StreamEffect[R, E, A] =
+  final def fromIterator[A](iterator: Iterator[A]): StreamEffect[Any, Nothing, A] =
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/StreamEffect.scala]: Can we implement `StreamEffect.fromIterable` in terms of this (by calling `Iterable#iterator`?

File: streams/shared/src/main/scala/zio/stream/ZStream.scala [hunk 3]
```diff
@@ -581,7 +581,7 @@ class ZStream[-R, +E, +A] private[stream] (private[stream] val structure: ZStrea
   final def aggregateManaged[R1 <: R, E1 >: E, A1 >: A, B](
     managedSink: ZManaged[R1, E1, ZSink[R1, E1, A1, A1, B]]
   ): ZStream[R1, E1, B] =
-    ZStream[R1, E1, B] {
```
Comment (vasilmkd) [inline streams/shared/src/main/scala/zio/stream/ZStream.scala]: I know it's nitpicking but I really dislike these type hints...
