### PR TITLE
Indicate the true position of assertTrue arguments

### LINKED ISSUE #8362: Variadic assertTrue doesn't report which assertion failed
The `assertTrue` macro is great, but unfortunately the variadic version will only report that an assertion failed on the opening line, not which condition failed, which can make it pretty inconvenient. E.g., the below code will only report that an assertion failed on the line of the `assertTrue`:

```
  ...
  assertTrue(
    someCondition,
    someOtherCondition,
  )
```

There's now an inspection in the Zio IntelliJ plugin that recommends collapsing sequential `assertTrue` into a single call to the variadic version, which I think compounds this problem. I switched over my code, because it reads nicer, and didn't realize/think about this until some tests started failing.

### PR DESCRIPTION
**Pull request by joroKr21**
close #8362
/claim #8362

### CODE REVIEW

File: test/shared/src/main/scala-3/zio/test/Macros.scala [hunk 1]
```diff
@@ -239,26 +239,29 @@ object SmartAssertMacros {
...
+      case _ => (Nil, value)
+    }
 
-    val arrow = ast.asExprOf[TestArrow[Any, Boolean]]
-    '{TestResult($arrow.withCode(${Expr(code)}).withLocation($sourceLocation))}
+    given PositionContext = PositionContext(expr.asTerm)
+    val code = Expr(Macros.showExpr(expr))
+    val arrow = transform(expr).asExprOf[TestArrow[Any, Boolean]]
+    val pos = expr.asTerm.pos
+    val location = Expr(Some(s"${pos.sourceFile.path}:${pos.endLine + 1}"))
```
Comment (joroKr21) [inline test/shared/src/main/scala-3/zio/test/Macros.scala:253]: `endLine` is a bit arbitrary, but it seems to be what `SourceLocation` does

**Review by adamgfraser — APPROVED** [review]
