### PR TITLE
Fix #8924 make Tag and HasNoScope macros blackbox on Scala 3

### LINKED ISSUE #8924: Incorrect layer type when using a contravariant type parameter
The bug is reproduced on the following playground: https://scastie.scala-lang.org/kgWAa1cXQJ6Bk7YLo4NOhQ

There is the code:
```scala
import scala.Predef.{identity => id}
import zio._

object Module:
  opaque type AType[-I, -R, +E, +A] = I => ZIO[R, E, A]

  extension [A, B, C, D] (aType: AType[A, B, C, D])
    def toLayer(implicit tagA: Tag[A], tagB: Tag[B], tagC: Tag[C], tagD: Tag[D]): ULayer[AType[A, B, C, D]] =
      ZLayer.succeed[AType[A, B, C, D]](aType)
  
  def identity[I]: AType[I, Any, Nothing, I] = 
    id[I].andThen(ZIO.succeed(_))

  def service[I: Tag, R: Tag, E: Tag, A: Tag]: URIO[AType[I, R, E, A], AType[I, R, E, A]] = 
    ZIO.service[AType[I, R, E, A]]

import Module._

val intId = identity[Int]
val layer = intId.toLayer//(Tag[Int], Tag[Any], Tag[Nothing], Tag[Int])
val effect = service[Int, Any, Nothing, Int].as("voila!")

val runtime = Runtime.default
Unsafe.unsafe { unsafe =>
  given Unsafe = unsafe
  runtime.unsafe.run(effect.provide(layer)).getOrThrowFiberFailure()
}
```

As one can observe, the type of `intId` is `AType[Int, Any, Nothing, Int]`. But `intId.toLayer` gives a `ULayer[AType[Int, Any, Any, Int]]` instead of the expected `ULayer[AType[Int, Any, Nothing, Int]]`.

It seems that when resolving implicit parameters, when injecting an instance of `Tag` for `Nothing`, `Tag[Any]` is preferred over `Tag[Nothing]`. 

Uncomment the code at line 20 to force the injection of the correct tags and the problem is gone. Another way to hack around this bug is to remove the contravariant annotation on `E` as it forces the injection of the correct tag.

Going further, when replacing the `implicit` with `using`, the quick hack of bypassing injection doesn't even work.

### PR DESCRIPTION
**Pull request by neko-kai**
/claim #8924

Original example failure was caused by an upstream bug (just reported at https://github.com/scala/scala3/issues/24678)

But... there's no reason I can think of why `zio.Tag` (and HasNoScope) should be `transparent` (and trigger the upstream bug). Especially given that izumi.reflect.Tag, that zio.Tag defers to, is blackbox itself. Making it blackbox (just like its Scala 2 counterpart) fixes the issue AND avoids the bug AND speeds up compilation.

Actually, it could've been a historical accident since `izumi.reflect.Tag` was transparent initially and inspected trees some time before Scala 3.0 release 🤔

### CODE REVIEW

**Comment by neko-kai** [comment]
Hmm, getting the same dottydoc failure on two unrelated PRs https://github.com/zio/zio/actions/runs/19972494641/job/57280470027?pr=10274 (https://github.com/zio/zio/pull/10274) even though main branch is green 🤔 (does not reproduce locally either)

**Comment by hearnadam** [comment]
@neko-kai I think the dottydoc issue has to do with newer JDKs: https://github.com/scala/scala3/issues/24183#issuecomment-3528910384

File: core-tests/shared/src/test/scala-3/zio/BlackboxTagRegressionSpec.scala [hunk 1]
```diff
@@ -0,0 +1,41 @@
+package zio.managed
```
Comment (hearnadam) [inline core-tests/shared/src/test/scala-3/zio/BlackboxTagRegressionSpec.scala]: Why is this in the managed namespace?

File: core-tests/shared/src/test/scala-3/zio/BlackboxTagRegressionSpec.scala [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+
+import zio._
+import zio.test._
+
+object BlackboxTagRegressionSpec extends ZIOSpecDefault {
```
Comment (hearnadam) [inline core-tests/shared/src/test/scala-3/zio/BlackboxTagRegressionSpec.scala:6]: Is there a reason this is in its own test?

File: core-tests/shared/src/test/scala-3/zio/BlackboxTagRegressionSpec.scala [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+  override def spec: Spec[TestEnvironment with Scope, Any] =
+    suiteAll("BlackboxTagRegressionSpec") {
+      // https://github.com/zio/zio/issues/8924
+      // Reported upstream at https://github.com/scala/scala3/issues/24678
+      test("Issue #8924 example compiles as long as zio.Tag is a blackbox macro") {
+        val intId  = Module.identity[Int]
+        val layer  = intId.toLayer
+        val effect = Module.service[Int, Any, Nothing, Int].as("voila!")
+
+        val runtime = Runtime.default
```
Comment (hearnadam) [inline core-tests/shared/src/test/scala-3/zio/BlackboxTagRegressionSpec.scala]:
```suggestion
```
Unused?

File: core-tests/shared/src/test/scala-3/zio/BlackboxTagRegressionSpec.scala (hunk 1 above)
Comment (neko-kai) [reply core-tests/shared/src/test/scala-3/zio/BlackboxTagRegressionSpec.scala]: Fantastic question: I used `HasNoScopeSpec` as a template without noticing that the test packages in sources were all over the place and didn't match the directory. Fixed in https://github.com/zio/zio/pull/10273/commits/48ec83df871474e148f93a67fdef4f83dc3577c4

File: core-tests/shared/src/test/scala-3/zio/BlackboxTagRegressionSpec.scala (hunk 2 above)
Comment (neko-kai) [reply core-tests/shared/src/test/scala-3/zio/BlackboxTagRegressionSpec.scala:6]: Doesn't seem like there's a related Spec in core-tests/scala-3 I could stuff this test case into. The bug minimizes without Scala 3 syntax, but then it would somewhat lose the link to the original issue if it was rewritten. (and it's a Scala 3 only issue)

**Review by kyri-petrou — APPROVED** [review]
LGTM, thanks!
