### PR TITLE
Address a variety of ZSink combinator bugs and tests

### LINKED ISSUE #1312: Wrong behavior of Sink combinators
`collectAll`

```scala
private def collectAllStepError = {
  // This test needs to be verified for correctness.
  val sink = stepErrorSink.collectAll
  unsafeRun(sinkIteration(sink, 1).map(_ must_=== Nil))
}
```

> @iravid Yeah I think the implementation for Sink#collectAllWith is surprising. It stores the error in the first element of the tuple, but never uses it in extract; and if subsequent errors occur in a step, the previous errors are discarded. We should probably change it to fail eagerly in step.

```scala
private def collectAllWhileFalsePredicate = {
  // This test needs to be verified for correctness.
  // I find this behavior to be surprising.
  val sink = ZSink.identity[Int].collectAllWhile[Int, Int](_ < 0)
  unsafeRun(sinkIteration(sink, 1).either.map(_ must_=== Left(())))
  // Fails instead of returning empty list.
  // I would presume that sinkIteration(sink, 1).map(_ must_=== Nil) is the correct behavior.
}
```
> @iravid The implementation of collectAllWhile looks right - it tries to extract the underlying sink if an element that doesn't match the predicate is stepped.

The problem is with ZSink.identity, however; that one fails with Unit if an element never passed through the sink. Maybe test it with a different sink?

`untilOutput`

```scala
private def untilOutputHappyPath = {
  // This test needs to be verified for correctness.
  val sink = ZSink.identity[Int].untilOutput(_ % 2 == 0)
  unsafeRun(sinkIteration(sink, 1).map(_ must_=== 1))
}
```
> @iravid The logic in untilOutput's step looks backwards. should be `if (!Step.done(s))` ...

```scala
private def untilOutputFalsePredicate = {
  // This test needs to be verified for correctness.
  val sink = ZSink.identity[Int].untilOutput(_ % 2 != 0)
  unsafeRun(sinkIteration(sink, 1).map(_ must_=== 1))
}
```
> @iravid Yes, it's surprising too. Extracting that should probably result in an error (or a `None` which means the output should be `Option[B]`).

### PR DESCRIPTION
**Pull request by vasilmkd**
Resolves #1312. Finally.

Also improves test coverage.

@iravid Please take a look when you have time.

### CODE REVIEW

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 1]
```diff
@@ -188,17 +190,13 @@ trait ZSink[-R, +E, +A0, -A, +B] { self =>
                 self.initial.flatMap { init =>
                   self
                     .stepChunk(Step.state(init), as.map(ev))
-                    .fold(
-                      e => Step.done((Some(e), f(state._2, b), Step.state(init)), Chunk.empty),
-                      s => Step.leftMap(s)((state._1, f(state._2, b), _))
-                    )
+                    .map(Step.leftMap(_)((f(state._1, b), _)))
```
Comment (iravid) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: Nice. I noticed that swallowed error too :-)

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 2]
```diff
@@ -838,24 +867,28 @@ trait ZSink[-R, +E, +A0, -A, +B] { self =>
    * Creates a sink that produces values until one verifies
    * the predicate `f`.
    */
-  final def untilOutput(f: B => Boolean): ZSink[R, E, A0, A, B] =
-    new ZSink[R, E, A0, A, B] {
-      type State = self.State
+  final def untilOutput(f: B => Boolean): ZSink[R, Option[E], A0, A, B] =
```
Comment (iravid) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala]: Could you clarify why `Option[E]` is needed?

File: streams/shared/src/main/scala/zio/stream/ZSink.scala (hunk 1 above)
Comment (vasilmkd) [reply streams/shared/src/main/scala/zio/stream/ZSink.scala]: It's now in line with `collectAllWhile`, so that's something. I'm happy.

File: streams/shared/src/main/scala/zio/stream/ZSink.scala (hunk 2 above)
Comment (vasilmkd) [reply streams/shared/src/main/scala/zio/stream/ZSink.scala]: Fixed after discussion in DM.

**Comment by vasilmkd** [comment]
@iravid Ready for review.
