### PR TITLE
Spec layer initialization defects

### LINKED ISSUE #7141: Test initialization failure do not reported to sbt
If test failed to initialise it did not reported to `sbt.testing.EventHandler` and overall test run treated as success.

I made sample project:
https://github.com/darl/zio2-example/blob/main/src/test/scala/dev/zio/quickstart/MainSpec.scala

```bash
$ sbt test && echo 'success' || echo 'failed'
[info] welcome to sbt 1.7.1 (Homebrew Java 11.0.15)
[info] loading global plugins from /Users/darl/.sbt/1.0/plugins
[info] loading settings for project zio-quickstart-hello-world-build-build from metals.sbt ...
[info] loading project definition from /Users/darl/projects/zio-quickstart-hello-world/project/project
[info] loading settings for project zio-quickstart-hello-world-build from metals.sbt ...
[info] loading project definition from /Users/darl/projects/zio-quickstart-hello-world/project
[success] Generated .bloop/zio-quickstart-hello-world-build.json
[success] Total time: 0 s, completed Jul 28, 2022, 10:42:23 PM
[info] loading settings for project zio-quickstart-hello-world from build.sbt ...
[info] set current project to zio-quickstart-hello-world (in build file:/Users/darl/projects/zio-quickstart-hello-world/)
+ Main
    - sampleTest
      Exception in thread "zio-fiber-48" java.lang.RuntimeException: boom
      	at dev.zio.quickstart.MainSpec$.$init$$$anonfun$1(MainSpec.scala:9)
      	at dev.zio.quickstart.MainSpec$.intLayer.macro(MainSpec.scala:9)
      	at dev.zio.quickstart.MainSpec$.spec.macro(MainSpec.scala:11)
      	at dev.zio.quickstart.MainSpec$.spec.macro(MainSpec.scala:11)
      	at dev.zio.quickstart.MainSpec$.spec.macro(MainSpec.scala:11)
      	at dev.zio.quickstart.MainSpec$.spec.macro(MainSpec.scala:11)
      	at dev.zio.quickstart.MainSpec$.spec.macro(MainSpec.scala:11)
      	at dev.zio.quickstart.MainSpec$.spec.macro(MainSpec.scala:11)
[info] No tests were executed
[success] Total time: 2 s, completed Jul 28, 2022, 10:42:24 PM
success
```

### PR DESCRIPTION
**Pull request by swoogles**
Fixes #7141 

Also de-dup some of the `ExecutionEvent` processing by adding a small helper in `TestExecutor`

Before, falsely reporting success to SBT:
Screen Shot 2022-07-28 at 4 11 31 PM

After, correctly reporting failure to SBT:
Screen Shot 2022-07-28 at 4 12 07 PM

### CODE REVIEW

File: test-sbt/shared/src/main/scala/zio/test/sbt/ZTestEventHandlerSbt.scala [hunk 1]
```diff
@@ -1,17 +1,40 @@
...
+ */
 class ZTestEventHandlerSbt(eventHandler: EventHandler, taskDef: TaskDef) extends ZTestEventHandler {
   def handle(event: ExecutionEvent): UIO[Unit] =
     event match {
       case evt @ ExecutionEvent.Test(_, _, _, _, _, _) =>
         ZIO.succeed(eventHandler.handle(ZTestEvent.convertEvent(evt, taskDef)))
-      case ExecutionEvent.SectionStart(_, _, _)      => ZIO.unit
-      case ExecutionEvent.SectionEnd(_, _, _)        => ZIO.unit
-      case ExecutionEvent.TopLevelFlush(_)           => ZIO.unit
-      case ExecutionEvent.RuntimeFailure(_, _, _, _) => ZIO.unit
```
Comment (swoogles) [inline test-sbt/shared/src/main/scala/zio/test/sbt/ZTestEventHandlerSbt.scala:15]: Surprise surprise, invoking `ZIO.unit` in the vent of a `RuntimeFailure` _won't_ give SBT any useful info. Who would've thought?

**Review by adamgfraser — APPROVED** [review]
