### PR TITLE
Fix flaky test

### LINKED ISSUE #2096: Flaky ZIO ForkAll Test
```scala
[info] ZIO Test
[info] - ZIO
[info]   - forkAll
[info]     - propagates defects
```

https://circleci.com/gh/zio/zio/36839?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### PR DESCRIPTION
**Pull request by mlangc**
`ZIO.forkAll`, when being executed with `List(ZIO.dieNow(boom))` will
internally execute `nilIO.zipWithPar(boomIO)((as, a) => a :: as)`, where
`nilIO` is a simple ZIO value that results in `Nil`, and `boomIO` a
simple ZIO value that results in `ZIO.dieNow(boom)`. In rare cases,
`boomIO` completes before `nilIO` and then interrupts `nilIO`. The
result of the test is then not just a `Die`, but also an interruption.

Fixes #2096

### CODE REVIEW

**Comment by adamgfraser** [comment]
@mlangc Excellent analysis of the situation.

It seems counterintuitive that you could get an interruption exception by forking a single effect. I wonder if we need to change the logic in `forkAll` to address this. If the list of effects is empty we can just immediately return an empty list. If it is non-empty we can fork and combine those fibers.

What do you think?

File: core/shared/src/main/scala/zio/ZIO.scala [hunk 1]
```diff
@@ -2604,11 +2604,22 @@ object ZIO extends ZIOCompanionPlatformSpecific {
    * composite fiber that produces a list of their results, in order.
    */
   def forkAll[R, E, A](as: Iterable[ZIO[R, E, A]]): URIO[R, Fiber.Synthetic[E, List[A]]] =
-    as.foldRight[URIO[R, Fiber.Synthetic[E, List[A]]]](succeedNow(Fiber.succeed(Nil))) { (aIO, asFiberIO) =>
-      asFiberIO.zipWith(aIO.fork) {
-        case (asFiber, aFiber) =>
-          asFiber.zipWith(aFiber)((as, a) => a :: as)
-      }
+    as.toList match {
```
Comment (adamgfraser) [inline core/shared/src/main/scala/zio/ZIO.scala]: Can we use `as.reduceRightOption(???).getOrElse(ZIO.succeedNow(Fiber.succeed(Nil)))` to clean this up?

Comment (mlangc) [reply core/shared/src/main/scala/zio/ZIO.scala]: I've just refactored the code as you proposed.

Comment (adamgfraser) [reply core/shared/src/main/scala/zio/ZIO.scala]: Looks great!
