### PR TITLE
Render StackTrace.none as such

### LINKED ISSUE #10302: StackTrace.none.toString is confusing
```
assertTrue(zio.StackTrace.none.toString == "Stack trace for thread \"zio-fiber-\":\n")
```

We should just print `StackTrace.None`

### PR DESCRIPTION
**Pull request by hearnadam**
/fixes https://github.com/zio/zio/issues/10302

This prevents `Cause.fail`/`Exit.fail` as:

```scala
Fail(value,Stack trace for thread "zio-fiber-":)
```

Instead:
```scala
Fail(value,StackTrace.none)
```

### CODE REVIEW

File: core/shared/src/main/scala/zio/StackTrace.scala [hunk 1]
```diff
@@ -57,7 +57,8 @@ final case class StackTrace(
   }
 
   override def toString(): String =
-    prettyPrint("Stack trace for thread \"" + fiberId.threadName + "\":")
+    if (isEmpty) "StackTrace.none"
```
Comment (guizmaii) [inline core/shared/src/main/scala/zio/StackTrace.scala:60]: Can you add a test maybe, please?

Comment (hearnadam) [reply core/shared/src/main/scala/zio/StackTrace.scala:60]: Added a case to `CauseSpec`

**Review by kyri-petrou — APPROVED** [review]
