### PR TITLE
Extend causes in the Exit.getOrThrow* methods with stack traces

### LINKED ISSUE #9025: FiberFailure doesn't fill its stacktrace
The following scala `App` throws. The printed stacktrace starts at the `subcall()` method. I expected it to capture the full trace including `cal()` and `Test.main()`. I'm integrating zio gradually in my code base and am using `unsafeRunSync` here and there. Important parts of stacktraces are missing. I wonder if this is on purpose or if it's an oversight.

```scala
import zio.{Runtime, Unsafe, ZIO}

object Test extends App {
  def call(): Unit = subcall()
  def subcall(): Unit =
    Unsafe.unsafe { implicit unsafe =>
      Runtime.default.unsafe.run(subcall2()).getOrThrowFiberFailure()
    }
  def subcall2() = ZIO.fail("boom")
  call()
}
```
```
Exception in thread "main" Exception in thread "zio-fiber-1239886032" java.lang.String: boom
	at <empty>.Test.subcall2(Test.scala:9)
	at <empty>.Test.subcall(Test.scala:7)
```

### PR DESCRIPTION
**Pull request by joroKr21**
fixes #9025
/claim #9025

The idea is that most users call those methods in interop code
and since they are leaving the ZIO runtime, they need a stack trace.

Also override `printStackTrace` in `FiberFailure` by delegating
to a new `Cause.prettyPrintWith` method which allows for a custom
`println` function. This is necessary because the original method
uses the private `stackTrace` field, not `getStackTrace`.

Updated `Cause` to remove the "Exception in thread" part as this
shouldn't be part of the exception `toString`, it's added later and
was causing it to be printed twice.

Last thing to node is that I didn't change `FiberFailure.toString`
for caution of breaking user code but it's not in line with Java
exceptions, which don't include the stack trace in their `toString`.

### CODE REVIEW

**Comment by kyri-petrou** [comment]
I'll do a more in-depth review of this PR later this week, but in the meantime I think we need to make testing around this a bit more robust. See my comments on #9073, particularly [this](https://github.com/zio/zio/pull/9073#discussion_r1712961292) and [this](https://github.com/zio/zio/pull/9073#discussion_r1712961129) comment

**Comment by joroKr21** [comment]
@kyri-petrou stack traces are different on:
- different Scala versions (because of name mangling)
- different platforms (JVM, JS, Native due to obvious reasons)

**Comment by joroKr21** [comment]
We could use this at $work. Anything missing?

File: streams/shared/src/main/scala/zio/stream/ZStream.scala [hunk 1]
```diff
@@ -3498,24 +3498,10 @@ final class ZStream[-R, +E, +A] private (val channel: ZChannel[R, Any, Any, Any,
    * Converts this stream into a `scala.collection.Iterator` wrapped in a scoped
    * [[ZIO]]. The returned iterator will only be valid within the scope.
    */
-  def toIterator(implicit trace: Trace): ZIO[R with Scope, Nothing, Iterator[Either[E, A]]] =
```
Comment (kyri-petrou) [inline streams/shared/src/main/scala/zio/stream/ZStream.scala:3526]: Out of curiosity, why was this change (and the other stream ones) needed?

File: core/shared/src/main/scala/zio/ZIO.scala [hunk 2]
```diff
@@ -6378,6 +6378,21 @@ object ZIO extends ZIOCompanionPlatformSpecific with ZIOCompanionVersionSpecific
...
+    runtime.unsafe.run(pull) match {
+      case Exit.Success(value) =>
+        Iterator.single(value) ++ unfoldPull(runtime, pull)
+      case Exit.Failure(cause) =>
+        cause.failureOrCause match {
+          case Left(None)    => Iterator.empty
+          case Left(Some(e)) => Exit.fail(e).getOrThrow()
+          case Right(c)      => Exit.failCause(c).getOrThrowFiberFailure()
+        }
+    }
```
Comment (kyri-petrou) [inline core/shared/src/main/scala/zio/ZIO.scala]: This is only used in streams, if you still need it I would move it to that package and make it `private[stream]`

File: core/shared/src/main/scala/zio/Cause.scala [hunk 3]
```diff
@@ -497,35 +498,38 @@ sealed abstract class Cause[+E] extends Product with Serializable { self =>
...
-    import Cause.Unified
+    val builder = new StringBuilder
+    prettyPrintWith(builder.append(_).append('\n'))(Unsafe.unsafe)
+    builder.result()
+  }
 
-    val builder = ChunkBuilder.make[String]()
-    var size    = 0
+  /** Pretty-prints this cause with the provided `println` function. */
+  final def prettyPrintWith(println: String => Unit)(implicit unsafe: Unsafe): Unit = {
```
Comment (kyri-petrou) [inline core/shared/src/main/scala/zio/Cause.scala]: Could we change the argument name to something different? Calling `println` looks very wrong

**Review by kyri-petrou — COMMENTED** [review]
Sorry for taking this long to review this.

I think it looks good, the only issue is that I'm not sure whether the stream changes are needed as part of this PR

File: streams/shared/src/main/scala/zio/stream/ZStream.scala (hunk 1 above)
Comment (joroKr21) [reply streams/shared/src/main/scala/zio/stream/ZStream.scala:3526]: Because they were throwing a `FiberFailure`

File: core/shared/src/main/scala/zio/ZIO.scala (hunk 2 above)
Comment (joroKr21) [reply core/shared/src/main/scala/zio/ZIO.scala]: Good idea 👍

File: streams/shared/src/main/scala/zio/stream/ZStream.scala [hunk 4]
```diff
@@ -3523,24 +3523,10 @@ final class ZStream[-R, +E, +A] private (val channel: ZChannel[R, Any, Any, Any,
...
-              case Right(c)      => throw FiberFailure(c)
-            }
-        }
-
-      unfoldPull
-    }
+  def toIterator(implicit trace: Trace): ZIO[R with Scope, Nothing, Iterator[Either[E, A]]] = for {
+    runtime <- ZIO.runtime[R]
+    pull    <- either.toPull
+  } yield unfoldPull(runtime, pull)(trace, Unsafe.unsafe).flatten
```
Comment (kyri-petrou) [inline streams/shared/src/main/scala/zio/stream/ZStream.scala:3529]: I have a feeling that this will destroy chunking, or at the very least cause each element of the stream to be evaluated in a new call to `runtime.unsafe.run`. This will be very expensive as each time we'd need to create a new Fiber to evaluate it. If we can't reuse `unfoldPull` I'd say it's probably better to specialize this implementation instead

File: core-tests/shared/src/test/scala/zio/StackTracesSpec.scala [hunk 5]
```diff
@@ -84,54 +96,229 @@ object StackTracesSpec extends ZIOBaseSpec {
...
+                |	at zio.StackTracesSpec.spec
+                |""".stripMargin
+            else
+              """java.util.NoSuchElementException: head of empty list
+                |	at scala.collection.immutable.Nil$.head
+                |	at zio.StackTracesSpec$.$anonfun
+                |	at zio.ZIO.map$$anonfun
+                |	at zio.StackTracesSpec.spec.underlyingFailure
+                |	at zio.StackTracesSpec.spec
+                |""".stripMargin
```
Comment (kyri-petrou) [inline core-tests/shared/src/test/scala/zio/StackTracesSpec.scala:133]: These 2 stack traces look the same to me, or did I miss some difference between them?

**Review by kyri-petrou — COMMENTED** [review]
Missed something in the previous round, but otherwise looks good to me!

File: core-tests/shared/src/test/scala/zio/StackTracesSpec.scala (hunk 5 above)
Comment (joroKr21) [reply core-tests/shared/src/test/scala/zio/StackTracesSpec.scala:133]: `zio.ZIO.$anonfun$map` vs `zio.ZIO.map$$anonfun` 😄

File: streams/shared/src/main/scala/zio/stream/ZStream.scala (hunk 4 above)
Comment (joroKr21) [reply streams/shared/src/main/scala/zio/stream/ZStream.scala:3529]: `pull` returns a `Chunk`, that's why we call `.flatten`

Comment (kyri-petrou) [reply streams/shared/src/main/scala/zio/stream/ZStream.scala:3529]: Aghh I see

**Review by kyri-petrou — APPROVED** [review]
