### PR TITLE
Provide environment to stream finalizers

### LINKED ISSUE #9829: ZStream finalizer in the wrong environment
```scala
import zio._
import zio.stream._

object Test extends ZIOAppDefault {

  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] =
    ZStream
      .environment[String]
      .tap(env => ZIO.log(env.toString))
      .ensuring(ZIO.environment[String].tap(env => ZIO.log(env.toString)))
      .provideEnvironment(ZEnvironment("kek"))
      .runDrain
}
```

```
timestamp=2025-04-29T06:09:20.085609Z level=INFO thread=#zio-fiber-1040644215 message="ZEnvironment(String -> kek)" location=Test.run file=Test.scala line=11
timestamp=2025-04-29T06:09:20.105389Z level=INFO thread=#zio-fiber-1040644215 message="ZEnvironment(Scope -> zio.Scope$unsafe$CloseableScope@67c9b483, ZIOAppArgs -> ZIOAppArgs(Chunk()))" location=Test.run file=Test.scala line=12
```

### PR DESCRIPTION
**Pull request by joroKr21**
Closes #9829

😭

### CODE REVIEW

File: streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala [hunk 1]
```diff
@@ -451,7 +451,7 @@ private[zio] final class ChannelExecutor[Env, InErr, InElem, InDone, OutErr, Out
     if (finalizers.isEmpty) null
     else
       ZIO
-        .foreach(finalizers)(_.apply(ex).exit)
+        .foreach(finalizers)(fin => provide(fin.apply(ex).exit))
```
Comment (kyri-petrou) [inline streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala]: I think this will work too right? It'll be more performant because we're providing the environment just once in case there are multiple finalizers

```scala
      provide(ZIO.foreach(finalizers)(_.apply(ex).exit))
        .map(results => Exit.collectAll(results) getOrElse Exit.unit)
        .unexit
```

Comment (joroKr21) [reply streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala]: I guess

**Review by kyri-petrou — APPROVED** [review]
Thanks! So weird that this has gone unnoticed for so long 😢

**Comment by joroKr21** [comment]
Do we publish snapshots?

**Comment by joroKr21** [comment]
Somehow using a snapshot doesn't help. Can we release this?

**Comment by kyri-petrou** [comment]
Hmm have you made sure to use the snapshot version for `zio-stream` as well?

**Comment by joroKr21** [comment]
Oh, I forgot they are separate dependencies...
