### PR TITLE
Fix ZPool finalizers not running when resource acquisition fails or is interrupted

### LINKED ISSUE #9152: ZPool leaks resources when acquisition is interrupted
I've been debugging a [CI failure in ZIO HTTP](https://github.com/zio/zio-http/actions/runs/10610450982/job/29407956295#step:9:4911) involving a flaky test, and I managed to trace this issue down to ZPool not releasing resources on scoped workflows when the resource acquisition is interrupted. Reproducer:

```scala
import zio.*

object Foo extends ZIOAppDefault {
  val counter = Ref.unsafe.make(0)(Unsafe)

  val incCounter = ZIO.acquireRelease(counter.update(_ + 1))(_ => counter.update(_ - 1))

  def run = ZIO.scoped(
    for {
      pool <- ZPool.make(incCounter *> ZIO.sleep(2.seconds), 0 to 100, 10.seconds)
      f    <- ZIO.scoped(pool.get).fork
      _    <- ZIO.sleep(1.second)
      _    <- f.interrupt
      _    <- f.await.ignore
    } yield ()
  ) *> counter.get.debug("count")
}
```

I expect `count: 0` to be printed in the console, however `count: 1` is printed instead.

Note that this is causing connections to be leaked in ZIO HTTP's Client in cases that the request is interrupted while we're acquiring a connection to the server.

cc @987Nabil

EDIT: This seems worse than I thought; if the acquisition fails, then the resource does not even become part of the pool, which means it'll stay alive totally unmanaged

### PR DESCRIPTION
**Pull request by kyri-petrou**
/fixes #9152
/claim #9152

The previous behaviour would run the finalizers within an interruptible region in case of a failure. This means that in cases where the acquisition would be interrupted after some resource was first initialized (either due to interruption or failure) the finalizers wouldn't be run and the pool would contain invalid items.

/cc @987Nabil this should fix the flaky test in ZIO HTTP, but I'll test it more extensively once there's a snapshot version out

### CODE REVIEW

File: core-tests/shared/src/test/scala/zio/ZPoolSpec.scala [hunk 1]
```diff
@@ -157,14 +157,35 @@ object ZPoolSpec extends ZIOBaseSpec {
...
             interruptible <- pool.get
           } yield assertTrue(interruptible)
-        }
-    }
+        } @@ exceptJS(nonFlaky) +
+        test("doesn't leak resources when acquisition is interrupted") {
+          for {
+            latch     <- Promise.make[Nothing, Unit]
+            latch2    <- Promise.make[Nothing, Unit]
+            incCounter = ZIO.acquireRelease(ZIO.unit)(_ => latch2.succeed(()))
```
Comment (kyri-petrou) [inline core-tests/shared/src/test/scala/zio/ZPoolSpec.scala:173]: Note: We can't use a counter in this test because the interruption is "disconnected", so we need to use a promise and await it to check whether it's been completed

**Review by jdegoes — APPROVED** [review]

**Comment by kyri-petrou** [comment]
@jdegoes PS: I noticed some test flakiness; I looked into it and it doesn't seem to be related to the changes to the library code but to the addition of the `nonFlaky` annotation. I have a fix for it but I'll do it in a followup PR since it's unrelated to this one
