### PR TITLE
Fix Flaky ZManaged#withEarlyRelease Test

### LINKED ISSUE #1747: ZManaged#withEarlyRelease test is flaky
```
[info]   - withEarlyRelease
[info]     + Provides a canceler that can be used to eagerly evaluate the finalizer
[info]     - The canceler should run uninterruptibly
[info]       Right(Some(Success(()))) did not satisfy isRight(isNone())
[info]       Some(Success(())) did not satisfy isNone()
```

@adamgfraser could you take a look?

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #1747.

### CODE REVIEW

File: core/shared/src/main/scala/zio/ZManaged.scala [hunk 1]
```diff
@@ -670,15 +670,15 @@ final case class ZManaged[-R, +E, +A](reserve: ZIO[R, E, Reservation[R, E, A]])
...
+  final def withEarlyRelease: ZManaged[R, E, (URIO[R, Any], A)] =
     withEarlyReleaseExit(Exit.interrupt)
 
   /**
    * A more powerful version of `withEarlyRelease` that allows specifying an
    * exit value in the event of early release.
    */
-  final def withEarlyReleaseExit(exit: Exit[_, _]): ZManaged[R, E, (URIO[R, _], A)] =
-    ZManaged[R, E, (URIO[R, _], A)] {
+  final def withEarlyReleaseExit(exit: Exit[Any, Any]): ZManaged[R, E, (URIO[R, Any], A)] =
```
Comment (LGLO) [inline core/shared/src/main/scala/zio/ZManaged.scala]: Is this because of Scala 3?

File: core-tests/shared/src/test/scala/zio/ZManagedSpec.scala [hunk 2]
```diff
@@ -670,8 +670,8 @@ object ZManagedSpec
                            for {
                              fiber        <- canceler.fork
                              _            <- latch.await
+                             interruption <- withLive(fiber.interrupt)(_.timeout(5.seconds)).either
```
Comment (LGLO) [inline core-tests/shared/src/test/scala/zio/ZManagedSpec.scala]: What is semantic change here?
Before `fiber.interrupt` was running with `Clock.Live` and now only `.timeout` is running with it?
How does it help with flakiness?

File: core/shared/src/main/scala/zio/ZManaged.scala (hunk 1 above)
Comment (adamgfraser) [reply core/shared/src/main/scala/zio/ZManaged.scala]: Yes, just trying to implement #1759 and at least not add any more existential types.

File: core-tests/shared/src/test/scala/zio/ZManagedSpec.scala (hunk 2 above)
Comment (adamgfraser) [reply core-tests/shared/src/test/scala/zio/ZManagedSpec.scala]: No, you're totally fine. Changing `provide(Clock.Live)` to `withLive` doesn't have any semantic effect, it is just trying to clean up the code a little.

The semantically significant change is moving the `ref.set(false)` effect to after the interruption. I am using the `Ref` so that the cancelation action is non-terminating and we can check that it is uninterruptible. But since it never terminates the finalizer will still run at the end of the `Managed`, and we want that to terminate so that we don't hang. The problem is that created a race condition, because if the `Ref` is set to `false` before the forked canceler checks the `whenM` condition the canceler will become terminating and our test will fail, causing the flakiness. We fix that by moving the effect to set the Ref to after we have checked if we can interrupt the canceler.

Does that make sense?

Comment (LGLO) [reply core-tests/shared/src/test/scala/zio/ZManagedSpec.scala]: Yes, it does!
I think the `.either` doesn't bring any value, E is Nothing here and `.either` doesn't help with defects.

**Comment by adamgfraser** [comment]
Let me make one change before merging please.

**Comment by ghostdogpr** [comment]
@adamgfraser sorry I merged it right before I saw this :/

**Comment by adamgfraser** [comment]
@ghostdogpr No problem. Sorry, was just going to remove the `either` call as @LGLO suggested but don't think it is worth changing at this point.
