### PR TITLE
Use reflection to install system signal handlers in JVM applications

### LINKED ISSUE #9240: Dependency on sun.misc.SignalHandler causing NoClassDefFoundError
I notice that ZIO [uses](https://github.com/zio/zio/blob/6362961efb3fe0af160b6b5e76b2a3014531825d/core/jvm/src/main/scala/zio/internal/PlatformSpecific.scala#L43) the deprecated `sun.misc.SignalHandler`:
```
  final def addSignalHandler(signal: String, action: () => Unit)(implicit unsafe: zio.Unsafe): Unit = {
    import sun.misc.Signal
    import sun.misc.SignalHandler
```

I'm building a plugin (written in ZIO) that conforms to the [Smithy](https://smithy.io/2.0/guides/smithy-build-json.html) plugin SPI, but when it's loaded by a Java 17 JVM and executed, it crashes:
```
Projection api-gw-transformer failed: java.lang.NoClassDefFoundError: sun/misc/SignalHandler
java.lang.NoClassDefFoundError: sun/misc/SignalHandler
	at zio.VersionSpecific.$init$(VersionSpecific.scala:78)
	at zio.package$.<clinit>(package.scala:24)
	at zio.ZLogger$.<clinit>(ZLogger.scala:108)
	at zio.RuntimePlatformSpecific.$init$(RuntimePlatformSpecific.scala:35)
	at zio.Runtime$.<clinit>(Runtime.scala:213)
```

The stack trace doesn't match, but I'm pretty sure the above code in `PlatformSpecific` is the problem.

All my plugin code does for now is:
```
    zio.Unsafe.unsafe { implicit u =>
      zio.Runtime.default.unsafe.run(ZIO.log("Test")).getOrThrowFiberFailure()
    }
```

I've even tried building with nearly the exact same version of Java (Corretto-17.0.12, whereas Smithy uses Corretto-17.0.12.7.1).

### PR DESCRIPTION
**Pull request by kyri-petrou**
/fixes #9240

_NOTE: This approach is a port of the `cats-effect` approach when installing system signal handlers._

In short, we use runtime reflection and a proxy class in order to avoid crashing the application with `NoClassDefFoundError` in cases that the JVM doesn't contain the `sun.misc.Signal` and `sun.misc.SignalHandler` classes. It also adds config to include these classes when compiling the code using GraalVM's native image.

I added a comment / question below, please let me know what you think

### CODE REVIEW

File: core/jvm/src/main/java/zio/internal/Signal.java [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+        final Class<?> signalHandlerClass = findClass("sun.misc.SignalHandler");
+
+        if ((signalClass != null) && (signalHandlerClass != null)) {
+            final MethodHandles.Lookup lookup = MethodHandles.lookup();
+
+            SIGNAL_CONSTRUCTOR_METHOD_HANDLE = initSignalConstructorMethodHandle(lookup, signalClass);
+            HANDLE_STATIC_METHOD_HANDLE = initHandleStaticMethodHandle(lookup, signalClass, signalHandlerClass);
+            SIGNAL_HANDLER = new SignalHandler.SunMiscSignalHandler(signalHandlerClass);
+        } else {
+            System.err.println("WARNING: sun.misc.Signal and sun.misc.SignalHandler are not available on this platform. " +
```
Comment (kyri-petrou) [inline core/jvm/src/main/java/zio/internal/Signal.java]: Couple of questions here:

1. Should we use a logger instead of `System.err.println`?
2. Should we add _some_ option to disable this warning? Might be annoying in some cases, but I think as a default a user should be aware that the fiber dump functionality won't work as expected

Comment (hearnadam) [reply core/jvm/src/main/java/zio/internal/Signal.java]: `java.logging `?

Comment (kyri-petrou) [reply core/jvm/src/main/java/zio/internal/Signal.java]: Thanks for the recommendation! I switched to using `java.logging` to log the warning and changed the code to make it a bit more readable / safe so that we log the warning if any of the reflective methods fail

File: core/jvm/src/main/java/zio/internal/Signal.java [hunk 2]
```diff
@@ -0,0 +1,151 @@
...
+                        Signal.class.getClassLoader(),
+                        new Class<?>[]{signalHandlerClass},
+                        invocationHandler
+                );
+                try {
+                    final Object s = constuctorMethodHandle.invoke(signal);
+                    staticMethodHandle.invoke(s, proxy);
+                } catch (Throwable err) {
+                    // Gracefully degrade to a no-op logging the exception.
+                }
```
Comment (hearnadam) [inline core/jvm/src/main/java/zio/internal/Signal.java]: Is it safe to catch all `Throwable`?

Also, is there a reason to use `Throwable` here and `Exception` above?

File: core/jvm/src/main/java/zio/internal/Signal.java [hunk 3]
```diff
@@ -0,0 +1,151 @@
...
+ * This class is used to handle system signals in a platform-specific way. It attemps to use the
+ * sun.misc.Signal and sun.misc.SignalHandler classes if they are available. If they are not
+ * available, it will gracefully degrade to a no-op.
+ * <p>
+ * <b>IMPLEMENTATION NOTE</b>: This class uses reflection to access the sun.misc.Signal and sun.misc.SignalHandler.
+ * This is necessary because the sun.misc.Signal and sun.misc.SignalHandler classes might not be available in some
+ * JVMs.
+ * </p>
+ */
+final class Signal {
```
Comment (hearnadam) [inline core/jvm/src/main/java/zio/internal/Signal.java]: Is there a reason to write this in java?

**Review by hearnadam — APPROVED** [review]

File: core/jvm/src/main/java/zio/internal/Signal.java (hunk 3 above)
Comment (kyri-petrou) [reply core/jvm/src/main/java/zio/internal/Signal.java]: Actually, not really. I'm not really sure why I thought we'd need Java for this. I rewrote the implementation in Scala

File: core/jvm/src/main/java/zio/internal/Signal.java (hunk 2 above)
Comment (kyri-petrou) [reply core/jvm/src/main/java/zio/internal/Signal.java]: It's mostly because the `invoke` method can throw any Throwable (depending on the underlying method) whereas the method above only throw exceptions. I think it's relatively safe to catch all Throwable's here because I don't think we want to crash the application in the very unlikely edge-case that we failed to handle a signal

**Review by ghostdogpr — APPROVED** [review]
