### PR TITLE
Use Comma For Default Sequence Delimiter In ConfigProvider.envProvider

### LINKED ISSUE #7614: zio.Config: Problem loading env vars
After migrating a project from 2.0.3 to 2.0.5 and adopt `zio.Config`, the app started crashing, not finding the env vars:
```
timestamp=2022-12-08T15:53:50.189983Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" zio.Config$Error$And: ((Missing data at ENV_A: Expected ENV_A to be set in properties) and (Missing data at ENV_B: Expected ENV_B to be set in properties))
        at example.Main.run(Main.scala:9)"
```
[Reproducible example here](https://github.com/juliano/zconfig-issue)

It seems to me it's related to having an url among the variables, if I change it to something else it works.

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #7614.

### CODE REVIEW

File: core/shared/src/main/scala/zio/ConfigProvider.scala [hunk 1]
```diff
@@ -154,7 +154,7 @@ object ConfigProvider {
             ZIO
               .fromOption(valueOpt)
               .mapError(_ => Config.Error.MissingData(path, s"Expected ${pathString} to be set in the environment"))
-          results <- Flat.util.parsePrimitive(value, path, name, primitive, ":")
+          results <- Flat.util.parsePrimitive(value, path, name, primitive, ",")
```
Comment (vigoo) [inline core/shared/src/main/scala/zio/ConfigProvider.scala]: Maybe it would worth making this a parameter (and keeping `envProvider` a value that calls it with `","` so if others have values with commas in them they can select another separator?

**Review by jdegoes — APPROVED** [review]
Not sure if this is a fix or not, but personally I prefer comma even though environment variables such as PATH use the colon.

**Comment by adamgfraser** [comment]
I think the problem is that URLs use the colon not as a sequence delimiter. So if we want to support those we can't use the colon as the sequence delimiter, at least not without adding more sophisticated logic like trying to parse text as URLs first or quoting them.

File: core/shared/src/main/scala/zio/ConfigProvider.scala (hunk 1 above)
Comment (adamgfraser) [reply core/shared/src/main/scala/zio/ConfigProvider.scala]: Done.

**Review by jdegoes — APPROVED** [review]
