### PR TITLE
Bug/5948

### LINKED ISSUE #5948: ZIO 2.0: `ArrayIndexOutOfBoundsException` in `FiberContext.captureTrace`
I have run into an apparent bug in `FiberContext.captureTrace`
When I try to dump trace for a fiber that is running in a loop (using `repeatUntil`) I get `ArrayIndexOutOfBoundsException`.

```scala
for {
       promise <- Promise.make[Nothing, Unit]
       fiber1 <- ZIO.yieldNow.repeatUntilZIO(_ => promise.isDone).fork
       dump <- FiberRenderer.dumpStr(Seq(fiber1), withTrace = true)
        _ <- promise.isDone 
} yield ()
```
This fails with: 
```
 Exception in thread "zio-fiber-" java.lang.ArrayIndexOutOfBoundsException: -1
    	at zio.internal.Stack$$anon$1.next(Stack.scala:49)
    	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
    	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
    	at zio.internal.Stack.foreach(Stack.scala:24)
    	at zio.internal.FiberContext.captureTrace(FiberContext.scala:86)
    	at zio.internal.FiberContext.$anonfun$trace$1(FiberContext.scala:831)
    	at zio.internal.FiberContext.runUntil(FiberContext.scala:303)
    	at zio.internal.FiberContext.run(FiberContext.scala:233)
    	at zio.internal.ZScheduler$$anon$1.run(ZScheduler.scala:151)
```
Full example [here](https://github.com/dkarlinsky/zio/blob/3994832b37db20ca9d93946a00b564580edfcbfe/core-tests/shared/src/test/scala/zio/internal/FiberRendererSpec.scala)

### PR DESCRIPTION
**Pull request by jdegoes**
The stack used by FiberContext (`zio.internal.Stack`) was never designed for concurrent access. Given the new stack traces are generated directly from the stack, it is important to allow weakly consistent concurrent reads.

This pull request revises `Stack` to make it suitable for concurrent (weakly consistent) reads.

Fixes #5948

### CODE REVIEW

File: core/shared/src/main/scala/zio/internal/Stack.scala [hunk 1]
```diff
@@ -35,29 +35,61 @@ private[zio] final class Stack[A <: AnyRef]() extends Iterable[A] { self =>
...
-      var currentArray   = self.array
-      var currentIndex   = getUsed - 1
-      var iterated       = 0
-      var currentNesting = self.getNesting
+      var currentArray = self.array
+      var currentIndex = findNonNull(currentArray)
+      var _next        = computeNext()
 
-      def hasNext: Boolean = iterated < self.size
+      private def isMoreChunks(): Boolean = (currentArray ne null) && currentArray(0).isInstanceOf[Array[_]]
```
Comment (mijicd) [inline core/shared/src/main/scala/zio/internal/Stack.scala:42]: `hasMoreChunks`? :)

**Review by mijicd — APPROVED** [review]

**Review by adamgfraser — APPROVED** [review]
