### PR TITLE
Fix sequence config with shorter one issue

### LINKED ISSUE #8604: Cannot replace a sequence config value with a shorter one
#7700 [changed the semantic](https://github.com/zio/zio/pull/7700#discussion_r1070671785) of `ConfigProvider#orElse`  to merging all config values in left biased way.

It works with simple configuration formats, but there is a surprising case where trying to override a sequence with a shorter one.

Example: [Scastie](https://scastie.scala-lang.org/guersam/e7J2Et51Q5ezzfduSAjS1g/25)

```scala
ZIO.config(Config.chunkOf("permissions", Config.string))
  .withConfigProvider(
    fromHoconString("permissions = [admin]") orElse
    fromHoconString("permissions = [read, write]")
  )
  .map { ps =>
    assertTrue(ps == Chunk("admin")) // assertion fails: ps is Chunk("admin", "write")
  }    
```

It's reproducible with the simplest ConfigProvider such as `fromMap` when the sequence is expressed in bracket indexed format like `"foo[0]" -> "a"`.

### PR DESCRIPTION
**Pull request by kyri-petrou**
/closes #8604
/claim #8604

Alternatively, we could check if the sequence on the right starts at a higher index than on the left, but this feels more robust. Thoughts?

### CODE REVIEW

**Comment by kyri-petrou** [comment]
Is CI flaky / stateful in any way? Compiling failed on something irrelevant to the changes in this PR 🤔

**Comment by adamgfraser** [comment]
No there seems to be some kind of nondeterminism in the compiler. 😱

However, looks like it is passing now. Will take a look later.

**Comment by kyri-petrou** [comment]
Who doesn't love some probabilistic type inference 🥲

**Review by adamgfraser — CHANGES_REQUESTED** [review]
So I think this goes in the right direction but we need to go further and say if we successfully enumerate children for a given path from the left we do not enumerate children from the right.

One of our previous guiding principles was that we wanted to prevent "Frankenstein configurations" where a single value contained data from two different configuration providers.

So I would just change the line above the one you edited in the pattern match to accept a wildcard for the right hand side and delete the last branch. Then that will also require changing the test you edited, which I think is incorrectly specified because it creates exactly that kind of Frankenstein configuration where the employees of `parent1` mix data from two different configuration providers.

**Comment by kyri-petrou** [comment]
@adamgfraser funnily enough, my initial fix was to do just what you recommended, but then I saw the test failing and thought there was a reason for it 😅 . Thanks for clarifying, I'll change the code

File: core/shared/src/main/scala/zio/ConfigProvider.scala [hunk 1]
```diff
@@ -209,7 +209,7 @@ object ConfigProvider {
                         case (Left(e1), Left(e2)) => ZIO.fail(e1 && e2)
                         case (Left(_), Right(r))  => ZIO.succeed(r)
                         case (Right(l), Left(_))  => ZIO.succeed(l)
-                        case (Right(l), Right(r)) => ZIO.succeed(l ++ r)
+                        case (Right(l), Right(r)) => ZIO.succeed(if (l.nonEmpty) l else r)
```
Comment (kyri-petrou) [inline core/shared/src/main/scala/zio/ConfigProvider.scala:212]: @adamgfraser I think there might be another bug here. In some cases, a failure on the left side is represented as a `Right(Set())`. Is this the intended behaviour?

Comment (adamgfraser) [reply core/shared/src/main/scala/zio/ConfigProvider.scala:212]: @kyri-petrou Will take a look at clarifying the contract around that!

**Review by adamgfraser — APPROVED** [review]
