### PR TITLE
fix ZSink#collectAllWhileWith (second attempt)

### LINKED ISSUE #3657: ZSink#collectAllWhileWith always returns zero value
RC18-2:
```
@ Stream(1,2,3,5).run(ZSink.sum[Int].collectAllWhileWith(_ => true)(-1)(_ + _)).unsafeRun  
res30: Int = 10
```

RC19-2:
```
@ Stream(1,2,3,5).run(ZSink.sum[Int].collectAllWhileWith(-1)(_ => true)(_ + _)).unsafeRun 
res19: Int = -1
```

### PR DESCRIPTION
**Pull request by simpadjo**
Closes #3657

Not sure how useful this combinator is with the new encoding.
It uses ZSink as a Transducer without a huge disclaimer, (consequently) it has no meaningful laws

FWIW, here is the fix

### CODE REVIEW

File: streams/shared/src/main/scala/zio/stream/ZSink.scala [hunk 1]
```diff
@@ -78,27 +78,13 @@ abstract class ZSink[-R, +E, -I, +Z] private (
...
-                    state
-                      .updateAndGet(f(_, z))
-                      .flatMap(s =>
-                        if (p(z)) restart
-                        else ZIO.fail(Right(s))
-                      )
-                }
-            }
-          }
+    self.toTransducer >>> ZSink
```
Comment (simpadjo) [inline streams/shared/src/main/scala/zio/stream/ZSink.scala:81]: Could be cleaner if we had 
`takeWhile(p: A => Boolean): Transducer[A, Option[A]]`
