### PR TITLE
Make Cause#foldLeft Stack Safe

### LINKED ISSUE #1984: Cause#failureOrCause can stackoverflow but should use
`Cause#failureOrCause` stack-overflows when it's made of many nested `Both`s.
`failures` would overflow as well in this case but case for `failureOrCause` is that is requires only first `Fail`.
Basically there is problem with `foldLeft`.

I stumped on it when I created 10000 failing effects and tried to `foreachPar` them and they completed before being interrupted, so each had time to fail before interruption.

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #1984.

### CODE REVIEW

File: core-tests/shared/src/test/scala/zio/CauseSpec.scala [hunk 1]
```diff
@@ -31,6 +31,13 @@ object CauseSpec
             check(causes) { c =>
               assert(c.untraced.traces.headOption, isNone)
             }
+          },
+          zio.test.test("`Cause.foldLeft is stack safe") {
```
Comment (neko-kai) [inline core-tests/shared/src/test/scala/zio/CauseSpec.scala]: Confused since the test doesn't use `Cause.foldLeft` 😕

Comment (adamgfraser) [reply core-tests/shared/src/test/scala/zio/CauseSpec.scala]: Ah, sorry. `failures` is implemented in terms of `foldLeft` so I was just using it that to test it. Previously this would stack overflow.

Comment (adamgfraser) [reply core-tests/shared/src/test/scala/zio/CauseSpec.scala]: The issue is that `foldLeft` is private so we can't test it directly.

Comment (jozic) [reply core-tests/shared/src/test/scala/zio/CauseSpec.scala]: `private[zio]`?

File: core-tests/shared/src/test/scala/zio/CauseSpec.scala [hunk 2]
```diff
@@ -31,6 +31,13 @@ object CauseSpec
...
+            val n = 100000
+            def causeN(n: Int, acc: Cause[String] = Cause.fail("fail")): Cause[String] =
+              if (n == 1) acc
+              else causeN(n - 1, Both(acc, Cause.fail("fail")))
```
Comment (LGLO) [inline core-tests/shared/src/test/scala/zio/CauseSpec.scala]: No need to change but could be more compact, `List.fill(100000)(Cause.fail("fail")).reduce(_ && _)` or something like that. Recursion is OK.

File: core-tests/shared/src/test/scala/zio/CauseSpec.scala (hunk 1 above)
Comment (adamgfraser) [reply core-tests/shared/src/test/scala/zio/CauseSpec.scala]: I don't think it makes sense to change the signature just to test it when we can easily test other methods that are implemented in terms of it. I can always rename the test to "Cause.failures is stack safe" if that would be clearer.

File: core/shared/src/main/scala/zio/Cause.scala [hunk 3]
```diff
@@ -334,15 +336,22 @@ sealed trait Cause[+E] extends Product with Serializable { self =>
...
-      case (z, Then(left, right)) => right.foldLeft(left.foldLeft(z)(f))(f)
-      case (z, Both(left, right)) => right.foldLeft(left.foldLeft(z)(f))(f)
-      case (z, Traced(cause, _))  => cause.foldLeft(z)(f)
-      case (z, Meta(cause, _))    => cause.foldLeft(z)(f)
-
-      case (z, _) => z
-    }
+  private def foldLeft[Z](z: Z)(f: PartialFunction[(Z, Cause[E]), Z]): Z = {
+    @tailrec
+    def loop(z: Z, cause: Cause[E], stack: List[Cause[E]]): Z =
```
Comment (LGLO) [inline core/shared/src/main/scala/zio/Cause.scala]: Nice trick!

File: core-tests/shared/src/test/scala/zio/CauseSpec.scala (hunk 1 above)
Comment (adamgfraser) [reply core-tests/shared/src/test/scala/zio/CauseSpec.scala]: I updated the test label to make this more clear.

File: core-tests/shared/src/test/scala/zio/CauseSpec.scala (hunk 2 above)
Comment (adamgfraser) [reply core-tests/shared/src/test/scala/zio/CauseSpec.scala]: You're right. I was experimenting with different types of cause "trees". It is only left leaning trees like this that cause stack overflows and I wanted to avoid stack overflows myself as I created this giant tree. Your suggestion accomplishes both these things more concisely. Updated now.

File: core/shared/src/main/scala/zio/Cause.scala (hunk 3 above)
Comment (adamgfraser) [reply core/shared/src/main/scala/zio/Cause.scala]: Thanks!

**Comment by adamgfraser** [comment]
@LGLO Yes you're right. In addition to making the methods stack safe we could terminate the traversal early in some cases. I added a new combinator `find` and implemented the methods that could terminate early in terms of it.

File: core/shared/src/main/scala/zio/Cause.scala [hunk 4]
```diff
@@ -325,24 +309,50 @@ sealed trait Cause[+E] extends Product with Serializable { self =>
...
-  private def foldLeft[Z](z: Z)(f: PartialFunction[(Z, Cause[E]), Z]): Z =
-    (f.lift(z -> self).getOrElse(z), self) match {
-      case (z, Then(left, right)) => right.foldLeft(left.foldLeft(z)(f))(f)
-      case (z, Both(left, right)) => right.foldLeft(left.foldLeft(z)(f))(f)
-      case (z, Traced(cause, _))  => cause.foldLeft(z)(f)
-      case (z, Meta(cause, _))    => cause.foldLeft(z)(f)
+  private def find[Z](f: PartialFunction[Cause[E], Z]): Option[Z] = {
+    @tailrec
+    def loop(cause: Cause[E], stack: List[Cause[E]]): Option[Z] =
+      f.lift(cause) match {
```
Comment (regiskuckaertz) [inline core/shared/src/main/scala/zio/Cause.scala]: I suggest `f.lift(cause) orElse ...` to avoid pattern matching

Comment (adamgfraser) [reply core/shared/src/main/scala/zio/Cause.scala]: The issue is if you do that the recursive call to `loop` is no longer in tail position.

File: core/shared/src/main/scala/zio/Cause.scala [hunk 5]
```diff
@@ -325,24 +309,50 @@ sealed trait Cause[+E] extends Product with Serializable { self =>
...
+        case Some(z) => Some(z)
+        case None =>
+          cause match {
```
Comment (regiskuckaertz) [inline core/shared/src/main/scala/zio/Cause.scala]: This is `cause.foldLeft(None) { case (_, cause) if f.isDefined(cause) => Some(f(cause)) }`, so find could be written as
```scala
private def find[Z](f: PartialFunction[Cause[E], Z]): Option[Z] = {
  f.lift(self) orElse foldLeft(None){ case (_, cause) if f.isDefined(cause) => Some(f(cause)) }
```

File: core/shared/src/main/scala/zio/Cause.scala (hunk 4 above)
Comment (regiskuckaertz) [reply core/shared/src/main/scala/zio/Cause.scala]: Yes indeed 👍 I should have put the comment below with this one 🤦‍♂

File: core/shared/src/main/scala/zio/Cause.scala (hunk 5 above)
Comment (adamgfraser) [reply core/shared/src/main/scala/zio/Cause.scala]: I think this would require us to traverse the entire data structure if `f(lift(self)` is `None`, because then we call `foldLeft` which always traverses the entire data structure. The `PartialFunction` in `foldLeft` controls whether a value from a particular cause will be added to the accumulator but can't terminate the traversal early.

File: core/shared/src/main/scala/zio/Cause.scala [hunk 6]
```diff
@@ -325,24 +309,50 @@ sealed trait Cause[+E] extends Product with Serializable { self =>
...
+      }
+    loop(self, Nil)
+  }
 
-      case (z, _) => z
-    }
+  private def foldLeft[Z](z: Z)(f: PartialFunction[(Z, Cause[E]), Z]): Z = {
+    @tailrec
+    def loop(z: Z, cause: Cause[E], stack: List[Cause[E]]): Z =
+      (f.lift(z -> cause).getOrElse(z), cause) match {
```
Comment (regiskuckaertz) [inline core/shared/src/main/scala/zio/Cause.scala]: You may want to memoize `f.lift` as it create a new object on each invocation.

Comment (regiskuckaertz) [reply core/shared/src/main/scala/zio/Cause.scala]: In fact this is just `f.applyOrElse(z -> cause, _ => z)` in hiding, without the `Option` allocation

Comment (adamgfraser) [reply core/shared/src/main/scala/zio/Cause.scala]: Good point. Will update.

File: core/shared/src/main/scala/zio/Cause.scala (hunk 5 above)
Comment (regiskuckaertz) [reply core/shared/src/main/scala/zio/Cause.scala]: Ha yeah right, you would need lazyness to get around that. Shame, that is elegant:
```scala
private def find[Z](f: PartialFunction[Cause[E], Z]): Option[Z] = {
  f.lift(self) orElse foldLeft(None){ case (z, cause) if f.isDefinedAt(cause) => z orElse Some(f(cause)) }
```
Out of curiosity, why a `PartialFunction` in `foldLeft`?
