### PR TITLE
Fix FiberRuntime observer memory leak

### LINKED ISSUE #10181: Increased GC pressure since ZIO 2.1.20
Hi, I recently updated a large app running in production under heavy load from ZIO 2.1.19 to 2.1.21 and almost immediately noticed an issue - after some warmup number of garbage collections in G1 constantly increases and our app is eventually restarted by VPA in k8s environment. Full GC helps for some time, but then GC spikes occur again. This was never an issue in 2.1.19. I cannot share full heap dump, but can show some findings. @kyri-petrou FYI

162,688 instances of zio.internal.FiberRuntime, loaded by jdk.internal.loader.ClassLoaders$AppClassLoader @ 0x80391e18 occupy 111.45 MB (48.67%) bytes.

Image

Image

### PR DESCRIPTION
**Pull request by hearnadam**
/fixes #10181

This change fixes a memory leak introduced in #9848 due to flipped boolean. The change introduced an optimization attempting to avoid removing observers when a fiber is already complete. Unfortunately, the check was inverted and resulted in `fiber.await` leaking observers.

Thank you to @vladimirkl for reporting and identifying the commit.

### CODE REVIEW

**Review by kyri-petrou — DISMISSED** [review]
Thanks! Can't believe I made that mistake 🤦‍♂️

File: core-tests/shared/src/test/scala/zio/FiberRuntimeSpec.scala [hunk 1]
```diff
@@ -66,6 +66,24 @@ object FiberRuntimeSpec extends ZIOBaseSpec {
         }
       }
     ),
+    suite("observers")(
+      test("removed on uncompleted fiber - bug #10181") {
+        val observerCalled = Ref.unsafe.make(false)
+        for {
+          p              <- Promise.make[Nothing, Unit]
+          fiber          <- ZIO.never.onInterrupt(_ => p.succeedUnit).fork
```
Comment (kyri-petrou) [inline core-tests/shared/src/test/scala/zio/FiberRuntimeSpec.scala]: You need to make sure the fiber here started via another promise, otherwise the `onInterrupt` won't be called

File: core-tests/shared/src/test/scala/zio/FiberRuntimeSpec.scala [hunk 2]
```diff
@@ -66,6 +66,24 @@ object FiberRuntimeSpec extends ZIOBaseSpec {
...
+                 val obs: Exit[Nothing, Unit] => Unit = _ => observerCalled.unsafe.set(true)
+                 fiber.unsafe.addObserver(obs)
+                 fiber.unsafe.removeObserver(obs)
+               }
+          _      <- fiber.interrupt
+          _      <- p.await
+          called <- observerCalled.get
+        } yield assertTrue(!called)
+      }
+    ),
```
Comment (kyri-petrou) [inline core-tests/shared/src/test/scala/zio/FiberRuntimeSpec.scala:86]: Maybe add a `@@ nonFlaky` as well

File: core-tests/shared/src/test/scala/zio/FiberRuntimeSpec.scala (hunk 1 above)
Comment (hearnadam) [reply core-tests/shared/src/test/scala/zio/FiberRuntimeSpec.scala]: Ah yes! That's why it works on my machine but not CI 😁

File: core-tests/shared/src/test/scala/zio/FiberRuntimeSpec.scala (hunk 2 above)
Comment (hearnadam) [reply core-tests/shared/src/test/scala/zio/FiberRuntimeSpec.scala:86]: Yup

**Review by kyri-petrou — APPROVED** [review]
