### PR TITLE
Fix memory leak when recursively flatmapping ZStreams

### LINKED ISSUE #10039: [zio-test] Gen.fromZIO leaks memory
The following test will result in high GC activity and fairly quickly will completely run out of memory.
```scala
test("leak") {
  val genA = Gen.elements("A")
  val genAB = Gen.elements("A", "B")
  val gen = Gen.fromZIO(ZIO.succeed(true)).flatMap(p => if (p) genAB else genA)
  check(gen)(_ => assertTrue(true))
} @@ TestAspect.samples(10000000)
```

Changing `Gen.fromZIO(ZIO.succeeed(true))` to either `Gen.const(true)` or just `Gen.boolean` results in fixed memory use throughout entire duration of the test.
Heap dump shows lots of `ZIO$FlatMap` instances that retain almost all the memory.

### PR DESCRIPTION
**Pull request by kyri-petrou**
/fixes #10039

Not sure how to add a test for this though. I had to do some manual heap dump testing to ensure that this works.

Note that with this change, `Gen` becomes significantly faster. On my Macbook Pro M4, the reproducer took ~1 minute to run without the fix, and ~25 seconds with the fix. It's still a fair bit, but at least it's much faster now

### CODE REVIEW

File: streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala [hunk 1]
```diff
@@ -210,9 +210,16 @@ private[stream] final class ChannelExecutor[Env, InErr, InElem, InDone, OutErr,
             case ZChannel.ConcatAll(combineSubK, combineSubKAndInner, value, k) =>
               val innerExecuteLastClose =
                 (f: URIO[Env, Any]) =>
-                  ZIO.succeed {
-                    closeLastSubstream = if (closeLastSubstream eq null) f else closeLastSubstream *> f
```
Comment (kyri-petrou) [inline streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala:214]: Part of the "leak" was being caused by this. On each `ZStream#flatMap` we were adding a new `*> ZIO.uninterruptible(Exit.unit)`

File: streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala [hunk 2]
```diff
@@ -210,9 +210,16 @@ private[stream] final class ChannelExecutor[Env, InErr, InElem, InDone, OutErr,
...
-                  }
+                  if ((f eq ZIO.unit) || (f eq Exit.unit)) Exit.unit
```
Comment (hearnadam) [inline streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala]: Do you want to use `isNullOrZIOUnit` and add Exit to it?

File: streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala [hunk 3]
```diff
@@ -492,20 +499,14 @@ private[stream] final class ChannelExecutor[Env, InErr, InElem, InDone, OutErr,
     ChannelState.Read(
       self.upstreamExecutor,
       onEffect = (effect: ZIO[Env, Nothing, Unit]) => {
-        val closeLast = ZIO.uninterruptible {
-          val close = this.closeLastSubstream
-          closeLastSubstream = null
-          if (close ne null) close else Exit.unit
-        }
+        val close     = this.closeLastSubstream
+        val closeLast = if (close ne null) ZIO.uninterruptible(close) else ZIO.unit
```
Comment (hearnadam) [inline streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala]: It looks like the reason you are using `ZIO.unit` on line 503 is to suspend the operation after? that should be ok in the general case, since `ZIO.unit.flatMap` is optimized.

File: streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala [hunk 4]
```diff
@@ -492,20 +499,14 @@ private[stream] final class ChannelExecutor[Env, InErr, InElem, InDone, OutErr,
...
-          val closeLast = ZIO.uninterruptible {
-            val close = this.closeLastSubstream
-            closeLastSubstream = null
-            if (close ne null) close else Exit.unit
-          }
+        val close = this.closeLastSubstream
+        if (close ne null) {
+          val closeLast = ZIO.uninterruptible(close)
 
           executeCloseLastSubstream(closeLast).map { _ =>
```
Comment (hearnadam) [inline streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala]: Can you use `flatMap` then return `Exit.unit` here to avoid the allocation?

File: streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala [hunk 5]
```diff
@@ -492,20 +499,14 @@ private[stream] final class ChannelExecutor[Env, InErr, InElem, InDone, OutErr,
...
       onEmit = { (emitted: Any) =>
-        if (this.closeLastSubstream ne null) {
-          val closeLast = ZIO.uninterruptible {
-            val close = this.closeLastSubstream
-            closeLastSubstream = null
-            if (close ne null) close else Exit.unit
-          }
+        val close = this.closeLastSubstream
+        if (close ne null) {
+          val closeLast = ZIO.uninterruptible(close)
```
Comment (hearnadam) [inline streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala]: Can't this result in `uninterruptible(ZIO.unit)`?

**Review by hearnadam — COMMENTED** [review]
Good find!

File: streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala (hunk 2 above)
Comment (hearnadam) [reply streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala]: Ah wait - isn't `closeLastSubstream` being ignored?

Comment (kyri-petrou) [reply streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala]: If `f` is a no-op (i.e., `ZIO.unit` or `Exit.unit`) then we don't need to modify `closeLastSubstream`. We're not doing anything with `closeLastSubstream`, we just add another effect to it in the case that it's not a no-op

Comment (hearnadam) [reply streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala]: Ah yes

File: streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala (hunk 3 above)
Comment (kyri-petrou) [reply streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala]: No actually the reason was just to unify the code path. I  updated the PR and removed the unnecessary flatmap in that case

File: streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala (hunk 5 above)
Comment (kyri-petrou) [reply streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala]: I updated all the code to use `isNullOrZIOUnit` instead

File: streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala (hunk 4 above)
Comment (kyri-petrou) [reply streams/shared/src/main/scala/zio/stream/internal/ChannelExecutor.scala]: Good point, done

**Review by hearnadam — APPROVED** [review]
