### PR TITLE
Fix zio-kafka regression caused by ZStream changes

### LINKED ISSUE #9324: zio-kafka test failures with 2.1.13
See https://github.com/zio/zio-kafka/pull/1400

Tests are timing out where previously they were running fine with 2.1.12. Just a heads up for now and hopefully a good hint for what's wrong, we'll try to pinpoint the issue further. 

> I see this in the logs when I run the "rebalanceSafeCommits prevents processing messages twice when rebalancing" test. Never seen it before, no more context unfortunately:
> 21:47:38.895 [ZScheduler-Worker-4] [consumer=1] DEBUG zio.kafka.consumer.ConsumerLive - Fiber zio-fiber-107 did not handle an error
> zio.FiberFailure: Right(())
> Also when I increase the bufferSize parameter of `plainStream` from 4 to 32 the test succeeds without timeout..

The `bufferSize` parameter is passed to `flatMapPar`. Without that change, I notice that messages are emitted from the stream  with large delays and the test times out.

### PR DESCRIPTION
**Pull request by kyri-petrou**
/fixes #9324

Main change in this PR is the change from `onError` to `catchAllCause`. Frankly, I really don't know why propagating the interruption (same way that we do in `mapZIOPar` and `mapZIOParUnbounded`) causes issues in the `flatMapPar` method for zio-kafka. I also failed to create a reproducer after many hours of trying different things / combinations.

At this stage I'm not even sure whether this is an issue in zio-kafka that it's only been surfaced that the recent ZIO change, but in order to play it safe I reverted the behaviour to be the same as pre-v2.1.13 while I try to get to the bottom of this

### CODE REVIEW

File: streams/shared/src/main/scala/zio/stream/ZChannel.scala [hunk 1]
```diff
@@ -2021,7 +2023,7 @@ object ZChannel {
                              }
                        }
         _ <- pullStrategy(fiberId).forever
-               .onError(cause =>
```
Comment (regiskuckaertz) [inline streams/shared/src/main/scala/zio/stream/ZChannel.scala:2024]: Why not leave it like that and ignore errors? Because that's exactly what I wanted with `catchAllCause` but you demonstrated its surprising behaviour in the face of races

Comment (kyri-petrou) [reply streams/shared/src/main/scala/zio/stream/ZChannel.scala:2024]: There is another key difference between `onError` and `catchAllCause`, which is that in case of interruption `onError` is guaranteed to be invoked, whereas `catchAllCause` won't be unless it's executed within an uninterruptible region.

The cause of the linked issue in this case is that if we use `onError` we're adding the interruption to the queue, whereas if we use `catchAllCause` we're not, which for some reason is causing the issue in zio-kafka

**Review by jdegoes — APPROVED** [review]
