### PR TITLE
Fix unbounded memory usage in flatMapPar and defect handling

### LINKED ISSUE #1008: ZStream#flatMapPar has unbounded memory usage
Every fiber running an inner stream is tracked in a list, so for long running streams with lots of elements, this is pretty destructive.

A better approach would be to invert the relation and have the forked fibers interrupt themselves using a promise signalled by the outer stream.

### PR DESCRIPTION
**Pull request by iravid**
Also changes `Take.Fail` to use a full `Cause` so that defects can be signalled across queues as well.

Resolves #1008.

### CODE REVIEW

File: streams/shared/src/main/scala/zio/stream/ZStream.scala [hunk 1]
```diff
@@ -253,44 +255,44 @@ trait ZStream[-R, +E, +A] extends Serializable { self =>
...
+                    // Make sure that the current inner stream has actually succeeded in acquiring
+                    // a permit before continuing. Otherwise, two bad things happen:
+                    // - we might needlessly fork inner streams without available permits
+                    // - worse, we could reach the end of the stream and acquire the permits ourselves
+                    //   before the inners had a chance to start
+                    _ <- latch.await
+                  } yield ()
+                }.foldCauseM(
+                    cause =>
+                      (interruptInners.succeed(()) *> permits.acquireN(n) *> out
```
Comment (regiskuckaertz) [inline streams/shared/src/main/scala/zio/stream/ZStream.scala]: 🤯 this is nice.

File: streams/shared/src/main/scala/zio/stream/ZStream.scala [hunk 2]
```diff
@@ -253,44 +255,44 @@ trait ZStream[-R, +E, +A] extends Serializable { self =>
...
+                          leftDone = (_, permitAcquisition) => interruptInners.succeed(()) *> permitAcquisition.join,
                           // All fibers completed successfully, so we just need to signal that
                           // we're done.
                           rightDone = (_, failureAwait) => out.offer(Take.End) *> failureAwait.interrupt
                         )
                         .toManaged_
                   )
                   .fork
-            _ <- ZManaged.finalizer(innerFibers.get.flatMap(Fiber.interruptAll))
+            _ <- ZManaged.finalizer(interruptInners.succeed(()))
```
Comment (regiskuckaertz) [inline streams/shared/src/main/scala/zio/stream/ZStream.scala]: Is this still necessary?

Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/ZStream.scala]: Yes, I'll add a comment. It handles the case where the stream after the queue is short-circuited.

There's some overlap between the different ending cases (interruption, short circuiting, etc) but I don't want to look at this combinator again this weekend. :-)

Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/ZStream.scala]: Actually this isn't quite right. Even though we're short circuiting the driver stream would still try to fork all the inner streams (which would get interrupted immediately). I'll fix this now.

Comment (iravid) [reply streams/shared/src/main/scala/zio/stream/ZStream.scala]: Sorry ignore that. `ZManaged#fork` installs a finalizer that interrupts the fiber on the way out so we won't be unnecessarily forking inner streams.

**Comment by iravid** [comment]
@regiskuckaertz Could do that as a follow up. As a benchmark or as a test?

**Comment by regiskuckaertz** [comment]
True, I don't know what a test would prove or how it could measure memory usage.
