### PR TITLE
Ignore should not recover from unchecked exceptions

### LINKED ISSUE #2142: Ignore should not recover from unchecked exceptions
Recently in [this issue](https://github.com/zio/zio/issues/1868) we fixed `ZIO#option` to make it NOT handle unchecked exceptions. The point was that it should be explicit using something like `sandbox`.

I think the same reasoning applies to `ZIO#ignore`. What do you think?

### PR DESCRIPTION
**Pull request by alexvanolst**
Resolves #2142

### CODE REVIEW

File: core-tests/shared/src/test/scala/zio/ZIOSpec.scala [hunk 1]
```diff
@@ -119,6 +119,19 @@ object ZIOSpec
             assertM(ZIO.fail("Fail").head.either, isLeft(isSome(equalTo("Fail"))))
           }
         ),
+        suite("ignore")(
+          testM("return success as Unit") {
+            import zio.CanFail.canFail
```
Comment (ghostdogpr) [inline core-tests/shared/src/test/scala/zio/ZIOSpec.scala]: These imports aren’t needed (that’s what makes the CI fail).

Comment (alexvanolst) [reply core-tests/shared/src/test/scala/zio/ZIOSpec.scala]: Thanks 👍 I had those in from adapting the `.option` tests

**Comment by ghostdogpr** [comment]
The change breaks the tests “Invokes cleanups on interrupt“ in ZManagedSpec because they expect the old behavior. I think you can just adapt those tests.
