### PR TITLE
Ensure ZLayer macros use the trace from implicit scope

### LINKED ISSUE #9352: Ambiguous implicit value for zio.Trace with ZIO 2.1.13
```scala
import zio._

object Dummy {
  trait Dep

  def call[R: Tag](implicit trace: Trace): URIO[R, Unit] =
    ZIO
      .serviceWithZIO[Dep](_ => ZIO.service[R].unit)
      .provideSome[R](ZLayer.succeed(new Dep {}))
}
```
This snippet fails with:
```bash
ambiguous implicit values:
[error]  both value trace of type zio.Trace
[error]  and value trace$macro$4 of type zio.Trace
[error]  match expected type zio.Trace
```
`scala: 2.13.15`
`zio: 2.1.13`
Previous versions do not have this problem, [scastie link](https://scastie.scala-lang.org/cipriansofronia/4eMtdcFkSieKOik3K1nxWA/6).

### PR DESCRIPTION
**Pull request by joroKr21**
Fix #9352
/claim #9352

### CODE REVIEW

File: core-tests/shared/src/test/scala/zio/autowire/AutoWireSpec.scala [hunk 1]
```diff
@@ -212,6 +213,22 @@ object AutoWireSpec extends ZIOBaseSpec {
...
+                Trace.empty
+              }
+
+              ZLayer.make[String](
+                ZLayer.succeed(42),
+                ZLayer.fromFunction((_: Int).toString)
+              )
+            }
+
+            assertZIO(layer.build.as(numTraces))(equalTo(3))
```
Comment (kyri-petrou) [inline core-tests/shared/src/test/scala/zio/autowire/AutoWireSpec.scala:231]: Thank you, at least now I won't have to remember why we had to do use explicit tags in the macros in the future 🥲

**Review by kyri-petrou — APPROVED** [review]

File: core-tests/shared/src/test/scala/zio/autowire/AutoWireSpec.scala (hunk 1 above)
Comment (joroKr21) [reply core-tests/shared/src/test/scala/zio/autowire/AutoWireSpec.scala:231]: This test was really hard to come up with 🤣
