### PR TITLE
Ensure UnsafeAPI performs stateful updates within fiber (#9040)

### LINKED ISSUE #9040: Fiber observers may not be called
We were fairly reliably experiencing deadlocks in our tests. It took a while to reproduce locally but I eventually tracked it down to `toEffect` from `interop-cats` (https://github.com/zio/interop-cats/issues/694).

Digging a bit deeper it seems that actually the issue is that the callback passed to `addObserver` might not be called. The same problem affects `zio.Runtime.default.run` and likely anything else that uses `addObserver`.

Here is a minimal reproduction:
```
      test("observers must be called") {
        ZIO.loopDiscard(1)(_ <= 1_000_000, _ + 1) { n =>
          Runtime.default.run(ZIO.succeed(n))
        }.map(_ => assertTrue(true))
      }
```

On my local environment that will hang by about the 150,000th iteration although it is highly dependent on timing.

There are a few different problems. The modifications to `observers` are non-atomic and can interleave. Also there is no mutex around the `_exitValue` check and the modification to `observers`.

### PR DESCRIPTION
**Pull request by steinybot**
Take 2.

Fixes #9040

### CODE REVIEW

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala [hunk 1]
```diff
@@ -1487,7 +1488,7 @@ final class FiberRuntime[E, A](fiberId: FiberId.Runtime, fiberRefs0: FiberRefs,
   def unsafe: UnsafeAPI =
     new UnsafeAPI {
       def addObserver(observer: Exit[E, A] => Unit)(implicit unsafe: Unsafe): Unit =
-        self.addObserver(observer)
+        self.tell(FiberMessage.Stateful(_.asInstanceOf[FiberRuntime[E, A]].addObserver(observer)))
```
Comment (kyri-petrou) [inline core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: Perhaps let's avoid the message passing and restarting of the fiber when the _exitValue is already set:

```suggestion
        val exit = _exitValue
        if (exit ne null) observer(exit)
        else self.tell(FiberMessage.Stateful(_.asInstanceOf[FiberRuntime[E, A]].addObserver(observer)))
```

Comment (kyri-petrou) [reply core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: ~~Also, do we need the `asInstanceOf`? Doesn't seem to me like it's needed~~

Ahh type inference doesn't work well

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala [hunk 2]
```diff
@@ -1496,7 +1497,7 @@ final class FiberRuntime[E, A](fiberId: FiberId.Runtime, fiberRefs0: FiberRefs,
         self.getFiberRefs()
 
       def removeObserver(observer: Exit[E, A] => Unit)(implicit unsafe: Unsafe): Unit =
-        self.removeObserver(observer)
+        self.tell(FiberMessage.Stateful(_.asInstanceOf[FiberRuntime[E, A]].removeObserver(observer)))
```
Comment (kyri-petrou) [inline core/shared/src/main/scala/zio/internal/FiberRuntime.scala:1502]: As above

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala [hunk 3]
```diff
@@ -37,14 +37,15 @@ final class FiberRuntime[E, A](fiberId: FiberId.Runtime, fiberRefs0: FiberRefs,
...
-  private var _children       = null.asInstanceOf[JavaSet[Fiber.Runtime[_, _]]]
+  private var _lastTrace     = fiberId.location
+  private var _fiberRefs     = fiberRefs0
+  private var _runtimeFlags  = runtimeFlags0
+  private var _blockingOn    = FiberRuntime.notBlockingOn
+  private var _asyncContWith = null.asInstanceOf[ZIO.Erased => Any]
+  private val running        = new AtomicBoolean(false)
+  private val inbox          = new ConcurrentLinkedQueue[FiberMessage]()
+  private var _children      = null.asInstanceOf[JavaSet[Fiber.Runtime[_, _]]]
+  @volatile
```
Comment (kyri-petrou) [inline core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: Sorry for the nitpick, but for consistency, can you inline the annotation with the var definition? Also perhaps move it to the line above the `_exitValue` so that volatile vars are grouped together

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala (hunk 1 above)
Comment (steinybot) [reply core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: > Perhaps let's avoid the message passing and restarting of the fiber when the _exitValue is already set:

The issue there is that the observers could be notified out of order. The thread that has `_exitValue` might not have gotten to notifying the observers yet and so this observer will be notified too early. There is a comment in there that implies that notification order is important.

> Also, do we need the asInstanceOf? Doesn't seem to me like it's needed

Unfortunately yes I think so. It is a wildcard type:
```
final case class Stateful(onFiber: FiberRuntime[_, _] => Unit) extends FiberMessage
```
This does something similar: https://github.com/zio/zio/blob/8168cddf5026b9fe507f745c3d11d2f82836aeb6/core/shared/src/main/scala/zio/Runtime.scala#L137-L139

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala (hunk 3 above)
Comment (steinybot) [reply core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: Nitpick away. I'm a nitpicker myself 😆

Comment (steinybot) [reply core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: Done

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala (hunk 1 above)
Comment (kyri-petrou) [reply core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: > There is a comment in there that implies that notification order is important.

I think notification order is only required when we need them to be strictly ordered (i.e., if I add 2 observers one after the other then I want to make sure they're called in the right order). But for other observers we really shouldn't care, so it's OK to do that.

Also, we've been doing this exact thing so far and we didn't have any issues with ordering, so I highly doubt it'll be an issue.

Comment (kyri-petrou) [reply core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: > his does something similar:

I was going to mention this, since we're at it, can you also change that to use `unsafe.addObserver` now?

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala [hunk 4]
```diff
@@ -65,6 +64,7 @@ final class FiberRuntime[E, A](fiberId: FiberId.Runtime, fiberRefs0: FiberRefs,
     Metric.runtime.fiberForkLocations.unsafe.update(fiberId.location.toString, tags)(Unsafe.unsafe)
   }
 
+  @volatile private var observers  = Nil: List[Exit[E, A] => Unit]
```
Comment (steinybot) [inline core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: I'm not sure if this still needs to be volatile. All access using the public API is now using `tell` which I assume will create a happens-before relationship as required. There might still be some non-public places but I suspect happens-before will be established there too although not at all confident on this.

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala (hunk 1 above)
Comment (steinybot) [reply core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: Done. There were a couple others too.

File: core/shared/src/main/scala/zio/internal/FiberRuntime.scala (hunk 4 above)
Comment (kyri-petrou) [reply core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: I think let's change it back to having it as non-volatile. Volatile vars require extra memory and they're slower to initialize. Since we need FiberRuntime to be as lightweight as humanly possible, let's revert this change and we can revisit it if issues come up again

Comment (steinybot) [reply core/shared/src/main/scala/zio/internal/FiberRuntime.scala]: Done.

**Review by kyri-petrou — APPROVED** [review]
Thanks! ❤️
