### PR TITLE
Reduce generated code size for ZLayer.make

### LINKED ISSUE #8855: ZLayer.make fails with ClassTooLarge
This is with `val ScalaVersion = "3.3.3"` and `val ZioVersion = "2.0.22"` on an open source application, but I couldn't make a showcase within reasonable time, it is quite difficult. I couldn't figure out a way to make any failing cases from scratch. I managed to refactor it in a way that cancels the problem for now, but that also takes quite a bit of time, so I'm making this issue because maybe the bug is easier to test on your end. Our layer definitions look like this: [LayersLive.scala](https://github.com/dasch-swiss/dsp-api/blob/1dcf47b/webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala), though I don't expect you to build this project yourself (although you can of course), but I would also have to publish the branch.

```
[info] Build triggered by ~/dsp-api/webapi/src/main/scala/org/knora/webapi/core/LayersLive.scala. Running 'clear; Test/compile'.
[info] compiling 1 Scala source to ~/dsp-api/webapi/target/scala-3.3.3/classes ...
scala.tools.asm.ClassTooLargeException: Class too large: org/knora/webapi/core/LayersLive$
        at scala.tools.asm.ClassWriter.toByteArray(ClassWriter.java:621)
  | => wat dotty.tools.backend.jvm.PostProcessor.serializeClass(PostProcessor.scala:72)
        at dotty.tools.backend.jvm.PostProcessor.postProcessAndSendToDisk$$anonfun$2(PostProcessor.scala:31)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
        at dotty.tools.backend.jvm.PostProcessor.postProcessAndSendToDisk(PostProcessor.scala:48)
        at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:80)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:327)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:331)
        at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:87)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:246)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:262)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:270)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:279)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:71)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:279)
        at dotty.tools.dotc.Run.compileSources(Run.scala:194)
        at dotty.tools.dotc.Run.compile(Run.scala:179)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
        at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:136)
        at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
        at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
        at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
        at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
        at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
        at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
        at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
        at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
        at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
        at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
        at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:180)
        at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:178)
        at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:464)
        at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
        at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
        at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
        at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
        at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:419)
        at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
        at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:406)
        at sbt.internal.inc.Incremental$.apply(Incremental.scala:172)
        at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
        at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
        at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
        at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
        at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
        at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2371)
        at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2321)
        at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:31)
        at sbt.internal.io.Retry$.apply(Retry.scala:47)
        at sbt.internal.io.Retry$.apply(Retry.scala:29)
        at sbt.internal.io.Retry$.apply(Retry.scala:24)
        at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
        at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2319)
        at scala.Function1.$anonfun$compose$1(Function1.scala:49)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
        at sbt.std.Transform$$anon$4.work(Transform.scala:69)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
        at sbt.Execute.work(Execute.scala:292)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
[error] Error while emitting org/knora/webapi/core/LayersLive$
[error] Class too large: org/knora/webapi/core/LayersLive$
[error] one error found
```

### PR DESCRIPTION
**Pull request by joroKr21**
fixes #8855
/claim #8855

 - generate a single trace at the top of the block
 - cache the empty layer
 - apply vertical composition by value
 - keep horizontal composition as-is to preserve semantics

### CODE REVIEW

File: core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala [hunk 1]
```diff
@@ -3,124 +3,100 @@ package zio.internal.macros
...
+      case '{ZLayer.Debug.mermaid} => ZLayer.Debug.Mermaid
+    }
 
-    def loop(tpe: TypeRepr): List[TypeRepr] =
-      tpe.dealias.simplified match {
-        case AndType(lhs, rhs) =>
-          loop(lhs) ++ loop(rhs)
+    '{
+      given trace: Trace = Tracer.newTrace
+      val empty = ZLayer.succeed(())
```
Comment (kyri-petrou) [inline core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala]: Very minor, but should we perhaps store this in a val globally to avoid the creation of a `Function0` here? Or do we need to create it here for the trace implicit?

Comment (joroKr21) [reply core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala]: That's a good question - this will never fail so we don't really need a trace. If we want to add `ZLayer.unit` to the API, I can do that.

Comment (kyri-petrou) [reply core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala]: Yeah let's do that but maybe make it `private[zio]` since I don't think there's a use-case outside of the `zio` codebase

Comment (joroKr21) [reply core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala]: Inlined code must be accessible. If it's not accessible probably an accessor will be generated which not great for binary compatibility. My rule of thumb is that if the inlined code is copy-pasted in user land it should keep working.

Comment (kyri-petrou) [reply core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala]: Ah my bad, that's a good point. I think it's okay making it public then 👍

File: core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala [hunk 2]
```diff
@@ -3,124 +3,99 @@ package zio.internal.macros
...
+      case '{ZLayer.Debug.tree} => ZLayer.Debug.Tree
+      case '{ZLayer.Debug.mermaid} => ZLayer.Debug.Mermaid
+    }
 
-    def loop(tpe: TypeRepr): List[TypeRepr] =
-      tpe.dealias.simplified match {
-        case AndType(lhs, rhs) =>
-          loop(lhs) ++ loop(rhs)
+    '{
+      given trace: Trace = Tracer.newTrace
```
Comment (kyri-petrou) [inline core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala]: Minor: Is it possible to make this an `implicit val` instead. Scala 3 `given` are lazy (similar to `implicit lazy val`) and they generate extra bytecode

File: core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala [hunk 3]
```diff
@@ -3,124 +3,99 @@ package zio.internal.macros
...
+      val compose = [R1, O1, O2] => (lhs: ZLayer[R1, E, O1], rhs: ZLayer[O1, E, O2]) => lhs.to(rhs)
```
Comment (kyri-petrou) [inline core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala:51]: Should we create one of these for `++` as well so that we don't pass the RHS layer by-name?

**Review by kyri-petrou — COMMENTED** [review]
I think it LGTM, I built it locally and tested it against a Scala 3 service and everything seems to work as expected. Just some minor comments below

File: core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala (hunk 2 above)
Comment (kyri-petrou) [reply core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala]: If that's not possible, then maybe do this so that the given becomes the equivalent of `implicit def`:

```scala
val trace = Tracer.newTrace
given Trace = trace
```

Comment (joroKr21) [reply core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala]: Sure, I think either should be possible 👍

File: core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala (hunk 3 above)
Comment (joroKr21) [reply core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala:51]: I find it that keeping `++` by name strikes the right balance between method size and class size. Basically the issue is that if we pass everything by value the method becomes too large and if we pass everything by name it creates too many lambdas (which are lifter to static methods by Scala 3).

File: core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala [hunk 4]
```diff
@@ -3,124 +3,99 @@ package zio.internal.macros
...
 
-        case AppliedType(_, TypeBounds(_,_) :: _) =>
-          List.empty
+      ${
+        def typeToNode(tpe: TypeRepr): Node[TypeRepr, LayerExpr[E]] =
```
Comment (kyri-petrou) [inline core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala:54]: Just for my own understanding: Is there a difference in having this method and the ones below as methods as opposed to making them into lambdas?

From what I can tell they're all used as arguments to methods that accept lambdas. Doesn't that cause additional code to be generated by the compiler?

File: core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala [hunk 5]
```diff
@@ -3,124 +3,99 @@ package zio.internal.macros
...
+          Node(Nil, List(tpe), tpe.asType match { case '[t] => '{ZLayer.environment[t]} })
```
Comment (kyri-petrou) [inline core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala]: Do you know whether the tracing implicit is reachable here? Shall we do this just to be safe?

```suggestion
          Node(Nil, List(tpe), tpe.asType match { case '[t] => '{ZLayer.environment[t](using trace)} })
```

**Review by kyri-petrou — COMMENTED** [review]
Apologies for the noobish questions, I'm trying to get a better understanding of the macros myself 😓

File: core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala (hunk 4 above)
Comment (joroKr21) [reply core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala:54]: There's no difference, I just tried to have a little bit of consistency where bigger pieces of logic get their own methods but simple stuff like `_ <:< _` remain lambdas.

File: core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala (hunk 5 above)
Comment (joroKr21) [reply core/shared/src/main/scala-3/zio/internal/macros/LayerMacroUtils.scala]: Yeah, that might be a good idea. I'm still getting used to Scala 3 macros so I'm also not really sure.

**Comment by jdegoes** [comment]
@joroKr21 Nice work here! Good to merge after conflicts are fixed. 👍

**Review by jdegoes — APPROVED** [review]
