### PR TITLE
Fix Type Safety Issue with ZIO#refineToOrDie

### LINKED ISSUE #2355: refineToOrDie does not constrain E1 witn E
```scala
final def refineToOrDie[E1: ClassTag](implicit ev1: E <:< Throwable, ev2: CanFail[E]): ZIO[R, E1, A]
```
this signature does not constrain `E1` with `E`, letting unsound code like the one below compile
```scala
  ZIO
    .fail(new RuntimeException("BOO!"))
    .refineToOrDie[Error]
```

Naively this can be fixed with something like this
```scala
  implicit final class ZioOps[R, E, A](self: ZIO[R, E, A]) {
    final def refineToOrDie1[E1 <: E : ClassTag](implicit ev1: E <:< Throwable, ev2: CanFail[E]): ZIO[R, E1, A] =
      self.refineOrDieWith { case e: E1 => e }(ev1)
  }
```
and it will result in a compile error
```
type arguments [Error] do not conform to method refineToOrDie1's type parameter bounds [E1 <: RuntimeException]
```

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #2355.

### CODE REVIEW

File: core/shared/src/main/scala/zio/ZIO.scala [hunk 1]
```diff
@@ -2644,6 +2638,15 @@ object ZIO extends ZIOFunctions {
     def toManaged: ZManaged[R, E, A] = ZManaged.fromAutoCloseable(io)
   }
 
+  implicit final class ZioRefineToOrDieOps[R, E <: Throwable, A](private val self: ZIO[R, E, A]) extends AnyVal {
+
+    /**
+     * Keeps some of the errors, and terminates the fiber with the rest.
+     */
+    final def refineToOrDie[E1 <: E: ClassTag](implicit ev: CanFail[E]): ZIO[R, E1, A] =
```
Comment (neko-kai) [inline core/shared/src/main/scala/zio/ZIO.scala]: Is the implicit class necessary? Does
```scala
final def refineToOrDie[E1 <: E: ClassTag](implicit ev1: E <:< Throwable, ev2: CanFail[E]): ZIO[R, E1, A] =
```
behave differently?

Comment (adamgfraser) [reply core/shared/src/main/scala/zio/ZIO.scala]: That won't compile because the covariant `E` appears in contravariant position in the type bound, which is why we need the implicit class.

Comment (neko-kai) [reply core/shared/src/main/scala/zio/ZIO.scala]: Got it!
