### PR TITLE
Use fresh names for compose helper method in layer macro

### LINKED ISSUE #9011: type parameter E defined in method compose$macro$3 shadows type E defined in method
The following code sample compiles fine with ZIO 2.1.2 but fails with 2.1.3/2.1.4/2.1.5 and seem to compile back fine with 2.1.6.

```scala
def someProgram[E] :  IO[E, Unit] = {
    val someEffect: ZIO[String, E, Unit] = ZIO.serviceWith[String] { client =>
      println(client)
      ()
    }
    val clientLayer: ZLayer[Any, Nothing, String] = ZLayer.succeed("client")
    someEffect.provide(clientLayer)
  }
```

Error:
```
[error] /home/.../MyFile.scala:37:23: type parameter E defined in method compose$macro$3 shadows type E defined in method someProgram. You may want to rename your type parameter, or possibly remove it.
[error]     someEffect.provide(clientLayer)
[error]                       ^
```

Note that it's a simplified code sample, I've also got a slightly more complex code sample where version 2.1.6 still raises the error (it was fine with 2.1.2).

Scala 2.13.14

### PR DESCRIPTION
**Pull request by joroKr21**
Also pass the trace explicitly to `ZLayer.environment`, because it's no longer implicit.

Closes #9011

### CODE REVIEW

File: core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala [hunk 1]
```diff
@@ -46,14 +46,60 @@ private[zio] trait LayerMacroUtils {
...
+        List(q"""
+          def $compose[$R, $E, $O1, $O2](lhs: $layerSym[$R, $E, $O1], rhs: $layerSym[$O1, $E, $O2]) =
+            lhs.to(rhs)($trace)
+        """)
+      } else {
+        Nil
+      }
+
+      c.Expr(q"""
+        val $trace: ${typeOf[Trace]} = ${reify(Tracer)}.newTrace
```
Comment (kyri-petrou) [inline core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: I believe this is going to bring back #8986, won't it?

Comment (joroKr21) [reply core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: Now we use it also for `ZIO.environment` - I think this means always?

Comment (kyri-petrou) [reply core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: I published locally your branch and it seems it does bring it back. Given the script below:

```scala
//> using scala "2.13.14"
//> using dep "dev.zio::zio::2.1.6+16-c49fcb17-SNAPSHOT"
//> using options -Xlint -Xfatal-warnings -Ywarn-macros:after -Wunused:locals

import zio._

object Foo {
  def foo = ZIO.unit.provide(ZLayer(ZIO.unit))
}
```

Running `scala-cli compile .` raises the following warning/error:

```
Compiling project (Scala 2.13.14, JVM (21))
[error] ./src/testy.scala:8:29
[error] local val trace$macro$1 in method foo is never used
[error]   def foo = ZIO.unit.provide(ZLayer(ZIO.unit))
[error]  
```

Comment (kyri-petrou) [reply core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: PS: We probably need to set up a unit test for this, I'm just really not sure how to test for generated code :/

Comment (joroKr21) [reply core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: Why would you provide a unit layer 😄

Comment (joroKr21) [reply core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: Basically this is the issue `-Ywarn-macros:after` - too strict warnings

Comment (kyri-petrou) [reply core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: > Why would you provide a unit layer 😄

@joroKr21 that was just a minimization. Providing unit layers is in fact a very common thing. e.g., this raises the same warning

```scala
//> using scala "2.13.14"
//> using dep "dev.zio::zio::2.1.6+16-c49fcb17-SNAPSHOT"
//> using options -Xlint -Xfatal-warnings -Ywarn-macros:after -Wunused:locals

import zio._

object Foo {
  def foo = ZIO.unit.provide(Runtime.enableCooperativeYielding)
}
```

Comment (kyri-petrou) [reply core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: > Basically this is the issue -Ywarn-macros:after - too strict warnings

I know, but since users do use that compiler flag we shouldn't introduce a change that will break their code

Comment (joroKr21) [reply core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: So we need to pull up that var flag - let me check if it can be done easily

Comment (joroKr21) [reply core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: I added another mutable flag 🙈

**Review by kyri-petrou — APPROVED** [review]
Thanks!

File: core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala (hunk 1 above)
Comment (som-snytt) [reply core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: I just noticed the PR in my feed -- I must be following someone -- I haven't tried it yet with this PR, but the new normal is
```
 -Wmacros:default
```
which means only user code contributes definitions to check, and the macro expansion can only provide references that consume them.

Comment (som-snytt) [reply core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: I didn't intend to become a reviewer, I was just sayin. 😅

Comment (kyri-petrou) [reply core/shared/src/main/scala-2/zio/internal/macros/LayerMacroUtils.scala]: @som-snytt that's a good point, although unfortunately we still have to account for people using `-Ywarn-macros:after`. It's quite annoying for users to update the version of a library and get unused local value compiler errors totally unaware they're coming from ZIO's macros :/

> I didn't intend to become a reviewer, I was just sayin

And no worries, thanks for your input!
