### PR TITLE
ZIO Test: Fix Subtype Assertion

### LINKED ISSUE #2970: ZIO Test: Subtype Assertion Does Not Work with Primitive Types
The following test fails:

```scala
test("isSubtype") {
  assert(1)(isSubtype[Int](anything))
}
```

The reason appears to be that the `runtimeClass` of the `ClassTag` is `int` but the class of the actual value is `java.lang.Integer`. We probably need some special logic to handle these types.

Thanks to @sken77 for reporting!

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #2970. Class tags have an unapply method that contains special logic for handling primitive types we can use.

### CODE REVIEW

File: test/shared/src/main/scala/zio/test/Assertion.scala [hunk 1]
```diff
@@ -597,10 +597,7 @@ object Assertion extends AssertionVariants {
    * }}}
    */
   def isSubtype[A](assertion: Assertion[A])(implicit C: ClassTag[A]): Assertion[Any] =
-    Assertion.assertionRec("isSubtype")(param(className(C)))(assertion) { actual =>
-      if (C.runtimeClass.isAssignableFrom(actual.getClass())) Some(actual.asInstanceOf[A])
-      else None
-    }
+    Assertion.assertionRec("isSubtype")(param(className(C)))(assertion)(C.unapply(_))
```
Comment (iravid) [inline test/shared/src/main/scala/zio/test/Assertion.scala]: TIL about ClassTag.unapply!
