### PR TITLE
fix : ZStream Broadcastdynamic hanging

### LINKED ISSUE #9430: ZStream#broadcastDynamic hangs
My ZIO never ends

```scala
import zio._
import zio.stream._

object Main extends ZIOAppDefault {

  val stream = ZStream.fromIterable(Range(0, 10).toList).tap(i => ZIO.debug(s"stream ${i}"))

  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] =
    (for {
      i <- stream.broadcastDynamic(2)
      _ <- ZIO.debug("fan out")
      res <- i.tap(x => ZIO.debug("i " + x)).runDrain
      _ <- ZIO.debug("end")
    } yield res).debug
}
```

I was wondering what could be the cause.

### PR DESCRIPTION
**Pull request by gkfabs**
/closes #9430
/claim #9430

This PR fixes Issue https://github.com/zio/zio/issues/9430 by

- Removing scope from bounded hub and using queue with shutdown just like broadcast function
- adding tests

The fix looks too easy to me, I'm afraid of missing out something, but the test pass.

### CODE REVIEW

File: streams/shared/src/main/scala/zio/stream/ZStream.scala [hunk 1]
```diff
@@ -3436,7 +3436,7 @@ final class ZStream[-R, +E, +A] private (val channel: ZChannel[R, Any, Any, Any,
     capacity: => Int
   )(implicit trace: Trace): ZIO[R with Scope, Nothing, Hub[Take[E1, A1]]] =
     for {
-      hub <- ZIO.acquireRelease(Hub.bounded[Take[E1, A1]](capacity))(_.shutdown)
+      hub <- Hub.bounded[Take[E1, A1]](capacity)
```
Comment (guizmaii) [inline streams/shared/src/main/scala/zio/stream/ZStream.scala]: So we never close the Hub? 🤔 Or is it closed by the `runIntoHubScoped`?

Comment (gkfabs) [reply streams/shared/src/main/scala/zio/stream/ZStream.scala]: To me the Hub is closed by the `fromQueueWithShutdown` function line 346

Comment (gkfabs) [reply streams/shared/src/main/scala/zio/stream/ZStream.scala]: I just rollback this line, because as you mention the Hub may not be closed.

**Comment by kyri-petrou** [comment]
@gkfabs just FYI the `/claim` command needs to go in the description of the PR. I edited it for you but you need to configure your account now to receive payments via Algora. Let me know once you've done that

**Review by kyri-petrou — COMMENTED** [review]
I think this kind of escapes the context of this PR, but looking at `broadcastDynamic` I feel like the description is not quite aligned with the implementation, and that's partially due to the return type:

```scala
ZIO[R & Scope, Nothing, ZStream[Any, E, A]]
```

Unless I'm missing something, `broadcastDynamic` is currently more or less the equivalent of doing the following:

```scala
stream.broadcast(1, 2).map(_.head)
```

If we wanted for it to behave the way it's supposed to (at least according to the description) the return type should have been the following, where the outer effect fans out the stream and the inner effect creates a new stream dynamically.

```scala
ZIO[R & Scope, Nothing, URIO[Scope, ZStream[Any, E, A]]]
```

What are your thoughts on this? I'm a bit confused at what's the actual use-case for `broadcastDynamic` given its current behaviour

**Comment by gkfabs** [comment]
It makes sense to me to change the return type of `broadcastDynamic` based on its description to
```
ZIO[R & Scope, Nothing, URIO[Scope, ZStream[Any, E, A]]]
```
The current implementation doesn't produce a dynamic number of streams. It just produce one stream.

**Review by kyri-petrou — APPROVED** [review]
Happy to approve this, and we can explore deprecating the method and changing it in the future
