### PR TITLE
Fix interruption propagation in `ZChannel#mapOutPar*` methods

### LINKED ISSUE #9303: Flaky tests causing CI failures
Following tests have been causing CI failures recently:

- CheckSpec / checkAllPar effect type is correctly inferred ([logs](https://github.com/zio/zio/actions/runs/11831467283/job/32966664135))
- ZStreamSpec / Combinators / mapZIOPar / parallelism is not exceeded ([logs](https://github.com/zio/zio/actions/runs/11815850244/job/32917903670))

We need to check whether the tests are flaky due to a flaky test implementation or a bug in the methods used by the tests

/cc @clarzte

### PR DESCRIPTION
**Pull request by kyri-petrou**
/fixes #9303
/cc @regiskuckaertz

> [!NOTE]
> A large number of changes in this PR are due to whitespaces. Make sure to review it with whitespace diff ignored

A previous PR (https://github.com/zio/zio/pull/9123) introduced some flakiness in a number of tests where `ZChannel#mapOutPar*` methods are involved. After some extensive investigation, the issue is due to race conditions in the propagation of interruption from the parent fiber to the forked fibers.

This PR fixes it through these main changes:

1. Create a fork of the parent scope and fork worker fibers using `forkIn(childScope)`. If the `errorSignal` succeeds, then close the child scope. This ensures that all in-progress worker fibers are interrupted prior to closing the stream. This is the same behaviour as with the previous implementation, but without using `race` for each forked worker to await on the error signal.
2. Use `onExit` rather than `catchAllCause` when handling errors in the main loop. We need to do this because `catchAllCause` will not be executed in cases that we're within an interruptible region and the parent fiber is interrupted.

### CODE REVIEW

File: streams/shared/src/main/scala/zio/stream/ZChannel.scala [hunk 1]
```diff
@@ -752,54 +750,53 @@ sealed trait ZChannel[-Env, -InErr, -InElem, -InDone, +OutErr, +OutElem, +OutDon
...
               case s: Exit.Success[OutElem2] => ZChannel.write(s.value) *> writer
               case f: Exit.Failure[Either[Unit, OutDone]] =>
+                def extractFailures = ZChannel.unwrap(failure.get.map(ZChannel.refailCause(_)))
                 f.cause.failureOrCause match {
-                  case Left(_: Left[Unit, OutDone])  => ZChannel.unwrap(failure.get.map(ZChannel.refailCause(_)))
-                  case Left(x: Right[Unit, OutDone]) => ZChannel.succeedNow(x.value)
-                  case Right(cause)                  => ZChannel.refailCause(cause)
+                  case Left(_: Left[Unit, OutDone])    => extractFailures
+                  case Left(x: Right[Unit, OutDone])   => ZChannel.succeedNow(x.value)
+                  case Right(c) if c.isInterruptedOnly => extractFailures
```
Comment (kyri-petrou) [inline streams/shared/src/main/scala/zio/stream/ZChannel.scala:798]: @regiskuckaertz I noticed that this case was missing here but was present in `mapOutZIOPar`. Was this intentional?

Comment (regiskuckaertz) [reply streams/shared/src/main/scala/zio/stream/ZChannel.scala:798]: no, thank you for fixing 🙏

**Review by regiskuckaertz — APPROVED** [review]
